### ISSUE TITLE
Yoga Pose Detection

### ISSUE THREAD

**Issue by hridayK** [abhisheks008/DL-Simplified#101]
### Deep Learning Simplified Repository (Proposing new issue)
:red_circle: **Yoga Pose Classifier** : </br>
:red_circle: **To classify yoga postures from a video stream** : </br>
:red_circle: **http://download.tensorflow.org/data/pose_classification/yoga_poses.zip** : </br>
:red_circle: **Approach** : Try to make a classifier model based on body points detected from images and use the trained model for detecting postures on videos (can be from live camera or a stream of already shot video)

**********************************************************************************
### 📍 **Follow the Guidelines to Contribute in the Project :**
* You need to create a separate folder named as the Project Title.
* Inside that folder, there will be four main components.
   * Images - To store the required images.
   * Dataset - To store the dataset or, information/source about the dataset.
   * Model - To store the machine learning model you've created using the dataset.
   * `requirements.txt` - This file will contain the required packages/libraries to run the project in other machines.
* Inside the `Model` folder, the `README.md` file must be filled up properly, with proper visualizations and conclusions.

***********************************************************************
:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include issue number along with it.
- Follow Contributing Guidelines & Code of Conduct before start Contributing.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Hriday Keswani
- GitHub Profile Link : https://github.com/hridayK
- Email ID : hridaykeswani@gmail.com
- Participant ID (if applicable):
- Approach for this Project : Use MoveNet model to extract data points from images and train a Machine Leaning model to classify poses
- What is your participant role? (Mention the Open Source program) Participant SSOC'22

*************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by abhisheks008** [comment]
Nice project chosen. I have renamed the project as **Yoga Pose Detection**, follow this naming pattern through out the whole implementation of your project. And try to use more than 2-3 models so that you can compare the models by using their accuracy scores and find the best fitted one.

Best wishes, issue assigned to you @hridayK

**Comment by abhisheks008** [comment]
@hridayK updates please.

**Comment by hridayK** [comment]
Really sorry I won't be able to match the timeline of SSOC, but so far have been able to test the concept for 3 yoga poses with each being trained on 200 images and on using external images of the same pose the accuracy seems, good I am yet to get a numbered accuracy score, and have been busy with a few unexpected things in college leading to this delay in updates, but will surely be able to finish with the project in the next 20 days.

**Comment by abhisheks008** [comment]
You can finish this is up, but that contribution will not be counted in SSOC. If you are okay with that, you can contribute here, it's completely fine. But for getting the points you need to complete this within the deadline.
@hridayK
