### ISSUE TITLE
Object Detection from a video

### ISSUE THREAD

**Issue by abhisheks008** [abhisheks008/DL-Simplified#11]
### Deep Learning Simplified Repository (Proposing new issue)
:red_circle: **Project Title** : Object Detection from a video</br>
:red_circle: **Aim** : Identify the objects from an input video with an accuracy more than 90%.</br>
:red_circle: **Dataset** : https://www.kaggle.com/code/shawon10/object-detection-from-a-traffic-video/data</br>
:red_circle: **Approach** : Try to use 3-4 algorithms to implement the models and compare all the algorithms to find out the best fitted algorithm for the model by checking the accuracy scores. Also do not forget to do a exploratory data analysis before creating any model.

**********************************************************************************
### 📍 **Follow the Guidelines to Contribute in the Project :**
* You need to create a separate folder named as the Project Title.
* Inside that folder, there will be four main components.
   * Images - To store the required images.
   * Dataset - To store the dataset or, information/source about the dataset.
   * Model - To store the machine learning model you've created using the dataset.
   * `requirements.txt` - This file will contain the required packages/libraries to run the project in other machines.
* Inside the `Model` folder, the `README.md` file must be filled up properly, with proper visualizations and conclusions.

***********************************************************************
:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include issue number along with it.
- Follow Contributing Guidelines & Code of Conduct before start Contributing.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : 
- GitHub Profile Link : 
- Email ID :
- Participant ID (if applicable):
- Approach for this Project :
- What is your participant role? (Mention the Open Source program)

*************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by janeka1122** [comment]
Hi @abhisheks008, can you assign me this issue please. I am learning Deep Learning and Neural nets. I am fluent in Python.

**Comment by abhisheks008** [comment]
This issue will be assigned to you once the program starts. Otherwise your contribution will not be counted as a participation in SSOC 2022. See you in the program @janeka1122.

**Comment by 11Veeraj** [comment]
@abhisheks008 can you assign me this issue? I'm from SSOC'22

**Comment by abhisheks008** [comment]
@11Veeraj 
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : 
- GitHub Profile Link : 
- Email ID :
- Participant ID (if applicable):
- Approach for this Project :
- What is your participant role? (Mention the Open Source program)

Mention the details first.

**Comment by 11Veeraj** [comment]
Full name : Veeraj Goudar
GitHub Profile Link : https://github.com/11Veeraj
Email ID : veeraj.goudar@mitaoe.ac.in
Approach for this Project : Using Neural Network (Yolo or RVNN)
What is your participant role? SSOC (Social Summer of Code)

**Comment by LahariBoni** [comment]
Assigned it to you @11Veeraj, Go Ahead.

**Comment by abhisheks008** [comment]
@11Veeraj updates please.

**Comment by 11Veeraj** [comment]
You can check on my repo from dl simplified I have used a CNN model Yolov5 in which object 365 and coco dataset have been used I have created a Implementation.ipynb file in which you can run the code and the detected objects are appended in a csv only thing left is to create a proper readme file 
https://github.com/11Veeraj/DL-Simplified/tree/main/Object%20Detection%20from%20a%20video

here is the link you can find Implentation.ipynb file in model folder

**Comment by 11Veeraj** [comment]
@abhisheks008 
If any corrections are required please let me know as this is my first Open source contribution so I might have committed a few mistakes.

Thank You!

**Comment by abhisheks008** [comment]
What's your contribution here? @11Veeraj

**Comment by 11Veeraj** [comment]
The Yolo model was giving output in multiple notepad text files for each frame as it was dividing the video into multiple frames of the image, so each frame has one notepad file, which I converted into a single CSV which can be found in the detectupdate.py line no 165, and after that identified the classes for each object which was detected and appended it in CSV so that all the objects which are identified can be stored in a single CSV.
Also, we can download and watch the video where objects are labelled from each frame in the given path of Implementation.ipynb

**Comment by 11Veeraj** [comment]
The original file from them for running the script is detect.py

**Comment by abhisheks008** [comment]
I got everything, I wanted to know what's your contribution? You have put the YOLOv5 repo and you are telling that it's your contribution. That's not fair. 
Everything was done by ultralytics, are you the founder of ultralytics?

I am not getting you. Please explain.
@11Veeraj

**Comment by 11Veeraj** [comment]
I have used the basic model of yolov5 if you use it. You won't get the database results properly it provides the data in a txt file, which is scattered in those text files as it is dividing the video into multiple image frames, so I have combined it into one CSV so that the object identified from each image would be in a single file which is contextualised wherein user can extract the information from it.

If you look into ultralytics repo original one, you would find they have used it only for the image purpose, and it is not ideal for video object detection you can find the changes made in comparison their repo I have attached it, and further from that CSV generated I have extracted the actual object name from the video.
![image](https://user-images.githubusercontent.com/80123055/184549738-59824bde-a91f-465c-ba10-760d8f4e9d04.png)

**Comment by 11Veeraj** [comment]
In ultralytics repo you can see they've only mentioned for image

**Comment by abhisheks008** [comment]
Look I understand what you have done, but there are certain things that needs to be followed while contributing in this repo. 
Firstly, the README.md file, there everything is redirecting towards Ultralytics org.
Secondly, you have not followed the pattern to represent the project, there must be a `.ipynb` file in which all your works should be combined together and run properly with the outputs.
Thirdly, update the README.md file by your own, follow the template and update accordingly.

The way you have represented your project, it seems that you have barely copied the whole thing. You have inspired from the YOLOv5 model and have implemented with this dataset. You need to showcase that. I hope you are getting my point, what I am trying to say. For the project pattern you can check up other projects of this project repo.

@11Veeraj

**Comment by 11Veeraj** [comment]
I will update the readme file and highlight my contribution and mention the credits for the ultralytics model. Also will try to explore more algorithms such as RCNN. Thank you for correcting me.

**Comment by abhisheks008** [comment]
Thanks for understanding. Best wishes!

**Comment by abhisheks008** [comment]
Updates please @11Veeraj

**Comment by 11Veeraj** [comment]
Working on Rcnn model for object detection. Its a topic which im learning so its taking a bit long.
Also due to clg a bit delay is caused.

**Comment by abhisheks008** [comment]
I understand what you are facing right now, but as you are enrolled in a program and you have been assigned an issue for the last 26 days, you need to keep updating ourselves, otherwise we can't get ypur problem and eventually the issue will be unassigned due to inactivity. Hope you understand.
@11Veeraj

**Comment by 11Veeraj** [comment]
Yes I understand the problems caused due to my delay which may lead to others not getting the chance. I’ll try to complete it asap.
Will let you know if I face any issue regarding this project.
If i am not able to complete within few days you may unassign the project

**Comment by parthpishte** [comment]
Full name :Parth Pishte
GitHub Profile Link :https://github.com/parthpishte
Email ID :parth.pishte21@vit.edu
Participant ID (if applicable):
Approach for this Project :the approach will be using yolo(any version) with pre trained and trained depending upon what needs to be detected , like if its an object not so common , its dataset can be created and thus can be trained on the model
What is your participant role? SSOC23

**Comment by abhisheks008** [comment]
Issue assigned to you @parthpishte

**Comment by Rithish5513U** [comment]
@abhisheks008 A help needed. I have used different email of github for doing the project contribution for Dog Detection using DL repo (Issue no 240 think so). But my mail while I register for GSSoc'24 is [rithish.satish@gmail.com](mailto:rithish.satish@gmail.com). Pls add the contribution points to this mail. Now i have changed my primary mail address in github to this ([rithish.satish@gmail.com](mailto:rithish.satish@gmail.com))

Also in this project, which object should i detect whether to classify each object or just classify object as a whole.

**Comment by abhisheks008** [comment]
> @abhisheks008 A help needed. I have used different email of github for doing the project contribution for Dog Detection using DL repo (Issue no 240 think so). But my mail while I register for GSSoc'24 is [rithish.satish@gmail.com](mailto:rithish.satish@gmail.com). Pls add the contribution points to this mail. Now i have changed my primary mail address in github to this ([rithish.satish@gmail.com](mailto:rithish.satish@gmail.com))
> 
> Also in this project, which object should i detect whether to classify each object or just classify object as a whole.

Query 1: For the email issue, I collect them for future communications with the contributors, there is no such connection with GSSoC for this. If you have given wrong email while registering in GSSoC, then you need to talk to the core team.

Query 2: You need to clasify each object.

**Comment by abhisheks008** [comment]
> @abhisheks008 can i get this issue pls? i will use yolo and its different versions..can try mobilenet too but ig yolo will be best suited

Please complete the previous issue.

**Comment by Rithish5513U** [comment]
@abhisheks008  check this dataset : https://www.kaggle.com/datasets/sshikamaru/car-object-detection
In this data the car images are available which are taken from a video by frame by frame.
Can i use this or any other??

**Comment by theiturhs** [comment]
@abhisheks008 

If this issue is not yet assigned to any one, I would like to work on this.

Find the details:

Name: Shruti Shrivastava
GitHub Profile: [GitHub](https://github.com/theiturhs)
Email Id: shrutishrivastava22ss@gmail.com
Participant Role: GSSOC'24

Approch:

I will be using YOLOv5, Detectron2 and PixelLib for object detection. All of them provide confidence scores for each detection.

Implementation will go in this manner:

- Setting Up the Models

- Preprocessing the Input Data: Handling video inputs (reading frames from a video file, performing noise removal if necessary, will check if the performance is better for gray-scale or not and so on)

- Applying the models on the video frames to detect objects.

- Extracting and using the confidence scores and bounding boxes to annotate the video frames

Thank you

**Comment by abhisheks008** [comment]
Assigned to you @theiturhs
