### ISSUE TITLE
Resume Screening Model

### ISSUE THREAD

**Issue by abhisheks008** [abhisheks008/DL-Simplified#12]
### Deep Learning Simplified Repository (Proposing new issue)
:red_circle: **Project Title** : Resume Screening Model</br>
:red_circle: **Aim** : Create a model, which will screen the resumes based on the ccriterias given.</br>
:red_circle: **Dataset** : https://www.kaggle.com/datasets/dhainjeamita/updatedresumedataset</br>
:red_circle: **Approach** : Try to use 3-4 algorithms to implement the models and compare all the algorithms to find out the best fitted algorithm for the model by checking the accuracy scores. Also do not forget to do a exploratory data analysis before creating any model.

**********************************************************************************
### 📍 **Follow the Guidelines to Contribute in the Project :**
* You need to create a separate folder named as the Project Title.
* Inside that folder, there will be four main components.
   * Images - To store the required images.
   * Dataset - To store the dataset or, information/source about the dataset.
   * Model - To store the machine learning model you've created using the dataset.
   * `requirements.txt` - This file will contain the required packages/libraries to run the project in other machines.
* Inside the `Model` folder, the `README.md` file must be filled up properly, with proper visualizations and conclusions.

***********************************************************************
:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include issue number along with it.
- Follow Contributing Guidelines & Code of Conduct before start Contributing.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : 
- GitHub Profile Link : 
- Email ID :
- Participant ID (if applicable):
- Approach for this Project :
- What is your participant role? (Mention the Open Source program)

*************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by prajwal-144** [comment]
Name: Prajwal Uday 
github link : https://github.com/prajwal-144
email : uprajwal20@gmail.com
Approach : Solve using NLP and NLU to get the final classified data.
Participant Role: SSOC

**Comment by LahariBoni** [comment]
Assigned it to you @prajwal-144. Go Ahead

**Comment by abhisheks008** [comment]
@prajwal-144 updates please.
