### ISSUE TITLE
Yoga Pose Detection

### ISSUE THREAD

**Issue by adithya-s-k** [abhisheks008/DL-Simplified#140]
### Deep Learning Simplified Repository (Proposing new issue)
:red_circle: **Project Title** : Yoga Pose Detection</br>
:red_circle: **Aim** : Yoga and Exercise Prediction model which can detect the exercise or yoga posture you are performing through your webcam in real time</br>
:red_circle: **Dataset** : will be created by the user or any video input</br>
:red_circle: **Approach**: We will be using Medipipe pose estimation model to get the coordinate of the points on your body
Work flow : 
1. **Add data function**: A function that basically lets the user put an exercise name and then stand in front of the camera and perform that action, they will have to perform the exercise, the function will take these 32 points and store them in an np array. This process can be repeated for any number of exercises.
2.  **Train Function** :  This function takes the np array of each exercise and pass it thought a model and then will be able to get the weights.
3.  **Execute Function**: Using the weights the function will open the camera feed and detect which yoga or exercise you are doing.

**********************************************************************************
### 📍 **Follow the Guidelines to Contribute in the Project :**
* You need to create a separate folder named as the Project Title.
* Inside that folder, there will be four main components.
   * Images - To store the required images.
   * Dataset - To store the dataset or, information/source about the dataset.
   * Model - To store the machine learning model you've created using the dataset.
   * `requirements.txt` - This file will contain the required packages/libraries to run the project in other machines.
* Inside the `Model` folder, the `README.md` file must be filled up properly, with proper visualizations and conclusions.

***********************************************************************
:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include issue number along with it.
- Follow Contributing Guidelines & Code of Conduct before start Contributing.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : 
- GitHub Profile Link : 
- Email ID :
- Participant ID (if applicable):
- Approach for this Project :
- What is your participant role? (Mention the Open Source program)

*************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by adithya-s-k** [comment]
✅ To be Mentioned while taking the issue :

Full name: Adithya S Kolavi
GitHub Profile Link: https://github.com/adithya-s-k
Email ID: adithyaskolavi@gmail.com
Participant ID (if applicable):
Approach for this Project: Mentioned in the issue itself
What is your participant role: SSOC participant

**Comment by abhisheks008** [comment]
@adithya-s-k I have updated the title and the aim of the project. Remember the project title is going to be **Yoga Pose Detection**. Start working on it and finish it before the deadline (October 1, 2022).

Issue assigned to you @adithya-s-k.
