### ISSUE TITLE
Penguin and Turtle Image Classification using DL

### ISSUE THREAD

**Issue by abhisheks008** [abhisheks008/DL-Simplified#207]
### Deep Learning Simplified Repository (Proposing new issue)
:red_circle: **Project Title** : Penguin and Turtle Image Classification using DL</br>
:red_circle: **Aim** : Classify the images of the Penguins and turtles using deep learning approach.</br>
:red_circle: **Dataset** : https://www.kaggle.com/datasets/abbymorgan/penguins-vs-turtles</br>
:red_circle: **Approach** : Try to use 3-4 algorithms to implement the models and compare all the algorithms to find out the best fitted algorithm for the model by checking the accuracy scores. Also do not forget to do a exploratory data analysis before creating any model.

**********************************************************************************
### 📍 **Follow the Guidelines to Contribute in the Project :**
* You need to create a separate folder named as the Project Title.
* Inside that folder, there will be four main components.
   * Images - To store the required images.
   * Dataset - To store the dataset or, information/source about the dataset.
   * Model - To store the machine learning model you've created using the dataset.
   * `requirements.txt` - This file will contain the required packages/libraries to run the project in other machines.
* Inside the `Model` folder, the `README.md` file must be filled up properly, with proper visualizations and conclusions.

***********************************************************************
:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include issue number along with it.
- Follow Contributing Guidelines & Code of Conduct before start Contributing.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : 
- GitHub Profile Link : 
- Email ID :
- Participant ID (if applicable):
- Approach for this Project :
- What is your participant role? (Mention the Open Source program)

*************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by harshsingh32** [comment]
I would like to work on this issue, please assign this issue to me under SSoC'23.

**Comment by VardaPanchal005** [comment]
I would like to work on the issue under SSOC

**Comment by abhisheks008** [comment]
Hey @harshsingh32 and @VardaPanchal005 nice to have you here. You will be assigned to this once the program starts on June 1. Till then have some patience.

**Comment by ranodeepbanerjee** [comment]
Happy to contribute in this project!

Full name : Ranodeep Banerjee
GitHub Profile Link : https://github.com/ranodeepbanerjee
Email ID : ranodeepbanerjee7@gmail.com
Participant ID (if applicable):
Approach for this Project :  i will be using CNN to implement models.
What is your participant role? SSOC Participant

Kindly assign this issue to me, thank you.

**Comment by abhisheks008** [comment]
I like your enthusiasm but as per the ethics of the open source programs, one contributor can work on one issue at a time.

@ranodeepbanerjee

**Comment by ranodeepbanerjee** [comment]
@abhisheks008 oh, alright!

**Comment by GurpreetSingh31** [comment]
I would like to work on this issue, please assign this issue to me under SSoC'23.f

**Comment by abhisheks008** [comment]
Please follow the guidelines mentioned in the issue and comment accordingly.
@GurpreetSingh31

**Comment by ayan-joshi** [comment]
Full name : Ayan Joshi
GitHub Profile Link : https://github.com/ayan-joshi
Email ID : ayanjoshi182003@gmail.com

Approach for this Project : I will use the CNN model to solve this problem and the 
dataset you provided will make it more easy I am confident that I can solve this issue please 
assign me @abhisheks008 
What is your participant role? SSOC contributor

**Comment by abhisheks008** [comment]
Try to use atleast 2-3 deep learning techniques to make a comparison between the models, so that you can find out the best fitted algorithm among the used ones with the help of the accuracy scores.

Issue assigned to you @ayan-joshi

**Comment by ayan-joshi** [comment]
@abhisheks008  As in the model the penguin and turtle images are in a same folder with different annotations file , I tried many fitting techniques but it's giving accuracy as 1 , So I can know that it's not working can I use any different data set which provides different folder for images of penguin and turtle Please help me with this

**Comment by ayan-joshi** [comment]
I tried 2-3 techniques like dropout , Batchnormalization but it's not working , can u start the issue for dogs and cats or like for some animals which have a better dataset this dataset was not working properly @abhisheks008 will be thankful to your reply

**Comment by abhisheks008** [comment]
> @abhisheks008 As in the model the penguin and turtle images are in a same folder with different annotations file , I tried many fitting techniques but it's giving accuracy as 1 , So I can know that it's not working can I use any different data set which provides different folder for images of penguin and turtle Please help me with this

You can use another dataset. Put the dataset link you are using, in the Dataset folder.

**Comment by ayan-joshi** [comment]
okay thanks I will try with another dataset @abhisheks008

**Comment by aindree-2005** [comment]
Full name : Aindree Chatterjee
GitHub Profile Link : aindree-2005
Email ID : aindree2005@gmail.com 
Approach for this Project : Comparing CNN vs ResNet50
What is your participant role? CodePeak 2023

**Comment by abhisheks008** [comment]
Issue assigned to you @aindree-2005
