### ISSUE TITLE
Improving the readme file of Phishing Website Detection

### ISSUE THREAD

**Issue by harshsingh32** [abhisheks008/DL-Simplified#209]
I would like to work on improving the readme file of Phishing Website Detection project, making it engaging for the users and make it more expressive.

**Comment by harshsingh32** [comment]
I would like to work on this issue, please assign this issue to me under SSoC'23.

**Comment by aarushiksk** [comment]
Hey! I hope you're well, I would like to work on this issue, when the program starts!  :)

**Comment by abhisheks008** [comment]
This issue is already pre-assigned to @harshsingh32 as he opened this issue first.

**Comment by abhisheks008** [comment]
Issue assigned to @harshsingh32
