### ISSUE TITLE
Twitter Sentiment Analysis NLP

### ISSUE THREAD

**Issue by abhisheks008** [abhisheks008/DL-Simplified#221]
### Deep Learning Simplified Repository (Proposing new issue)
:red_circle: **Twitter Sentiment Analysis** : </br>
:red_circle: **Aim**: Perform Sentiment Analysis with 3-4 Deep Learning Models and find the best-fit model.</br>
:red_circle: **Dataset**: https://www.kaggle.com/datasets/kazanova/sentiment140</br>
:red_circle: **Approach**: Try to use 3-4 algorithms to implement the models and compare all the algorithms to find the best-fitted model algorithm by checking the accuracy scores. Also do not forget to do an exploratory data analysis before creating any model.

**********************************************************************************
### 📍 **Follow the Guidelines to Contribute in the Project :**
* You need to create a separate folder named as the Project Title.
* Inside that folder, there will be four main components.
   * Images - To store the required images.
   * Dataset - To store the dataset or, information/source about the dataset.
   * Model - To store the machine learning model you've created using the dataset.
   * `requirements.txt` - This file will contain the required packages/libraries to run the project in other machines.
* Inside the `Model` folder, the `README.md` file must be filled up properly, with proper visualizations and conclusions.

***********************************************************************
:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include issue number along with it.
- Follow Contributing Guidelines & Code of Conduct before start Contributing.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : 
- GitHub Profile Link : 
- Email ID :
- Participant ID (if applicable):
- Approach for this Project :
- What is your participant role? (Mention the Open Source program)

*************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by ranodeepbanerjee** [comment]
Happy to contribute in this project!

Full name : Ranodeep Banerjee
GitHub Profile Link : https://github.com/ranodeepbanerjee
Email ID : ranodeepbanerjee7@gmail.com
Participant ID (if applicable):
Approach for this Project : i will be using svc , knn and naive bayes algorithms.
What is your participant role? SSOC Participant

Kindly assign this issue to me, thank you.

**Comment by abhisheks008** [comment]
I like you enthusiasm and approach for solving this issue. It would be preferable if you use deep learning models for this particular project.

@ranodeepbanerjee

**Comment by Shashank-crypto-coder** [comment]
Full name : Adimulam Shashank
GitHub Profile Link : https://github.com/Shashank-crypto-coder
Email ID : shashankadimulam135@gmail.com
Participant ID (if applicable):
Approach for this Project : We can use effective Text pre-processing techniques for cleaning of the Tweets data, and build an effective neural networks for Sentimental Analysis.
What is your participant role? SSOC Participant

**Comment by abhisheks008** [comment]
Hi @Shashank-crypto-coder nice to have you here. This issue will be assigned to you once the program starts officially ie. June 1.

Till then, star the repository and explore more in open source.

**Comment by abhisheks008** [comment]
Issue assigned to @Shashank-crypto-coder

**Comment by abhisheks008** [comment]
Issue assigned to you @aindree-2005
