### ISSUE TITLE
Ship Detection using DL

### ISSUE THREAD

**Issue by abhisheks008** [abhisheks008/DL-Simplified#229]
### Deep Learning Simplified Repository (Proposing new issue)
:red_circle: **Project Title** : Ship Detection</br>
:red_circle: **Aim** : Create a DL model which will identify the ships.</br>
:red_circle: **Dataset** : https://www.kaggle.com/datasets/arpitjain007/game-of-deep-learning-ship-datasets</br>
:red_circle: **Approach** : Try to use 3-4 algorithms to implement the models and compare all the algorithms to find out the best fitted algorithm for the model by checking the accuracy scores. Also do not forget to do a exploratory data analysis before creating any model.

**********************************************************************************
### 📍 **Follow the Guidelines to Contribute in the Project :**
* You need to create a separate folder named as the Project Title.
* Inside that folder, there will be four main components.
   * Images - To store the required images.
   * Dataset - To store the dataset or, information/source about the dataset.
   * Model - To store the machine learning model you've created using the dataset.
   * `requirements.txt` - This file will contain the required packages/libraries to run the project in other machines.
* Inside the `Model` folder, the `README.md` file must be filled up properly, with proper visualizations and conclusions.

***********************************************************************
:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include issue number along with it.
- Follow Contributing Guidelines & Code of Conduct before start Contributing.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : 
- GitHub Profile Link : 
- Email ID :
- Participant ID (if applicable):
- Approach for this Project :
- What is your participant role? (Mention the Open Source program)

*************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by hiteshhhh007** [comment]
Full Name: Hitesh K
GitHub Profile Link: https://github.com/hiteshhhh007
Email ID: [hiteshk0710@gmail.com]
Approach for this project: Using CNN and its various architectures and some usual ML algorithms to see which algorithm provides the best performance.
What is your participant role: Participant in SSOC (DL-ML Domain)

**Comment by abhisheks008** [comment]
Hi @hiteshhhh007 nice to have you here. I like the approach of solving this issue. This issue will be assigned to you once the program starts officially.

Till then, star the repository and explore more in open source.

**Comment by abhisheks008** [comment]
Issue assigned to @hiteshhhh007

**Comment by aindree-2005** [comment]
Full Name: Aindree Chatterjee
GitHub Profile Link: aindree-2005
Email ID: aindree2005@gmail.com
Approach for this project: Regular CNN model vs EffecientNet vs VCGNet performance
What is your participant role: Codepeak 

@abhisheks008 can I work on this?

**Comment by abhisheks008** [comment]
I have assigned you the issue you have created by yourself.

**Comment by aindree-2005** [comment]
> I have assigned you the issue you have created by yourself.

got it thanks!

**Comment by abhisheks008** [comment]
Issue assigned to you @aindree-2005
