### ISSUE TITLE
Movies Classification using DL

### ISSUE THREAD

**Issue by abhisheks008** [abhisheks008/DL-Simplified#239]
### Deep Learning Simplified Repository (Proposing new issue)
:red_circle: **Project Title** : Movies Classification</br>
:red_circle: **Aim** : Classify different genres of movies using deep learning approaches.</br>
:red_circle: **Dataset** : https://www.kaggle.com/datasets/akshaypawar7/millions-of-movies</br>
:red_circle: **Approach** : Try to use 3-4 algorithms to implement the models and compare all the algorithms to find out the best fitted algorithm for the model by checking the accuracy scores. Also do not forget to do a exploratory data analysis before creating any model.

**********************************************************************************
### 📍 **Follow the Guidelines to Contribute in the Project :**
* You need to create a separate folder named as the Project Title.
* Inside that folder, there will be four main components.
   * Images - To store the required images.
   * Dataset - To store the dataset or, information/source about the dataset.
   * Model - To store the machine learning model you've created using the dataset.
   * `requirements.txt` - This file will contain the required packages/libraries to run the project in other machines.
* Inside the `Model` folder, the `README.md` file must be filled up properly, with proper visualizations and conclusions.

***********************************************************************
:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include issue number along with it.
- Follow Contributing Guidelines & Code of Conduct before start Contributing.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : 
- GitHub Profile Link : 
- Email ID :
- Participant ID (if applicable):
- Approach for this Project :
- What is your participant role? (Mention the Open Source program)

*************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Myworld21** [comment]
Full name : Vandana Kumari
GitHub Profile Link : [https://github.com/Myworld21](https://github.com/Myworld21)
Email ID : [vandanaragini76@gmail.com](vandanaragini76@gmail.com)
Approach for this Project : I will extract numerical features from the textual movie descriptions using techniques like TF-IDF or word embeddings. We then select some deep learning algorithms: Convolutional Neural Networks (CNNs), Recurrent Neural Networks (RNNs), Transformers. These algorithms are trained on the preprocessed data. After training, we compare the models based on metrics such as accuracy, precision, recall, and F1-score. Considering factors like accuracy, training time, and model complexity, we determine the most suitable deep learning algorithm for movie genre classification.
What is your participant role? (Mention the Open Source program) SSOC Participant Season 2

**Comment by abhisheks008** [comment]
Hi @Myworld21  nice to have you here. I like your approach for solving this issue. This issue will be assigned to you once the program starts officially.

Till then, star the repository and explore more in open source.

**Comment by abhisheks008** [comment]
Issue assigned to @Myworld21

**Comment by Dhruv127** [comment]
kindly assign me the issue .
I'd leverage Recurrent Neural Networks (RNNs) on movie overviews alongside genre labels for text-based analysis,.

**Comment by abhisheks008** [comment]
Make sure you use atleast 2-3 models/methods for this project and find out the best fitted model based on the highest accuracy score.
Issue assigned to you @Dhruv127

**Comment by the-silent-geek** [comment]
Full name : D. Uday Kiran
GitHub Profile Link : https://github.com/the-silent-geek
Email ID : udaykir3911@gmail.com
Approach for this Project : This can be implemented by using models like cnn,rnn, and LSTM.
What is your participant role? social winter of code 23

**Comment by dipayan22** [comment]
Full name : Dipayan Majumder
GitHub Profile Link : github.com/dipayan22
Email ID : majumderd007@gmail.com
Participant ID (if applicable):
Approach for this Project : I will extract numerical feature from the textual data using TF-IDF , Word Embedding .Then i will used some deep learning algorithms likes RNN , Lstm ,transformer bert etc.
What is your participant role? (Mention the Open Source program) SWOC 24

**Comment by abhisheks008** [comment]
Assigned to @dipayan22 under SWOC S4.

**Comment by dipayan22** [comment]
hey @abhisheks008 i can't upload the Dataset file .Because it's too large . Can upload the link of the kaggle of in dataset file . please assist me.
