### ISSUE TITLE
Covid - 19 vaccine tracker 

### ISSUE THREAD

**Issue by starkver23** [abhisheks008/DL-Simplified#257]
### Deep Learning Simplified Repository (Proposing new issue)
:red_circle: **Project Title** :  Create a COVID - 19 Vaccine Tracker Model using Tableau</br>
:red_circle: **Aim** : To track all the dosage given to people over the past 3 years</br>
:red_circle: **Dataset** : https://www.kaggle.com/datasets/imdevskp/corona-virus-report</br>
:red_circle: **Approach** : Try to use 3-4 algorithms to implement the models and compare all the algorithms to find out the best fitted algorithm for the model by checking the accuracy scores. Also do not forget to do a exploratory data analysis before creating any model.

**********************************************************************************
### 📍 **Follow the Guidelines to Contribute in the Project :**
* You need to create a separate folder named as the Project Title.
* Inside that folder, there will be four main components.
   * Images - To store the required images.
   * Dataset - To store the dataset or, information/source about the dataset.
   * Model - To store the machine learning model you've created using the dataset.
   * `requirements.txt` - This file will contain the required packages/libraries to run the project in other machines.
* Inside the `Model` folder, the `README.md` file must be filled up properly, with proper visualizations and conclusions.

***********************************************************************
:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include issue number along with it.
- Follow Contributing Guidelines & Code of Conduct before start Contributing.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : 
- GitHub Profile Link : 
- Email ID :
- Participant ID (if applicable):
- Approach for this Project :
- What is your participant role? (Mention the Open Source program)

*************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by abhisheks008** [comment]
Cool I got it. Issue assigned to you.
@starkver23

**Comment by AgrawalTitiksha** [comment]
Full name : Titiksha Agrawal
GitHub Profile Link : https://github.com/AgrawalTitiksha
Email ID : agrawaltn2311@gmail.com
Approach for this Project : After applying power queries for transforming the data, using Tableau tools for visualizing, and analyzing to create an interactive dashboard useful for gaining insights.
What is your participant role? (Mention the Open Source program): @Contributor 2024

**Comment by abhisheks008** [comment]
You have been assigned to an issue earlier. Please finish that first. As per the code of conduct, it's one issue at a time for each and every contributor.

**Comment by AgrawalTitiksha** [comment]
yeah sure I'll do it first
