### ISSUE TITLE
Urdu Text Detection

### ISSUE THREAD

**Issue by abhisheks008** [abhisheks008/DL-Simplified#26]
### Deep Learning Simplified Repository (Proposing new issue)
:red_circle: **Project Title** : Urdu Text Detection</br>
:red_circle: **Aim** : Create DL model which will identify the texts written in Urdu.</br>
:red_circle: **Dataset** : https://www.kaggle.com/datasets/maryambiibii/urdu-artificial-text-text-detection</br>
:red_circle: **Approach** : Try to use 3-4 algorithms to implement the models and compare all the algorithms to find out the best fitted algorithm for the model by checking the accuracy scores. Also do not forget to do a exploratory data analysis before creating any model.

**********************************************************************************
### 📍 **Follow the Guidelines to Contribute in the Project :**
* You need to create a separate folder named as the Project Title.
* Inside that folder, there will be four main components.
   * Images - To store the required images.
   * Dataset - To store the dataset or, information/source about the dataset.
   * Model - To store the machine learning model you've created using the dataset.
   * `requirements.txt` - This file will contain the required packages/libraries to run the project in other machines.
* Inside the `Model` folder, the `README.md` file must be filled up properly, with proper visualizations and conclusions.

***********************************************************************
:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include issue number along with it.
- Follow Contributing Guidelines & Code of Conduct before start Contributing.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : 
- GitHub Profile Link : 
- Email ID :
- Participant ID (if applicable):
- Approach for this Project :
- What is your participant role? (Mention the Open Source program)

*************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by abhishak3** [comment]
I would like to take up this issue!

**Comment by abhisheks008** [comment]
Can you mention all the details please @abhishak3

**Comment by abhishak3** [comment]
yeah sure.
```
Issue No: #26  Urdu Text Detection
Full Name: Abhishek Pandey
Github Profile Link: https://github.com/abhishak3
Email ID: abhishek.pandey.3237@gmail.com
Approach: Going to experiment with various DL models + figuring out their performance measure
Participant Role : Contributor(SSOC)
```

**Comment by abhisheks008** [comment]
Issue assigned to you @abhishak3

**Comment by abhisheks008** [comment]
Updates please @abhishak3

**Comment by abhishak3** [comment]
I will update you in few hours.

**Comment by abhishak3** [comment]
@abhisheks008 I am unable to find any label in the given training data. Please have a look!

**Comment by abhisheks008** [comment]
The dataset is perfect, I have checked that. You need to create a deep learning model which extract the sentences written in Urdu from the video/images.
@abhishak3

**Comment by abhisheks008** [comment]
LOL! It's okay, it happens. @abhishak3
