### ISSUE TITLE
Store Sales Time Series Forecast

### ISSUE THREAD

**Issue by Vansh912** [abhisheks008/DL-Simplified#272]
### Deep Learning Simplified Repository (Proposing new issue)
:red_circle: **Store sales time series forecast** : </br>
:red_circle: **sales forecast time series problem** : </br>
:red_circle: **https://www.kaggle.com/competitions/store-sales-time-series-forecasting/overview** : </br>
:red_circle: **sales forecast using arima/RNN model** : Try to use 3-4 algorithms to implement the models and compare all the algorithms to find out the best fitted algorithm for the model by checking the accuracy scores. Also do not forget to do a exploratory data analysis before creating any model.

**********************************************************************************
### 📍 **Follow the Guidelines to Contribute in the Project :**
* You need to create a separate folder named as the Project Title.
* Inside that folder, there will be four main components.
   * Images - To store the required images.
   * Dataset - To store the dataset or, information/source about the dataset.
   * Model - To store the machine learning model you've created using the dataset.
   * `requirements.txt` - This file will contain the required packages/libraries to run the project in other machines.
* Inside the `Model` folder, the `README.md` file must be filled up properly, with proper visualizations and conclusions.

***********************************************************************
:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include issue number along with it.
- Follow Contributing Guidelines & Code of Conduct before start Contributing.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : 
- GitHub Profile Link : 
- Email ID :
- Participant ID (if applicable):
- Approach for this Project :
- What is your participant role? (Mention the Open Source program)

*************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by abhisheks008** [comment]
What are the deep learning methods you are going to use here for solving the issue?
@Vansh912

**Comment by Vansh912** [comment]
simple RNN model and arima time series model for comparision

**Comment by abhisheks008** [comment]
You have to implement 2-3 models, are you comfortable with that?

**Comment by Vansh912** [comment]
yeah i can search for different models that are suitable for this problem

**Comment by abhisheks008** [comment]
Cool. Start working on this issue. Assigned to you @Vansh912

**Comment by Vansh912** [comment]
ok sir

**Comment by aindree-2005** [comment]
Full name : Aindree Chatterjee
GitHub Profile Link : aindree-2005
Email ID : aindree2005@gmail.com
Participant ID (if applicable): 
Approach for this Project :Using RNNs
What is your participant role? (Mention the Open Source program) CodePeak 2023

**Comment by abhisheks008** [comment]
Issue assigned to you @aindree-2005
