### ISSUE TITLE
Image Caption Generator

### ISSUE THREAD

**Issue by mehak1309** [abhisheks008/DL-Simplified#292]
### Deep Learning Simplified Repository (Proposing new issue)
:red_circle: **Project Title**: Image Caption Generator </br>
:red_circle: **Aim**: To create a DL model that describes any image in a few words </br>
:red_circle: **Dataset**: https://www.kaggle.com/datasets/adityajn105/flickr8k  </br>
:red_circle: **Approach**: Try to use 3-4 algorithms to implement the models and compare all the algorithms to find out the best fitted algorithm for the model by checking the accuracy scores. Also do not forget to do a exploratory data analysis before creating any model.

**********************************************************************************
### 📍 **Follow the Guidelines to Contribute in the Project :**
* You need to create a separate folder named as the Project Title.
* Inside that folder, there will be four main components.
   * Images - To store the required images.
   * Dataset - To store the dataset or, information/source about the dataset.
   * Model - To store the machine learning model you've created using the dataset.
   * `requirements.txt` - This file will contain the required packages/libraries to run the project in other machines.
* Inside the `Model` folder, the `README.md` file must be filled up properly, with proper visualizations and conclusions.

***********************************************************************
:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include issue number along with it.
- Follow Contributing Guidelines & Code of Conduct before start Contributing.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Mehak Singal
- GitHub Profile Link : 
- Email ID : mehaksingal13@gmail.com
- Participant ID (if applicable):
- Approach for this Project : I will perform NLP techniques to do this project and then use a model (tensorflow).
- What is your participant role? GirlScript Summer of Code

*************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by abhisheks008** [comment]
What are the models you are planning to use here for this project? Are you planning to build an UI for this project? Please comment out in details.

@mehak1309

**Comment by mehak1309** [comment]
I am planning to use VGG16 (transfer learning) to extract features from the images and then train the dataseton a tensorflow model - CNN + LSTM. I am creating a colab file. But I am happy to create a UI for the the project.

**Comment by abhisheks008** [comment]
This issue will be assigned to you once you finish the assigned one.
@mehak1309

**Comment by Garvanand** [comment]
@abhisheks008 please assign this issue to me

**Comment by abhisheks008** [comment]
This issue is opened by @mehak1309, it will be assigned to her only.

@Garvanand you can take up other issues or create your new issues for contributing in this project repo.

**Comment by abhisheks008** [comment]
Can you share your approach for solving this issue?
@ShatilKhan

**Comment by namita0210** [comment]
I would like to work on this issue. Can you please assign it to me? I am here as a part of OSEN.
I am planning to use LSTM + CNN and explore other approaches on the go.

**Comment by abhisheks008** [comment]
Hi @namita0210 in which issue will you start working first?

It is a good approach taken by you for this issue. Try to implement 3-4 models for this project and find out the best fitted model according to the accuracy scores generated by all the models.

**Comment by namita0210** [comment]
> Hi @namita0210 in which issue will you start working first?
> 
> It is a good approach taken by you for this issue. Try to implement 3-4 models for this project and find out the best fitted model according to the accuracy scores generated by all the models.

I would like to begin with the image captioning issue.

**Comment by abhisheks008** [comment]
Issue assigned to you. You can start working on it. Go ahead.
@namita0210

**Comment by abhisheks008** [comment]
Hi @namita0210, updates on this issue?

**Comment by namita0210** [comment]
Hi, I have trained a DenseNet RNN on Flickr dataset. Will reflect in the
repository soon.

**Comment by abhisheks008** [comment]
This issue will not be considered under **CollabCode** Open Source event organized by **OSEN** as the program ended on **November 19th, 2023**.

**Comment by onkar-1432** [comment]
- Full name : Onkar viralekar
- Email ID : onkarviralekar.143@gmail.com
- Approach for this Project : I will apply TensorFlow based CNN model for feature extraction and RNN with attention over image. I will try to evaluate with different different attention mechanisms and will pick best out of them.

What is your participant role? Codepeak23 Contributor 
@abhisheks008 please assign these issue to me for Codepeak23. I will give my best to complete these project.

**Comment by abhisheks008** [comment]
Hi @onkar-1432 any update on this issue?

**Comment by onkar-1432** [comment]
Created a PR. Please check and go through the notebook. Suggest me any changes if required. Thanks.
