### ISSUE TITLE
Disaster Tweets Sentiment Analysis

### ISSUE THREAD

**Issue by mehak1309** [abhisheks008/DL-Simplified#293]
### Deep Learning Simplified Repository (Proposing new issue)
:red_circle: **Project Title**: Twitter Sentiment Analysis - Disaster Tweets</br>
:red_circle: **Aim**: To create a DL model that classifies whether a given tweet is a disaster or not. </br>
:red_circle: **Dataset**: https://www.kaggle.com/competitions/nlp-getting-started/data </br>
:red_circle: **Approach**: Try to use 3-4 algorithms to implement the models and compare all the algorithms to find out the best fitted algorithm for the model by checking the accuracy scores. Also do not forget to do a exploratory data analysis before creating any model.

**********************************************************************************
### 📍 **Follow the Guidelines to Contribute in the Project :**
* You need to create a separate folder named as the Project Title.
* Inside that folder, there will be four main components.
   * Images - To store the required images.
   * Dataset - To store the dataset or, information/source about the dataset.
   * Model - To store the machine learning model you've created using the dataset.
   * `requirements.txt` - This file will contain the required packages/libraries to run the project in other machines.
* Inside the `Model` folder, the `README.md` file must be filled up properly, with proper visualizations and conclusions.

***********************************************************************
:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include issue number along with it.
- Follow Contributing Guidelines & Code of Conduct before start Contributing.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Mehak Singal
- GitHub Profile Link : 
- Email ID : mehaksingal13@gmail.com
- Participant ID (if applicable):
- Approach for this Project : I will perform NLP techniques to do this project and then use a model (tensorflow).
- What is your participant role? GirlScript Summer of Code

*************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by abhisheks008** [comment]
Are you going to use NLP models/techniques for this project?
@mehak1309

**Comment by mehak1309** [comment]
yes like tokenization etc. Then I will use a model to classify tweets.

**Comment by abhisheks008** [comment]
Issue assigned to you @mehak1309

**Comment by aindree-2005** [comment]
@abhisheks008 can I work on this issue?

**Comment by abhisheks008** [comment]
Can you please share your approach for solving this issue as per the given template? Also as per the code of conduct, one contributor can work on one issue at a time only.
@aindree-2005

**Comment by YashSachan2** [comment]
@abhisheks008 Can I tak on this issue ?I have solved the twitter sentiments using LSTM,Logistic Regression and Naive Bayes

**Comment by abhisheks008** [comment]
Hi @YashSachan2 can you please share your approach for solving this issue in a detailed way? What are Deep Learning models you are planning to implement?

**Comment by aindree-2005** [comment]
Full name : Aindree Chatterjee
GitHub Profile Link :aindree-2005
Email ID : [aindree2005@gmail.com](mailto:aindree2005@gmail.com)
Participant ID (if applicable):
Approach for this Project : Tfidf with randomforest vs LSTM
What is your participant role? CodePeak

@abhisheks008 can I work on this?

**Comment by abhisheks008** [comment]
Try to use various deep learning models for this project along with the models/methods you have proposed. Explore and try out different models if you can. Anyways issue assigned to you @aindree-2005. You can start working on it.
