### ISSUE TITLE
Spam Vs Ham Mail Classification [With Streamlit GUI]

### ISSUE THREAD

**Issue by pooranjoyb** [abhisheks008/DL-Simplified#329]
### Deep Learning Simplified Repository (Proposing new issue)
:red_circle: **Project Title** : Spam Vs Ham Mail Classification</br>
:red_circle: **Aim** : ML project with a Streamlit GUI that will predict whether the Mail received from some source is a Spam Mail or not</br>
:red_circle: **Dataset** : https://www.kaggle.com/datasets/omokennanna/simple-spam-classification</br>
:red_circle: **Approach** : Try to use 3-4 algorithms to implement the models and compare all the algorithms to find out the best fitted algorithm for the model by checking the accuracy scores. Also do not forget to do a exploratory data analysis before creating any model.

**********************************************************************************
### 📍 **Follow the Guidelines to Contribute in the Project :**
* You need to create a separate folder named as the Project Title.
* Inside that folder, there will be four main components.
   * Images - To store the required images.
   * Dataset - To store the dataset or, information/source about the dataset.
   * Model - To store the machine learning model you've created using the dataset.
   * `requirements.txt` - This file will contain the required packages/libraries to run the project in other machines.
* Inside the `Model` folder, the `README.md` file must be filled up properly, with proper visualizations and conclusions.

***********************************************************************
:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include issue number along with it.
- Follow Contributing Guidelines & Code of Conduct before start Contributing.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Pooranjoy Bhattacharya
- GitHub Profile Link : pooranjoyb
- Email ID :pooranjoyb2016@gmail.com
- Participant ID (if applicable): 
- Approach for this Project : Apply different ML models to build a best model to predict the mails.
- What is your participant role? (Mention the Open Source program) Social Summer of Code 2023

*************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by abhisheks008** [comment]
Issue assigned to you @pooranjoyb

**Comment by abhisheks008** [comment]
Hi @smty2018, can you please share your approach for solving this issue along with the required details mentioned in the issue template.

**Comment by Rani1303** [comment]
@abhisheks008 is this issue open for SWOC'24?

**Comment by dipayan22** [comment]
Full name : Dipayan Majumder
GitHub Profile Link : https://github.com/dipayan22/
Email ID : majumderd007@gmail.com
Participant ID (if applicable):
Approach for this Project : Apply different ML and DL models to build a best model to predict the mails.
What is your participant role? (Mention the Open Source program) Social Summer of Code 2024

**Comment by dipayan22** [comment]
Query : Please provide me the link of the dataset

**Comment by abhisheks008** [comment]
Updated dataset link. This issue is part of Social Winter of Code.

**Comment by dipayan22** [comment]
sorry for the typing mistake .I participate in SWOC 2024. 
What is your participant role? (Mention the Open Source program) Social Winter of Code 2024.
Please assign me this project .

**Comment by abhisheks008** [comment]
Complete the previous issue first.

**Comment by adityachoudhury29** [comment]
How do I get assigned to this issue?

**Comment by dipayan22** [comment]
Full name : Dipayan Majumder
GitHub Profile Link : https://github.com/dipayan22/
Email ID : [majumderd007@gmail.com](mailto:majumderd007@gmail.com)
Participant ID (if applicable):
Approach for this Project : Apply different ML and DL models to build a best model to predict the mails.
What is your participant role? (Mention the Open Source program) Social Winter of Code 2024

**Comment by abhisheks008** [comment]
What are the deep learning methods are you focusing on?

**Comment by dipayan22** [comment]
i will use RNN ,LSTM ,Pre trained model like Transformer-bert etc . I also have to do some preprocessing . can you please assign me this project under SWOC 24.

**Comment by dipayan22** [comment]
Can i used some ML algorithm if it's give me good accuracy.

**Comment by abhisheks008** [comment]
This project repository mainly focuses on the DL models, so try to implement DL models more. If you find ML models are getting better results then only you can put the models for showcase along with the implemented DL models.

Issue assigned to you @dipayan22 under SWOC S4.
