### ISSUE TITLE
Car Price Prediction using DL

### ISSUE THREAD

**Issue by aaviiothic** [abhisheks008/DL-Simplified#339]
### Deep Learning Simplified Repository (Proposing new issue)

:red_circle: **Project Title** : Car Price Prediction

:red_circle: **Aim** : Creating a ML project to predict the price of cars which depends on various factors such as brand, mileage, etc.

:red_circle: **Dataset** : https://www.kaggle.com/datasets/hellbuoy/car-price-prediction

:red_circle: **Approach** : Try to use 3-4 algorithms to implement the models and compare all the algorithms to find out the best fitted algorithm for the model by checking the accuracy scores. Also do not forget to do a exploratory data analysis before creating any model.

**********************************************************************************
### 📍 **Follow the Guidelines to Contribute in the Project :**
* You need to create a separate folder named as the Project Title.
* Inside that folder, there will be four main components.
   * Images - To store the required images.
   * Dataset - To store the dataset or, information/source about the dataset.
   * Model - To store the machine learning model you've created using the dataset.
   * `requirements.txt` - This file will contain the required packages/libraries to run the project in other machines.
* Inside the `Model` folder, the `README.md` file must be filled up properly, with proper visualizations and conclusions.

***********************************************************************
:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include issue number along with it.
- Follow Contributing Guidelines & Code of Conduct before start Contributing.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Adityaa Sahu
- GitHub Profile Link : https://github.com/aaviiothic
- Email ID : adityaa0703@gmail.com
- Participant ID (if applicable):
- Approach for this Project : using RFE and VIF to predict price of cars.
- What is your participant role? (Mention the Open Source program)

*************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by aaviiothic** [comment]
Please assign me the issue, I'm working on it !

**Comment by abhisheks008** [comment]
Can you please follow the issue template and share all the information regarding the project. From where you are fetching the dataset, what are the deep learning techniques you are going to use here, what sort of data visualizations should be done, these things should be mentioned while creating an issue.

@aaviiothic

**Comment by aaviiothic** [comment]
> Can you please follow the issue template and share all the information regarding the project. From where you are fetching the dataset, what are the deep learning techniques you are going to use here, what sort of data visualizations should be done, these things should be mentioned while creating an issue.
> 
> @aaviiothic

Updated! please check. @abhisheks008

**Comment by abhisheks008** [comment]
This issue will be assigned to you @aaviiothic once you complete the assigned one. As per the code of conduct, one issue at a time for each contributor.

**Comment by Nabanita29** [comment]
can I work on this?

**Comment by abhisheks008** [comment]
> can I work on this?

Sorry @Nabanita29 as this issue is opened by a contributor, hence he/she will get the priority for working in this issue. You can create issues by your own.

**Comment by mayank2130** [comment]
Hey! I'd like to work on this project.

Dataset : https://www.kaggle.com/datasets/mayankpatel14/second-hand-used-cars-data-set-linear-regression

Approach : Using KNN, Linear Regression and Random Forest Regressor model to predict the car prices.

Full name : Mayank Thakur
GitHub Profile Link : https://github.com/mayank2130
Email ID : mayankthakur1712@gmail.com

Approach for this Project : Using KNN and xgb.XGBRegressor, lgb.LGBMRegressor to predict price of cars.
@abhisheks008

**Comment by abhisheks008** [comment]
This project repository consists of projects based on Deep Learning techniques and methods. Try to solve this issue using DL methods not by simple ML methods.
@mayank2130

**Comment by AtriChatterjee1** [comment]
Hey! I'd like to work on this project.

Dataset : https://www.kaggle.com/datasets/mayankpatel14/second-hand-used-cars-data-set-linear-regression

Approach : [Using ANN with 5-3-1 architecture ](https://www.researchgate.net/figure/Detailed-architecture-of-Artificial-Neural-Network-ANN-for-stock-price-prediction_fig1_340698512)

Full name : Atri Chattopadhyay
GitHub Profile Link : https://github.com/AtriChatterjee1
Email ID : [print.atri@gmail.com](mailto:print.atri@gmail.com)

@abhisheks008

**Comment by abhisheks008** [comment]
Hi @AtriChatterjee1, I have a suggestion. Can you use both the datasets, which is mentioned in the issue template and the one you used while posting the approach in the comment? That'll be a good combined and strong dataset to work on. I'd like to hear from you on this.

**Comment by YashSachan2** [comment]
Hi @abhisheks008 Can I take on this issue?I have worked on a similar case to detect house prices before.

**Comment by abhisheks008** [comment]
Hi @YashSachan2 can you please share your approach for solving this issue? Please try to use DL models as this repository contains projects which are mainly based on DL.

**Comment by n1haldev** [comment]
Hey @abhisheks008  I would like to work on this.

Dataset: https://www.kaggle.com/datasets/hellbuoy/car-price-prediction

Approach: Use GRU, LSTM and a regular ANN. 

Full Name: Nihal T M
Github Profile Link: https://github.com/n1haldev
Email ID: nihaltm2002@gmail.com

**Comment by CoderOMaster** [comment]
Hey @abhisheks008 I would like to work on this.

Dataset: https://www.kaggle.com/datasets/hellbuoy/car-price-prediction

Approach: Use XGBoost, ANN,LSTM or rnn based approaches

Full Name: Keshav Arora 
Github Profile Link: https://github.com/CoderOMaster
Email ID: keshavarorasci@gmail.com

**Comment by abhisheks008** [comment]
Hi @n1haldev and @CoderOMaster are you guys part of SWOC event?

**Comment by Soumiksb06** [comment]
Full name : Soumik Banerjee
GitHub Profile Link : https://github.com/Soumiksb06
Email ID: soumikbanerjee230@gmail.com

Hi, Abhishek,
I'm completely new to Open Source but have lots of experience in building DL and ML models for prediction. I feel that this project would be a suitable start for my Open Source journey. Please assign this one to me.
Thank You!

**Comment by abhisheks008** [comment]
Let the program start officially. Issues will be assigned after that. Till then go through the repository as well as the `README` file.

**Comment by Soumiksb06** [comment]
> Let the program start officially. Issues will be assigned after that. Till then go through the repository as well as the `README` file.

Ok. So how will we know about the assigned projects?

**Comment by abhisheks008** [comment]
I guess we will have a communication channel in Discord, through that we can communicate.

**Comment by Soumiksb06** [comment]
> I guess we will have a communication channel in Discord, through that we can communicate.

Okay

**Comment by abhisheks008** [comment]
Hi @Soumiksb06 would you like to work on this issue based on the approach you have shared earlier?

**Comment by Soumiksb06** [comment]
> Hi @Soumiksb06 would you like to work on this issue based on the approach you have shared earlier?

Yes sure!

**Comment by abhisheks008** [comment]
What will be your approach for solving this issue, what are the models you want to implement?
@Soumiksb06

**Comment by Soumiksb06** [comment]
> What will be your approach for solving this issue, what are the models you want to implement?
> @Soumiksb06 

I'll use LSTM, RNN, MLP and try others and find out the best fitted algorithm based on accuracy scores.

**Comment by abhisheks008** [comment]
Cool. Issue assigned to you @Soumiksb06. I have also updated the issue name, try to focus on DL models/methods instead of basic ML models.

**Comment by Soumiksb06** [comment]
> Cool. Issue assigned to you @Soumiksb06. I have also updated the issue name, try to focus on DL models/methods instead of basic ML models.

Yeah sure I mentioned DL models only. How can I contact you? on Linkedin or on Discord?

**Comment by abhisheks008** [comment]
> > Cool. Issue assigned to you @Soumiksb06. I have also updated the issue name, try to focus on DL models/methods instead of basic ML models.
> 
> Yeah sure I mentioned DL models only. How can I contact you? on Linkedin or on Discord?

Anywhere you want
