### ISSUE TITLE
Email Spam Detection using ML

### ISSUE THREAD

**Issue by aaviiothic** [abhisheks008/DL-Simplified#340]
Deep Learning Simplified Repository (Proposing new issue)

🔴 Project Title : Email Spam Detection

🔴 Aim : Using ML and Python to create a project which can detect spam/junk emails.

🔴 Dataset : https://www.kaggle.com/datasets/uciml/sms-spam-collection-dataset

🔴 Approach** : Try to use 3-4 algorithms to implement the models and compare all the algorithms to find out the best fitted algorithm for the model by checking the accuracy scores. Also do not forget to do a exploratory data analysis before creating any model.

**********************************************************************************
### 📍 **Follow the Guidelines to Contribute in the Project :**
* You need to create a separate folder named as the Project Title.
* Inside that folder, there will be four main components.
   * Images - To store the required images.
   * Dataset - To store the dataset or, information/source about the dataset.
   * Model - To store the machine learning model you've created using the dataset.
   * `requirements.txt` - This file will contain the required packages/libraries to run the project in other machines.
* Inside the `Model` folder, the `README.md` file must be filled up properly, with proper visualizations and conclusions.

***********************************************************************
:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include issue number along with it.
- Follow Contributing Guidelines & Code of Conduct before start Contributing.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Adityaa Sahu
- GitHub Profile Link : https://github.com/aaviiothic
- Email ID : adityaa0703@gmail.com
- Participant ID (if applicable):
- Approach for this Project : Using models like LSTM , BERT to detect spam emails.
- What is your participant role? (Mention the Open Source program)

*************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by aaviiothic** [comment]
Please assign me the issue , I'm working on it!
@abhisheks008

**Comment by abhisheks008** [comment]
Can you please follow the issue template and share all the information regarding the project. From where you are fetching the dataset, what are the deep learning techniques you are going to use here, what sort of data visualizations should be done, these things should be mentioned while creating an issue.

@aaviiothic

**Comment by aaviiothic** [comment]
> Can you please follow the issue template and share all the information regarding the project. From where you are fetching the dataset, what are the deep learning techniques you are going to use here, what sort of data visualizations should be done, these things should be mentioned while creating an issue.
> 
> @aaviiothic

updated! please check @abhisheks008

**Comment by abhisheks008** [comment]
What are deep learning models you are planning to execute for this project?
@aaviiothic

**Comment by aaviiothic** [comment]
> What are deep learning models you are planning to execute for this project? @aaviiothic

LSTM , BERT

**Comment by abhisheks008** [comment]
Try to use at least 3 deep learning models for this project and lastly compare them depending on the accuracy and loss scores to find out the best fitted model for this project.

@aaviiothic 

Issue assigned to you. Start working on it.

**Comment by mayank2130** [comment]
Email Spam Detection 

Aim : Use Deep Learning and Python to create a project which can detect spam emails.

Dataset : https://www.kaggle.com/datasets/uciml/sms-spam-collection-dataset

Approach : Using Logistic Regression, LSTM and fine tuning BERT model to find highest accuracy score and lowest loss score. Will be using confusion matrix for visualization.

Who am I ?

Full name : Mayank Thakur
GitHub Profile Link : https://github.com/mayank2130
Email ID : mayankthakur1712@gmail.com
Twitter: https://twitter.com/mayank01322310

**Comment by mayank2130** [comment]
Email Spam Detection

Aim : Use Deep Learning and Python to create a project which can detect spam emails.

Dataset : https://www.kaggle.com/datasets/uciml/sms-spam-collection-dataset

Approach : Using Logistic Regression, LSTM and fine tuning BERT model to find highest accuracy score and lowest loss score. Will be using confusion matrix for visualization.

Who am I ?

Full name : Mayank Thakur
GitHub Profile Link : https://github.com/mayank2130
Email ID : [mayankthakur1712@gmail.com](mailto:mayankthakur1712@gmail.com)
Twitter: https://twitter.com/mayank01322310

@abhisheks008

**Comment by abhisheks008** [comment]
Do you want to contribute and solve this issue as a contributor?
@mayank2130

**Comment by mayank2130** [comment]
Yes, I do indeed.
@abhisheks008

**Comment by mayank2130** [comment]
Hey, just following up. You want to assign this issue.

@abhisheks008

**Comment by abhisheks008** [comment]
Issue assigned to you. You can start working on it.
@mayank2130

**Comment by aindree-2005** [comment]
Full name : Aindree Chatterjee
GitHub Profile Link : https://github.com/aindree-2005
Email ID : [aindree2005@gmail.com](mailto:aindree2005@gmail.com)
Event:CodePeak

Project Title : SMS  Spam Detection
Aim : Using ML to detect spam email
Dataset : https://www.kaggle.com/datasets/uciml/sms-spam-collection-dataset
Approach : Simple Approach with LSTM
@abhisheks008 can I work on this issue?

**Comment by abhisheks008** [comment]
Hi @aindree-2005, it is a good approach for solving this issue. Simple approach with LSTM is a good one, you can also add BERT in this to make this project more unique than the others. I'd like to hear from you on this.

**Comment by aindree-2005** [comment]
> Hi @aindree-2005, it is a good approach for solving this issue. Simple approach with LSTM is a good one, you can also add BERT in this to make this project more unique than the others. I'd like to hear from you on this.
Got it! I'll look into the approach using BERT as well.

**Comment by abhisheks008** [comment]
@aindree-2005 good enough for me. Issue assigned to you. You can start working on it.
