### ISSUE TITLE
Lung Cancer Detection using Text Data

### ISSUE THREAD

**Issue by aindree-2005** [abhisheks008/DL-Simplified#400]
### Deep Learning Simplified Repository (Proposing new issue)
:red_circle: **Project Title** : Lung Cancer Detection </br>
:red_circle: **Aim** : To detect prime features for causing lung cancer</br>
:red_circle: **Dataset** : https://www.kaggle.com/datasets/mysarahmadbhat/lung-cancer/code </br>
:red_circle: **Approach** : Use Sequential Model and comparing it to Catboost

**********************************************************************************
### 📍 **Follow the Guidelines to Contribute in the Project :**
* You need to create a separate folder named as the Project Title.
* Inside that folder, there will be four main components.
   * Images - To store the required images.
   * Dataset - To store the dataset or, information/source about the dataset.
   * Model - To store the machine learning model you've created using the dataset.
   * `requirements.txt` - This file will contain the required packages/libraries to run the project in other machines.
* Inside the `Model` folder, the `README.md` file must be filled up properly, with proper visualizations and conclusions.

***********************************************************************
:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include issue number along with it.
- Follow Contributing Guidelines & Code of Conduct before start Contributing.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name :  Aindree Chatterjee
- GitHub Profile Link : aindree-2005
- Email ID : aindree2005@gmail.com
- Participant ID (if applicable):
- Approach for this Project :
- What is your participant role? (Mention the Open Source program)
Codepeak
*************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by aindree-2005** [comment]
@abhisheks008 Can I work on this?

**Comment by abhisheks008** [comment]
Colon and Lung Cancer Prediction model is already present there in this repository. Have a look at that. If you find something more unique than the existing one, please do let me inform here.

**Comment by aindree-2005** [comment]
> Colon and Lung Cancer Prediction model is already present there in this repository. Have a look at that. If you find something more unique than the existing one, please do let me inform here.

@abhisheks008 I looked at the models in that folder. The dataset is image data. I was planning on detection from text-data, based on yes/no responses to questions related to smoking, etc

**Comment by abhisheks008** [comment]
I have updated the issue name and also follow the same name as the project folder. Issue assigned to you @aindree-2005
