### ISSUE TITLE
AI Generated Fruits and Real Fruits Classification using Image Processing

### ISSUE THREAD

**Issue by abhisheks008** [abhisheks008/DL-Simplified#416]
### Deep Learning Simplified Repository (Proposing new issue)
:red_circle: **Project Title** : AI Generated Fruits and Real Fruits Classification using Image Processing</br>
:red_circle: **Aim** : The aim of this project to identify and predict the real fruits and AI generated fruits using Image Processing methods.</br>
:red_circle: **Dataset** : https://www.kaggle.com/datasets/osmankagankurnaz/dataset-of-ai-generated-fruits-and-real-fruits</br>
:red_circle: **Approach** : Try to use 3-4 algorithms to implement the models and compare all the algorithms to find out the best fitted algorithm for the model by checking the accuracy scores. Also do not forget to do a exploratory data analysis before creating any model.

**********************************************************************************
### 📍 **Follow the Guidelines to Contribute in the Project :**
* You need to create a separate folder named as the Project Title.
* Inside that folder, there will be four main components.
   * Images - To store the required images.
   * Dataset - To store the dataset or, information/source about the dataset.
   * Model - To store the machine learning model you've created using the dataset.
   * `requirements.txt` - This file will contain the required packages/libraries to run the project in other machines.
* Inside the `Model` folder, the `README.md` file must be filled up properly, with proper visualizations and conclusions.

***********************************************************************
:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include issue number along with it.
- Follow Contributing Guidelines & Code of Conduct before start Contributing.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : 
- GitHub Profile Link : 
- Email ID :
- Participant ID (if applicable):
- Approach for this Project :
- What is your participant role? (Mention the Open Source program)

*************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by KunalSharmaGit** [comment]
Name: Kunal Sharma
GitHub Profile Link: https://github.com/KunalSharmaGit
Email ID: kunalsharma8630@gmail.com
Approach for this Project: This can be implemented using various algorithms especially CNN in which we use Sigmoid activation function to classify the AI Generated and Real Fruits.
What is your participant role? Social Winter of Code 2023

**Comment by abhisheks008** [comment]
Wait for the program to officially start. Issues will be assigned to you after the orientation.
@KunalSharmaGit

**Comment by abhisheks008** [comment]
Hi @KunalSharmaGit welcome to SWOC 2024. What are the models you are planning to implement for this project?

**Comment by KunalSharmaGit** [comment]
Hey @abhisheks008, I think algorithms like Support Vector Machines(SVM), k-NN and CNN can be effective in implementing this project.

**Comment by abhisheks008** [comment]
Can you suggest some of the Deep Learning methods for this project?

**Comment by KunalSharmaGit** [comment]
CNN, VGG and ResNet.

**Comment by AgrawalTitiksha** [comment]
Full name : Titiksha Agrawal
GitHub Profile Link : https://github.com/AgrawalTitiksha
Email ID : agrawaltn2311@gmail.com
Approach for this Project : After data preprocessing and visualization, using PCA algorithm for normalizing and standardizing the images, then to use LDA , SVM (all 3 kernel) , and CNN (VGG16) for analyzing the images, it can also be used to predict for new input dataset (whether ai generated or not)
What is your participant role? (Mention the Open Source program) : @contributor 2024

need to mention: have worked on a similar project but topic, "Early stage Alzheimer's disease detection, classification and prediction" using the same model's above (excluding CNN).

**Comment by abhisheks008** [comment]
Based on the given approaches I'll go with @AgrawalTitiksha. Try to use ResNet along with VGG16. Issue assigned to you. You can start working on it.

**Comment by AgrawalTitiksha** [comment]
@abhisheks008 thankyou for assigning this, I'll hit the given requirements. Just to ask you what is the deadline.

**Comment by abhisheks008** [comment]
You can take your time according to your availability. Just finish the issue before the program ends.

**Comment by AgrawalTitiksha** [comment]
sure sure
