### ISSUE TITLE
Brand Sentiment Analysis using NLP

### ISSUE THREAD

**Issue by abhisheks008** [abhisheks008/DL-Simplified#445]
### Deep Learning Simplified Repository (Proposing new issue)
:red_circle: **Project Title** : Brand Sentiment Analysis using NLP</br>
:red_circle: **Aim** : The aim of this project is to analyze the sentiment of the brands based on the dataset.</br>
:red_circle: **Dataset** : https://www.kaggle.com/datasets/tusharpaul2001/brand-sentiment-analysis-dataset</br>
:red_circle: **Approach** : Try to use 3-4 algorithms to implement the models and compare all the algorithms to find out the best fitted algorithm for the model by checking the accuracy scores. Also do not forget to do a exploratory data analysis before creating any model.

**********************************************************************************
### 📍 **Follow the Guidelines to Contribute in the Project :**
* You need to create a separate folder named as the Project Title.
* Inside that folder, there will be four main components.
   * Images - To store the required images.
   * Dataset - To store the dataset or, information/source about the dataset.
   * Model - To store the machine learning model you've created using the dataset.
   * `requirements.txt` - This file will contain the required packages/libraries to run the project in other machines.
* Inside the `Model` folder, the `README.md` file must be filled up properly, with proper visualizations and conclusions.

***********************************************************************
:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include issue number along with it.
- Follow Contributing Guidelines & Code of Conduct before start Contributing.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : 
- GitHub Profile Link : 
- Email ID :
- Participant ID (if applicable):
- Approach for this Project :
- What is your participant role? (Mention the Open Source program)

*************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by dipayan22** [comment]
Full name : Dipayan Majumder
GitHub Profile Link : https://github.com/dipayan22/
Email ID : majumderd0072gmail.com
Participant ID (if applicable):
Approach for this Project : One approach to sentiment analysis using deep learning is to use recurrent neural networks (RNNs), which are capable of modeling sequential dependencies in text data. [RNNs can be further improved by incorporating long short-term memory (LSTM) or gated recurrent unit (GRU) cells . Another approach is to use convolutional neural networks (CNNs), which are effective in identifying local patterns in text data
What is your participant role? (Mention the Open Source program) SWOC 24

**Comment by dipayan22** [comment]
I wanted to apologize for providing the wrong email address while issuing the project. I understand that this may have caused inconvenience and confusion, and I take full responsibility for my mistake. I am taking steps to ensure that this does not happen again in the future. In the meantime, please let me know if there is anything else I can do to rectify this situation. Thank you for your understanding and patience.

Email - majumderd007@gmail.com

**Comment by Soumiksb06** [comment]
Full name : Soumik Banerjee
GitHub Profile Link : https://github.com/Soumiksb06
Email ID: soumikbanerjee230@gmail.com
Approach: I will use a deep learning architecture such as a recurrent neural network (RNN), long short-term memory networks (LSTM), or a transformer model like BERT. Then compare their accuracies and choose the best one.
What is your participant role? : SWOC '24 Contributor

I love to work with sentiment analysis and it's my area of interest! Please approve my request!

**Comment by abhisheks008** [comment]
Issue assigned to you @dipayan22
