### ISSUE TITLE
James Webb Telescope Images Analysis

### ISSUE THREAD

**Issue by abhisheks008** [abhisheks008/DL-Simplified#45]
### Deep Learning Simplified Repository (Proposing new issue)
:red_circle: **Project Title** : James Webb Telescope Images Analysis</br>
:red_circle: **Aim** : Analyze the recent images from the James Webb Telescope.</br>
:red_circle: **Dataset** : https://www.kaggle.com/datasets/goelyash/james-webb-telescope-images-original-size/code</br>
:red_circle: **Approach** : Try to use 3-4 algorithms to implement the models and compare all the algorithms to find out the best fitted algorithm for the model by checking the accuracy scores. Also do not forget to do a exploratory data analysis before creating any model.

**********************************************************************************
### 📍 **Follow the Guidelines to Contribute in the Project :**
* You need to create a separate folder named as the Project Title.
* Inside that folder, there will be four main components.
   * Images - To store the required images.
   * Dataset - To store the dataset or, information/source about the dataset.
   * Model - To store the machine learning model you've created using the dataset.
   * `requirements.txt` - This file will contain the required packages/libraries to run the project in other machines.
* Inside the `Model` folder, the `README.md` file must be filled up properly, with proper visualizations and conclusions.

***********************************************************************
:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include issue number along with it.
- Follow Contributing Guidelines & Code of Conduct before start Contributing.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : 
- GitHub Profile Link : 
- Email ID :
- Participant ID (if applicable):
- Approach for this Project :
- What is your participant role? (Mention the Open Source program)

*************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Rohith2202** [comment]
Hi sir. I want to work on this issue
Discord Username:Rohith#2286
Ssoc participant

**Comment by Rohith2202** [comment]
Madineni Rohith
https://github.com/Rohith2202
20bcs081@iiitdwd.ac.in
Will try various ML models and pick the right and most accurate one for James Webb Space Telescope Image analysis
SSOC participant

**Comment by abhisheks008** [comment]
We'll start the journey after completing those formalities. Till then, stay tuned with Deep Learning Simplified.

Thanks and regards.

**Comment by LahariBoni** [comment]
Assigned it to you @Rohith2202. Happy Contribution!

**Comment by abhisheks008** [comment]
@Rohith2202 updates please.

**Comment by Rohith2202** [comment]
Almost done sir. Will submit in 2 days time

**Comment by abhisheks008** [comment]
Cool, thanks for the update @Rohith2202
