### ISSUE TITLE
scroll bar button 

### ISSUE THREAD

**Issue by student-aditipaliwal** [abhisheks008/DL-Simplified#452]
to go to the home page we have to scroll whole site 
can add sc
![Uploading Screenshot 2024-01-19 020315.png…]()
roll bar

**Comment by student-aditipaliwal** [comment]
please assign this issue to me

**Comment by abhisheks008** [comment]
Which website you are talking about? The Google site?

**Comment by Harikaran1729** [comment]
Hello. I would like to work on this issue... I am participating in DWoC and this contribution would help me with that and help me learn and explore more in Web dev.. Please assign the task to me..

**Comment by abhisheks008** [comment]
Hi @Harikaran1729 DWOC issues are marked separately using the DWOC labels.

**Comment by abhisheks008** [comment]
Closing this issue.
