### ISSUE TITLE
README Enhancement of DL-Simplified Project Repository

### ISSUE THREAD

**Issue by abhisheks008** [abhisheks008/DL-Simplified#459]
### Deep Learning Simplified Repository (Proposing new issue)
:red_circle: **Project Title** : Documentation and Typing Mistake Correction</br>
:red_circle: **Aim** : The aim is to correct the typing mistake in this repo.</br>
:red_circle: **README to be enhanced** : https://github.com/abhisheks008/DL-Simplified/blob/main/README.md</br>
:red_circle: **Approach** : N/A
**********************************************************************************
### 📍 **Follow the Guidelines to Contribute in the Project :**
* You need to create a separate folder named as the Project Title.
* Inside that folder, there will be four main components.
   * Images - To store the required images.
   * Dataset - To store the dataset or, information/source about the dataset.
   * Model - To store the machine learning model you've created using the dataset.
   * `requirements.txt` - This file will contain the required packages/libraries to run the project in other machines.
* Inside the `Model` folder, the `README.md` file must be filled up properly, with proper visualizations and conclusions.

***********************************************************************
:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include issue number along with it.
- Follow Contributing Guidelines & Code of Conduct before start Contributing.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : 
- GitHub Profile Link : 
- Email ID :
- Participant ID (if applicable):
- Approach for this Project :
- What is your participant role? (Mention the Open Source program)

*************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by UncleWeeds** [comment]
Hello @abhisheks008 ,

I am interested in contributing to the Project and would like to take on Issue #459 - Documentation and Typing Mistake Correction. Below are my details and proposed approach for this issue:

Full Name: D. Abhiram Sai
GitHub Profile Link: https://github.com/UncleWeeds
Email ID: danduabhiramsai@gmail.com
Participant ID: 
Approach for this Project:
I plan to approach this project by:
Thoroughly reviewing the existing documentation and code comments to identify and correct typing mistakes.
Enhancing the clarity and comprehensiveness of the documentation, ensuring that it is user-friendly and informative.
Improving the README.md file in the Model/ folder by including detailed visualizations and clear, concise conclusions.
Ensuring that all changes are well-documented and that the requirements.txt file is updated to reflect any new dependencies.
Participant Role:
I am participating as a contributor, in the DWOC.

**Comment by abhisheks008** [comment]
Wait for the program to start officially, issues will be assigned thereafter.

**Comment by UncleWeeds** [comment]
@abhisheks008 Cool, assign it to me after the official start

**Comment by abhisheks008** [comment]
Assigned under DWOC @UncleWeeds

**Comment by TanyaSingh103** [comment]
Hello @abhisheks008 

I'd like to contribute to this, please add a gssoc tag and assign this issue to me, here are the details:

Full Name: Tanya Singh
GitHub Profile Link : https://github.com/TanyaSingh103
Email ID : tanya.103.singh@gmail.com
Approach for this Project : I'll review the existing documentation and correct any typos or grammatical mistakes. I'll keep the information clear, concise and comprehensible while adhering to existing style.
What is your participant role? GSSOC 24

**Comment by Yuvika-14** [comment]
Hello @abhisheks008 , 
I would love to contribute in this issue since it's very easy for me to correct any typing mistakes as well as grammatical mistakes because I am very proficient in English. Please assign me this issue because no one can do better than me. 

Full Name: Yuvika Singh
GitHub Profile Link: https://github.com/YuvikaSingh
Email ID: yuvika140604@gmail.com

Approach for this Project:
I plan to approach this project by:
Thoroughly reviewing the existing documentation and code comments to identify and correct typing mistakes.
Enhancing the clarity and comprehensiveness of the documentation, ensuring that it is user-friendly and informative.
Improving the README.md file in the Model/ folder by including detailed visualizations and clear, concise conclusions.
Ensuring that all changes are well-documented and that the requirements.txt file is updated to reflect any new dependencies.

**Comment by abhisheks008** [comment]
> Hello @abhisheks008
> 
> I'd like to contribute to this, please add a gssoc tag and assign this issue to me, here are the details:
> 
> Full Name: Tanya Singh GitHub Profile Link : https://github.com/TanyaSingh103 Email ID : [tanya.103.singh@gmail.com](mailto:tanya.103.singh@gmail.com) Approach for this Project : I'll review the existing documentation and correct any typos or grammatical mistakes. I'll keep the information clear, concise and comprehensible while making sure it is user friendly.
> 
> Participant role: GSSOC 24

Issue assigned to you @TanyaSingh103. You can start working on it.

**Comment by abhisheks008** [comment]
> Hello @abhisheks008 , I would love to contribute in this issue since it's very easy for me to correct any typing mistakes as well as grammatical mistakes because I am very proficient in English. Please assign me this issue because no one can do better than me.
> 
> Full Name: Yuvika Singh GitHub Profile Link: https://github.com/YuvikaSingh Email ID: [yuvika140604@gmail.com](mailto:yuvika140604@gmail.com)
> 
> Approach for this Project: I plan to approach this project by: Thoroughly reviewing the existing documentation and code comments to identify and correct typing mistakes. Enhancing the clarity and comprehensiveness of the documentation, ensuring that it is user-friendly and informative. Improving the README.md file in the Model/ folder by including detailed visualizations and clear, concise conclusions. Ensuring that all changes are well-documented and that the requirements.txt file is updated to reflect any new dependencies.

One issue at a time @Yuvika-14
