### ISSUE TITLE
Rick and Morty Character Image Detection 

### ISSUE THREAD

**Issue by abhisheks008** [abhisheks008/DL-Simplified#462]
### Deep Learning Simplified Repository (Proposing new issue)
:red_circle: **Project Title** : Rick and Morty Character Image Detection </br>
:red_circle: **Aim** : The aim of this project is to detect the characters based on the dataset.</br>
:red_circle: **Dataset** : https://www.kaggle.com/datasets/mriffaud/rick-and-morty</br>
:red_circle: **Approach** : Try to use 3-4 algorithms to implement the models and compare all the algorithms to find out the best fitted algorithm for the model by checking the accuracy scores. Also do not forget to do a exploratory data analysis before creating any model.

**********************************************************************************
### 📍 **Follow the Guidelines to Contribute in the Project :**
* You need to create a separate folder named as the Project Title.
* Inside that folder, there will be four main components.
   * Images - To store the required images.
   * Dataset - To store the dataset or, information/source about the dataset.
   * Model - To store the machine learning model you've created using the dataset.
   * `requirements.txt` - This file will contain the required packages/libraries to run the project in other machines.
* Inside the `Model` folder, the `README.md` file must be filled up properly, with proper visualizations and conclusions.

***********************************************************************
:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include issue number along with it.
- Follow Contributing Guidelines & Code of Conduct before start Contributing.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : 
- GitHub Profile Link : 
- Email ID :
- Participant ID (if applicable):
- Approach for this Project :
- What is your participant role? (Mention the Open Source program)

*************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by dipayan22** [comment]
Full name : Dipayan Majumder
GitHub Profile Link : github.com/dipayan22
Email ID : majumderd007@gmail.com
Participant ID (if applicable): 
Approach for this Project : We can use deep learning model (like CNN , Resnet50 , vgg16 etc )for this project
What is your participant role? (Mention the Open Source program) DWOC24

**Comment by abhisheks008** [comment]
I am marking this issue as Hard category. Please keep that in mind while contributing in this issue.
@dipayan22 assigned to you under DWOC 2024.

**Comment by Basma2423** [comment]
Full name: Basma Mahmoud
GitHub Profile Link: [github.com/Basma2423](https://github.com/Basma2423)
Email ID: mayarbasma2423@gmail.com
Approach for this Project: Multiple Deep Learning pre-trained models + CNN
What is your participant role? (Mention the Open Source program): GSSoC-2024 participant

**### I'm a rick and morty fan, and this is my first open-source contribution. I would appreciate it so much.**

**Comment by abhisheks008** [comment]
I have assigned you #506. If you wish I can unassign that and assign this one to you. Or you can work on this issue after completing the assigned one.

@Basma2423

**Comment by Basma2423** [comment]
@abhisheks008 
Yeah please, I'd like pretty much working on both 👍🏼😊

**Comment by abhisheks008** [comment]
You can work on one issue at a time. You can finish the assigned issue, then ask for this issue to get assigned. That'll be better in this case.

**Comment by kyra-09** [comment]
Full name : Aaradhya Singh
GitHub Profile Link : github.com/kyra-09
Email ID : aaradhyasinghgaur@gmail.com
Participant ID (if applicable):
Approach for this Project : Can try already available pre-trained DL models and look into if it can be modified .
What is your participant role? (Mention the Open Source program) -> Contributor /GSSOC - 2024

Hey , @abhisheks008 , I have a very deep understanding of cnn and dl models...for my first os contribution it wil enhance my uderstanding of manipulating existing models for the usecase.

**Please assign this issue to me**

**Comment by abhisheks008** [comment]
Hi @kyra-09 you can go ahead with this approach, issue assigned to you.

**Comment by Basma2423** [comment]
@abhisheks008 
Hey, 
Would it be possible to assign me this issue and switch it with the other one that I'm assigned to? If that's the case, I would appreciate it pretty much.
And if not, no problems. But it would be really great, as I was pretty excited about and looking for it. Thank you

**Comment by abhisheks008** [comment]
Hi @Basma2423 I'm really sorry but this issue is already assigned to someone. It's not possible right now. I hope you understand.

**Comment by Basma2423** [comment]
@abhisheks008 
Okay, no problem 👍🏻

**Comment by kyra-09** [comment]
Hey @abhisheks008 , I have a doubt...I need to determine the prediction accuracy for validation/testset but in order to find accuracy i need true labels of test dataset as well...but it dosn't have true labels to compare from..so do I leave that? or create true label file myself to compare?
