### ISSUE TITLE
Computed Tomography Analysis using DL

### ISSUE THREAD

**Issue by abhisheks008** [abhisheks008/DL-Simplified#468]
### Deep Learning Simplified Repository (Proposing new issue)
:red_circle: **Project Title** : Computed Tomography Analysis using DL</br>
:red_circle: **Aim** : The aim of this project is to analyze the CT scan images using the given dataset.</br>
:red_circle: **Dataset** : https://www.kaggle.com/datasets/trainingdatapro/computed-tomography-ct-of-the-brain</br>
:red_circle: **Approach** : Try to use 3-4 algorithms to implement the models and compare all the algorithms to find out the best fitted algorithm for the model by checking the accuracy scores. Also do not forget to do a exploratory data analysis before creating any model.

**********************************************************************************
### 📍 **Follow the Guidelines to Contribute in the Project :**
* You need to create a separate folder named as the Project Title.
* Inside that folder, there will be four main components.
   * Images - To store the required images.
   * Dataset - To store the dataset or, information/source about the dataset.
   * Model - To store the machine learning model you've created using the dataset.
   * `requirements.txt` - This file will contain the required packages/libraries to run the project in other machines.
* Inside the `Model` folder, the `README.md` file must be filled up properly, with proper visualizations and conclusions.

***********************************************************************
:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include issue number along with it.
- Follow Contributing Guidelines & Code of Conduct before start Contributing.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : 
- GitHub Profile Link : 
- Email ID :
- Participant ID (if applicable):
- Approach for this Project :
- What is your participant role? (Mention the Open Source program)

*************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Jeba-Rachel-Nesica** [comment]
Hi @abhisheks008 ,
I'd like to work on this issue.

Full name : JEBA RACHEL NESICA
GitHub Profile Link : https://github.com/Jeba-Rachel-Nesica
Email ID : jebarachelnesica@gmail.com
Participant ID (if applicable):
Approach for this Project :  U-Net, ResNet, CNN (using pre-trained models like VGG) are to be used to find the best fitting one.
What is your participant role? (Mention the Open Source program): GSSoC'24 Contributor

**Comment by Jaya-Prakash-17** [comment]
Full name : Jaya Prakash Sangem 
      (Im new to Open Source programs and also my GitHub profile is pretty much plain but, I have worked on similar 
      project on [classification of Brain Tumors from MRI scans](https://papers.ssrn.com/sol3/papers.cfm?abstract_id=4607794), So, I hope that experice would help me here addressing this 
      particular issue.)
      
GitHub Profile Link : https://github.com/Jaya-Prakash-17
Email ID : 21211a7253@bvrit.ac.in; 
                jayaprakashsangem@gmail.com
Approach for this Project : 
     -->Data Collection
     -->Data Preprocessing
     -->EDA (applying different filters like Guassian filter, gray scale etc to understand the image)
     --> Model Building &  training (I paticularly want to try out various DL Models, CNNs like(Resnet, Efficientnet, 
             InceptionNet and Many more advanced models and check which model gives best results)
What is your participant role?: Contributor @GSSOC24

So, kindly assign this issue to me. 
THANK YOU!!
