### ISSUE TITLE
README Enhancement - Avocados Classification

### ISSUE THREAD

**Issue by abhisheks008** [abhisheks008/DL-Simplified#472]
### Deep Learning Simplified Repository (Proposing new issue)
:red_circle: **Project Title** : README Enhancement - Avocados Classification</br>
:red_circle: **Aim** : The aim is to enhance the README file to make it more eye pleasing.</br>
:red_circle: **README to be enhanced** : https://github.com/abhisheks008/DL-Simplified/blob/main/Avocados%20Classification/README.md</br>
:red_circle: **Template** : https://github.com/abhisheks008/DL-Simplified/blob/main/.github/readme_template.md

**********************************************************************************
### 📍 **Follow the Guidelines to Contribute in the Project :**
* You need to create a separate folder named as the Project Title.
* Inside that folder, there will be four main components.
   * Images - To store the required images.
   * Dataset - To store the dataset or, information/source about the dataset.
   * Model - To store the machine learning model you've created using the dataset.
   * `requirements.txt` - This file will contain the required packages/libraries to run the project in other machines.
* Inside the `Model` folder, the `README.md` file must be filled up properly, with proper visualizations and conclusions.

***********************************************************************
:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include issue number along with it.
- Follow Contributing Guidelines & Code of Conduct before start Contributing.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : 
- GitHub Profile Link : 
- Email ID :
- Participant ID (if applicable):
- Approach for this Project :
- What is your participant role? (Mention the Open Source program)

*************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by mariam7084** [comment]
Full name : Mariam
GitHub Profile Link : github.com/mariam7084
Email ID : mariammanaullah1503@gmail.com
Participant ID (if applicable): NA
Approach for this Project : i will modify the readme.md according to the template provided.
What is your participant role? (Mention the Open Source program) DWoC

**Comment by abhisheks008** [comment]
Issue assigned to you under DWOC @mariam7084
