### ISSUE TITLE
README Enhancement - Brain Tumor Detection

### ISSUE THREAD

**Issue by abhisheks008** [abhisheks008/DL-Simplified#475]
### Deep Learning Simplified Repository (Proposing new issue)
:red_circle: **Project Title** : README Enhancement - Brain Tumor Detection</br>
:red_circle: **Aim** : The aim is to enhance the README file and make it eye pleasing, well documented using the given README template.</br>
:red_circle: **README to be enhanced** : https://github.com/abhisheks008/DL-Simplified/blob/main/Brain%20Tumor%20Detection/Model/README.md</br>
:red_circle: **README Template** : https://github.com/abhisheks008/DL-Simplified/blob/main/.github/readme_template.md

***********************************************************************
:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include issue number along with it.
- Follow Contributing Guidelines & Code of Conduct before start Contributing.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : 
- GitHub Profile Link : 
- Email ID :
- Participant ID (if applicable):
- Approach for this Project :
- What is your participant role? (Mention the Open Source program)

*************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by ARPIT2128** [comment]
Full name : Arpit Sharma 
GitHub Profile Link : https://github.com/ARPIT2128
Email ID : arpitsharma2128@gmail.com
Approach for this Project : Going through the implementation and readme
What is your participant role? SWOC2024

**Comment by abhisheks008** [comment]
Assigned @ARPIT2128
