### ISSUE TITLE
README Enhancement - Canola Diseases Detection

### ISSUE THREAD

**Issue by abhisheks008** [abhisheks008/DL-Simplified#487]
### Deep Learning Simplified Repository (Proposing new issue)
:red_circle: **Project Title** : README Enhancement - Canola Diseases Detection</br>
:red_circle: **Aim** : The aim is to enhance the README file and make it eye pleasing, well documented using the given README template.</br>
:red_circle: **README to be enhanced** : https://github.com/abhisheks008/DL-Simplified/tree/main/Canola%20Diseases%20Prediction/Model</br>
:red_circle: **README Template** : https://github.com/abhisheks008/DL-Simplified/blob/main/.github/readme_template.md

***********************************************************************
:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include issue number along with it.
- Follow Contributing Guidelines & Code of Conduct before start Contributing.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : 
- GitHub Profile Link : 
- Email ID :
- Participant ID (if applicable):
- Approach for this Project :
- What is your participant role? (Mention the Open Source program)

*************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Santhosh-Siddhardha** [comment]
Hi @abhisheks008 ,

- Full Name: Lingamuneni Santhosh Siddhardha
- GitHub Profile Link: [[Santhosh-Siddhardha]](https://github.com/Santhosh-Siddhardha)
- Email ID: [siddhardha.7085@gmail.com](mailto:siddhardha.7085@gmail.com)
- Participant ID: NA
- Approach for the Project:
Review Existing README: Thoroughly review the current README file and identify areas for improvement based on the provided template.
Enhancement Plan: Develop a plan to enhance the README file, incorporating visual elements, formatting improvements, and additional documentation as per the template.
Implementation: Make the necessary enhancements to the README file following the agreed-upon plan and guidelines.
Testing and Validation: Validate the enhanced README to ensure clarity, correctness, and visual appeal.
Documentation: Document the enhancements made in the README file and provide a summary of changes.
- Participant Role: GSSoC24 Contributor

**Comment by abhisheks008** [comment]
Issue assigned to you @Santhosh-Siddhardha
