### ISSUE TITLE
README Enhancement - Cats vs Dogs Classification using DL

### ISSUE THREAD

**Issue by abhisheks008** [abhisheks008/DL-Simplified#489]
### Deep Learning Simplified Repository (Proposing new issue)
:red_circle: **Project Title** : README Enhancement - Cats vs Dogs Classification using DL</br>
:red_circle: **Aim** : The aim is to enhance the README file and make it eye pleasing, well documented using the given README template.</br>
:red_circle: **README to be enhanced** : https://github.com/abhisheks008/DL-Simplified/blob/main/Cats%20vs%20Dogs%20Classification%20using%20DL/README.md</br>
:red_circle: **README Template** : https://github.com/abhisheks008/DL-Simplified/blob/main/.github/readme_template.md

***********************************************************************
:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include issue number along with it.
- Follow Contributing Guidelines & Code of Conduct before start Contributing.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : 
- GitHub Profile Link : 
- Email ID :
- Participant ID (if applicable):
- Approach for this Project :
- What is your participant role? (Mention the Open Source program)

*************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by niyonikagaur** [comment]
Full name : Niyonika Gaur
GitHub Profile Link : https://github.com/niyonikagaur
Email ID : nngaurz@gmail.com
Approach for this Project : To enhance the project's README file using the template
What is your participant role? (Mention the Open Source program): GSSoC'24 Contributor

**Comment by nandni-a** [comment]
Full name : Nandni Aggarwal
GitHub Profile Link : https://github.com/nandni-a
Email ID : nandni.aggarwal2004@gmail.com
Approach for this Project : To enhance the projects README file . 
What is your participant role? (Mention the Open Source program) : GSSoC 24 Contributor

**Comment by abhisheks008** [comment]
Issues will be assigned to the contributors based on first come first serve (FCFS). Issue assigned to @niyonikagaur.

@nandni-a you can try out other issues, lots of open issues are there in the repo.

**Comment by niyonikagaur** [comment]
The images under the Visualization heading are not loading.

**Comment by abhisheks008** [comment]
That's what you need to do, enhance the README, fix the problems. For the images you can check out the Images folder of that particular project.
