### ISSUE TITLE
Global Land Cover Mapping using Image Processing

### ISSUE THREAD

**Issue by abhisheks008** [abhisheks008/DL-Simplified#503]
### Deep Learning Simplified Repository (Proposing new issue)
:red_circle: **Project Title** : Global Land Cover Mapping using Image Processing</br>
:red_circle: **Aim** : The aim is to analyze the dataset using image processing and deep learning methods and find out the best fitted model for this dataset.</br>
:red_circle: **Dataset** : https://www.kaggle.com/datasets/aletbm/global-land-cover-mapping-openearthmap</br>
:red_circle: **Approach** : Try to use 3-4 algorithms to implement the models and compare all the algorithms to find out the best fitted algorithm for the model by checking the accuracy scores. Also do not forget to do a exploratory data analysis before creating any model.

**********************************************************************************
### 📍 **Follow the Guidelines to Contribute in the Project :**
* You need to create a separate folder named as the Project Title.
* Inside that folder, there will be four main components.
   * Images - To store the required images.
   * Dataset - To store the dataset or, information/source about the dataset.
   * Model - To store the machine learning model you've created using the dataset.
   * `requirements.txt` - This file will contain the required packages/libraries to run the project in other machines.
* Inside the `Model` folder, the `README.md` file must be filled up properly, with proper visualizations and conclusions.

***********************************************************************
:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include issue number along with it.
- Follow Contributing Guidelines & Code of Conduct before start Contributing.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : 
- GitHub Profile Link : 
- Email ID :
- Participant ID (if applicable):
- Approach for this Project :
- What is your participant role? (Mention the Open Source program)

*************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by tushtithakur** [comment]
Hi , I'm excited to contribute to this project. Could you please assign me? Looking forward to getting started! @abhisheks008

Full name : Tushti Thakur
GitHub Profile Link : https://github.com/tushtithakur
Email ID : tushtithakur1234@gmail.com
Approach for this Project : Implement different deep learning algorithms using the dataset, evaluate it and compare performance.
What is your participant role? GSSoC 2024

**Comment by abhisheks008** [comment]
Hi @tushtithakur wait for the induction session to complete by today evening, after that issues will be assigned to the contributors.

**Comment by tushtithakur** [comment]
@abhisheks008 Sure sir, I'll wait for the induction session to be completed. Thank you for the update!

**Comment by abhisheks008** [comment]
Hi @ArismitaM can you clarify more on the algorithms/models you are planning to use here?

**Comment by ArismitaM** [comment]
I am planning to use YOLOv5 to train for land cover and identify the same

**Comment by abhisheks008** [comment]
> I am planning to use YOLOv5 to train for land cover and identify the same

I know YOLO is a go to option for this kind of datasets. Can you share some other approaches along with the YOLO one?

Basically here in this repo, we used to ask our contributors to implement at least 2-3 models for the same dataset, check their accuracy scores and then conclude that some x is the best fitted model for this project. I hope you understand my point.

**Comment by ArismitaM** [comment]
> > I am planning to use YOLOv5 to train for land cover and identify the same
> 
> I know YOLO is a go to option for this kind of datasets. Can you share some other approaches along with the YOLO one?
> 
> Basically here in this repo, we used to ask our contributors to implement at least 2-3 models for the same dataset, check their accuracy scores and then conclude that some x is the best fitted model for this project. I hope you understand my point.

I can use VGG16 or ResNet50 too as different models compared to YOLO

**Comment by ArismitaM** [comment]
> > > I am planning to use YOLOv5 to train for land cover and identify the same
> > 
> > 
> > I know YOLO is a go to option for this kind of datasets. Can you share some other approaches along with the YOLO one?
> > Basically here in this repo, we used to ask our contributors to implement at least 2-3 models for the same dataset, check their accuracy scores and then conclude that some x is the best fitted model for this project. I hope you understand my point.
> 
> I can use VGG16 or ResNet50 too as different models compared to YOLO

I will use vgg16, resnet50, yolo, and inceptionv3 and then do a comparative study to analyze which model works the best and yields a better result for this issue. Please assign this task to me

**Comment by abhisheks008** [comment]
Cool! Issue assigned to you @ArismitaM

**Comment by ArismitaM** [comment]
Hi @abhisheks008, I have downloaded the Kaggle dataset and have gone through its contents. The images as well as the labels are .tiff files. The readme file provided with the Kaggle dataset does not explain the structure of the information in the dataset except for mentioning the hexadecimal number associated with each label. From this, I have the following inference:
- The image .tiff file is just a single layer of image
- The .tiff file for the corresponding label contains a layer of image that contains the areas associated with the label of this layer.
I will have to use this information structure to create bounding boxes for each of the land cover types to train YOLO with. It would help me if you could confirm whether my understanding of the information content in the .tiff files is correct or not.
If I have misunderstood, kindly provide the structure of the information in the tiff files.

**Comment by abhisheks008** [comment]
> Hi @abhisheks008, I have downloaded the Kaggle dataset and have gone through its contents. The images as well as the labels are .tiff files. The readme file provided with the Kaggle dataset does not explain the structure of the information in the dataset except for mentioning the hexadecimal number associated with each label. From this, I have the following inference:
> 
> * The image .tiff file is just a single layer of image
> * The .tiff file for the corresponding label contains a layer of image that contains the areas associated with the label of this layer.
> 
> I will have to use this information structure to create bounding boxes for each of the land cover types to train YOLO with. It would help me if you could confirm whether my understanding of the information content in the .tiff files is correct or not. If I have misunderstood, kindly provide the structure of the information in the tiff files.

You are going in the right direction. 🚀

**Comment by ArismitaM** [comment]
Hi @abhisheks008, I have analyzed the data set.

**This is an image present in the dataset under the directory images/train**

![Screenshot from 2024-05-18 19-19-43](https://github.com/abhisheks008/DL-Simplified/assets/146760434/82b95f82-e6b5-4265-89d6-e97c12b849dd)

**Each image has 3 layers, so below are the layers of the above image:**

![Screenshot from 2024-05-18 19-20-01](https://github.com/abhisheks008/DL-Simplified/assets/146760434/ec853ed6-b71c-4bbe-93ee-58ecce692b45)

![Screenshot from 2024-05-18 19-20-09](https://github.com/abhisheks008/DL-Simplified/assets/146760434/6e521154-e053-455d-9846-b7e324a8ec1e)

![Screenshot from 2024-05-18 19-20-16](https://github.com/abhisheks008/DL-Simplified/assets/146760434/77b834e0-ea67-4a78-9917-144f9f9f39df)

**There is a corresponding label/train which has 1 layer with coloured label**

![Screenshot from 2024-05-18 19-20-38](https://github.com/abhisheks008/DL-Simplified/assets/146760434/f87a5c3e-2ad7-495d-8472-aee35c3e30e8)

**Comment by abhisheks008** [comment]
@ArismitaM looks good to me.

**Comment by ArismitaM** [comment]
With reference to my comment above, I have a few queries,

1. In the images directory as well as the label directory, there is a folder called 'val' which also contains images, but I have not understood where to use them.
2. There are 3 layers for each image and a corresponding label for it. I want to understand the purpose of the 3 layers for each image.
3. How is the information organized for each image and corresponding label?

**Comment by abhisheks008** [comment]
### Query 1:
The `val` directory typically stands for 'validation'. In machine learning and deep learning, datasets are often split into three sets:

- Training set: Used to train the model.
- Validation set: Used to evaluate the model during training and tune hyperparameters.
- Test set: Used to evaluate the model's performance after training is complete

### Query 2:
The three layers in each image likely represent the three color channels in the image: Red, Green, and Blue (RGB). Each layer corresponds to the intensity of that color in the image:

- The first layer shows the intensity of the red color.
- The second layer shows the intensity of the green color.
- The third layer shows the intensity of the blue color.

When these layers are combined, they form a full-color image.

### Query 3:
Each image in the dataset is organized with its corresponding label, which likely represents the segmentation or classification information. Here's a typical structure:

- Images Directory: Contains subdirectories for training and validation images.

    - `images/train`: Contains the training images, each having three layers (RGB channels).
    - `images/val`: Contains the validation images, each having three layers (RGB channels).

- Labels Directory: Contains subdirectories for training and validation labels.

    - `labels/train`: Contains the training labels, usually a single-layer image where each pixel value represents a class label.
    - `labels/val`: Contains the validation labels, similarly structured to the training labels.

Three layers for each image are the RGB channels that combine to form the full-color image. The label image uses colors to represent different classes or segments corresponding to regions in the input image. The 'val' directory contains data for validation purposes, used to tune and evaluate the model during training.

### Example:
- Image Layers (RGB):
  - Red Channel (Layer 1):
    ![Screenshot from 2024-05-18 19-20-01](https://github.com/abhisheks008/DL-Simplified/assets/146760434/ec853ed6-b71c-4bbe-93ee-58ecce692b45)

  - Green Channel (Layer 2):
    ![Screenshot from 2024-05-18 19-20-09](https://github.com/abhisheks008/DL-Simplified/assets/146760434/6e521154-e053-455d-9846-b7e324a8ec1e)

   - Blue Channel (Layer 3):
    ![Screenshot from 2024-05-18 19-20-16](https://github.com/abhisheks008/DL-Simplified/assets/146760434/77b834e0-ea67-4a78-9917-144f9f9f39df)


- Corresponding Label:
![Screenshot from 2024-05-18 19-20-38](https://github.com/abhisheks008/DL-Simplified/assets/146760434/f87a5c3e-2ad7-495d-8472-aee35c3e30e8)


@ArismitaM

**Comment by ArismitaM** [comment]
Thank you for the clarification @abhisheks008.
I am able to understand the structure of information in the dataset.

**Comment by ArismitaM** [comment]
Hi @abhisheks008, I am writing a code that will draw bounding boxes around the objects with the same colour in the labels image (different colours are used for different classes) and generate a .txt file for it.
Do you think that this is an optimal method to do it?

**Comment by abhisheks008** [comment]
> Hi @abhisheks008, I am writing a code that will draw bounding boxes around the objects with the same colour in the labels image (different colours are used for different classes) and generate a .txt file for it. Do you think that this is an optimal method to do it?

If it is working with the development, then go for it.

**Comment by ArismitaM** [comment]
Hello @abhisheks008,
I have clustered the points of each of the classes using DBScan. PFA is the plot of a label and its corresponding cluster. Similar clusters have been created for all the labels in a raster file. 

label
![Screenshot from 2024-05-31 10-43-17](https://github.com/abhisheks008/DL-Simplified/assets/146760434/cd5a808e-760d-465d-877e-a85fe76979e8)

cluster
![Screenshot from 2024-05-31 10-44-34](https://github.com/abhisheks008/DL-Simplified/assets/146760434/096187d0-1fcb-489c-9161-d28ca9d8d6c1)

**Comment by abhisheks008** [comment]
> Hello @abhisheks008, I have clustered the points of each of the classes using DBScan. PFA is the plot of a label and its corresponding cluster. Similar clusters have been created for all the labels in a raster file.
> 
> label ![Screenshot from 2024-05-31 10-43-17](https://private-user-images.githubusercontent.com/146760434/335453704-cd5a808e-760d-465d-877e-a85fe76979e8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcyMDkzNzIsIm5iZiI6MTcxNzIwOTA3MiwicGF0aCI6Ii8xNDY3NjA0MzQvMzM1NDUzNzA0LWNkNWE4MDhlLTc2MGQtNDY1ZC04NzdlLWE4NWZlNzY5NzllOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwMVQwMjMxMTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zYWFmMDQxMTk4ZjVmMWRmMGIxNTc3OTc5NTJkMWY5YmY5YjE3ZGQ0ZWZlNjM1OTA1MzUxOGI0N2MxNjA4NDE4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.XuEAioXdgrIytJAeGpD-AFaOVmaNLOebeJHuy3w53y0)
> 
> cluster ![Screenshot from 2024-05-31 10-44-34](https://private-user-images.githubusercontent.com/146760434/335453772-096187d0-1fcb-489c-9161-d28ca9d8d6c1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcyMDkzNzIsIm5iZiI6MTcxNzIwOTA3MiwicGF0aCI6Ii8xNDY3NjA0MzQvMzM1NDUzNzcyLTA5NjE4N2QwLTFmY2ItNDg5Yy05MTYxLWQyOGNhOWQ4ZDZjMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwMVQwMjMxMTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01OTJmNWU0NTA4NTkxZmY5ZmY2YjhlNTU3ZWZhZmY5NzhkNTQyYTgwNWFkMjRkMjA1ZjdkYjIyYTU1ZTI5ZTZmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.kCico19Tm0W5NTX1Yn0SX3ME7Vd-YXjPLN4KOY60O9Q)

Looks good to me. Any issues with this?

**Comment by ArismitaM** [comment]
> > Hello @abhisheks008, I have clustered the points of each of the classes using DBScan. PFA is the plot of a label and its corresponding cluster. Similar clusters have been created for all the labels in a raster file.
> > label ![Screenshot from 2024-05-31 10-43-17](https://private-user-images.githubusercontent.com/146760434/335453704-cd5a808e-760d-465d-877e-a85fe76979e8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcyMDkzNzIsIm5iZiI6MTcxNzIwOTA3MiwicGF0aCI6Ii8xNDY3NjA0MzQvMzM1NDUzNzA0LWNkNWE4MDhlLTc2MGQtNDY1ZC04NzdlLWE4NWZlNzY5NzllOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwMVQwMjMxMTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zYWFmMDQxMTk4ZjVmMWRmMGIxNTc3OTc5NTJkMWY5YmY5YjE3ZGQ0ZWZlNjM1OTA1MzUxOGI0N2MxNjA4NDE4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.XuEAioXdgrIytJAeGpD-AFaOVmaNLOebeJHuy3w53y0)
> > cluster ![Screenshot from 2024-05-31 10-44-34](https://private-user-images.githubusercontent.com/146760434/335453772-096187d0-1fcb-489c-9161-d28ca9d8d6c1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcyMDkzNzIsIm5iZiI6MTcxNzIwOTA3MiwicGF0aCI6Ii8xNDY3NjA0MzQvMzM1NDUzNzcyLTA5NjE4N2QwLTFmY2ItNDg5Yy05MTYxLWQyOGNhOWQ4ZDZjMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwMVQwMjMxMTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01OTJmNWU0NTA4NTkxZmY5ZmY2YjhlNTU3ZWZhZmY5NzhkNTQyYTgwNWFkMjRkMjA1ZjdkYjIyYTU1ZTI5ZTZmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.kCico19Tm0W5NTX1Yn0SX3ME7Vd-YXjPLN4KOY60O9Q)
> 
> Looks good to me. Any issues with this?

no issues with this, I was giving an update

**Comment by ArismitaM** [comment]
I have drawn boxes around the clusters and this is how it looks:

![Screenshot from 2024-06-01 11-01-25](https://github.com/abhisheks008/DL-Simplified/assets/146760434/8808d715-277b-490e-9477-11eb6eb2959b)

![Screenshot from 2024-06-01 11-00-27](https://github.com/abhisheks008/DL-Simplified/assets/146760434/a9867f79-698b-48ef-8751-cf118fb138a5)

![Screenshot from 2024-06-01 11-00-44](https://github.com/abhisheks008/DL-Simplified/assets/146760434/bd87e015-f721-468a-a8db-821e7c750253)

![Screenshot from 2024-06-01 11-01-01](https://github.com/abhisheks008/DL-Simplified/assets/146760434/494c1921-c482-42bd-9f5e-35c8044bafd6)

**Comment by ArismitaM** [comment]
Hello @abhisheks008 ,
Here is an update:
I have trained this model in YOLOv5 using GPU successfully.
I tried using VGG but I realized that it was not ideal for object detection.
Then I moved on to RetinaNet. The first round of training worked well with CPU but it did not work with my GPU due to lack of memory. So, I have switched to training with CPU which is why it is taking time for the training process.

**Comment by abhisheks008** [comment]
> Hello @abhisheks008 , Here is an update: I have trained this model in YOLOv5 using GPU successfully. I tried using VGG but I realized that it was not ideal for object detection. Then I moved on to RetinaNet. The first round of training worked well with CPU but it did not work with my GPU due to lack of memory. So, I have switched to training with CPU which is why it is taking time for the training process.

Looks pretty good. Carry on!
