### ISSUE TITLE
Micromobility Lane Recognition

### ISSUE THREAD

**Issue by abhisheks008** [abhisheks008/DL-Simplified#506]
### Deep Learning Simplified Repository (Proposing new issue)
:red_circle: **Project Title** : Micromobility Lane Recognition</br>
:red_circle: **Aim** : The aim is to apply deep learning methods for recognizing micro mobility lanes from the given dataset.</br>
:red_circle: **Dataset** : https://www.kaggle.com/datasets/kaundanyachinmaya07/micromobility-lane-recognition-dataset</br>
:red_circle: **Approach** : Try to use 3-4 algorithms to implement the models and compare all the algorithms to find out the best fitted algorithm for the model by checking the accuracy scores. Also do not forget to do a exploratory data analysis before creating any model.

**********************************************************************************
### 📍 **Follow the Guidelines to Contribute in the Project :**
* You need to create a separate folder named as the Project Title.
* Inside that folder, there will be four main components.
   * Images - To store the required images.
   * Dataset - To store the dataset or, information/source about the dataset.
   * Model - To store the machine learning model you've created using the dataset.
   * `requirements.txt` - This file will contain the required packages/libraries to run the project in other machines.
* Inside the `Model` folder, the `README.md` file must be filled up properly, with proper visualizations and conclusions.

***********************************************************************
:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include issue number along with it.
- Follow Contributing Guidelines & Code of Conduct before start Contributing.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : 
- GitHub Profile Link : 
- Email ID :
- Participant ID (if applicable):
- Approach for this Project :
- What is your participant role? (Mention the Open Source program)

*************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Santhosh-Siddhardha** [comment]
Hi @abhisheks008 ,

- Full Name: Lingamuneni Santhosh Siddhardha
- GitHub Profile Link: [[Santhosh-Siddhardha]](https://github.com/Santhosh-Siddhardha)
- Email ID: [siddhardha.7085@gmail.com](mailto:siddhardha.7085@gmail.com)
- Participant ID: NA
- Approach for the Project:
Data Exploration: Perform exploratory data analysis (EDA) to understand the characteristics and challenges of the micromobility lane dataset.
Model Implementation: Implement 3-4 deep learning algorithms suitable for image recognition tasks (e.g., CNN, ResNet).
Model Comparison: Compare the performance of algorithms based on accuracy scores and other relevant metrics.
Documentation: Provide comprehensive documentation within the Model folder, including visualizations and conclusions from the deep learning experiments.
- Participant Role: GSSoC24 Contributor

**Comment by Basma2423** [comment]
Wanna give it a try, can you assign it to me? @abhisheks008 

Full name: **Basma Mahmoud**
GitHub Profile Link: [Basma2423](https://github.com/Basma2423)
Email ID: [mayarbasma2423@gmail.com](mailto:mayarbasma2423@gmail.com)
Approach for this Project: Multiple Deep Learning pre-trained models + CNN
What is your participant role? (Mention the Open Source program): GSSoC-2024 participant

Can you add the label for GSSoC, please?
Thanks.

**Comment by abhisheks008** [comment]
Hi @Basma2423 issue assigned to you. You can start working on it.

**Comment by Basma2423** [comment]
Thank you 😊
@abhisheks008 
I'll start working right now!

**Comment by VoonnaHarsha** [comment]
Wanna give it a try, can you assign it to me? @abhisheks008 

Full name: Voonna Harsha
GitHub Profile Link: https://github.com/VoonnaHarsha
Email ID: harshavoonna@gmail.com

What is your participant role? (Mention the Open Source program): GSSoC-2024 participant

Can you add the label for GSSoC, please?
Thanks.
