### ISSUE TITLE
Lending Club Loan Analysis

### ISSUE THREAD

**Issue by abhisheks008** [abhisheks008/DL-Simplified#52]
### Deep Learning Simplified Repository (Proposing new issue)
:red_circle: **Project Title** : Lending Club Loan Analysis</br>
:red_circle: **Aim** : Analyse the aspects of the lending clubs from different parameters.</br>
:red_circle: **Dataset** : https://www.kaggle.com/datasets/gabrielsantello/lending-club-loan-preprocessed-dataset</br>
:red_circle: **Approach** : Try to use 3-4 algorithms to implement the models and compare all the algorithms to find out the best fitted algorithm for the model by checking the accuracy scores. Also do not forget to do a exploratory data analysis before creating any model.

**********************************************************************************
### 📍 **Follow the Guidelines to Contribute in the Project :**
* You need to create a separate folder named as the Project Title.
* Inside that folder, there will be four main components.
   * Images - To store the required images.
   * Dataset - To store the dataset or, information/source about the dataset.
   * Model - To store the machine learning model you've created using the dataset.
   * `requirements.txt` - This file will contain the required packages/libraries to run the project in other machines.
* Inside the `Model` folder, the `README.md` file must be filled up properly, with proper visualizations and conclusions.

***********************************************************************
:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include issue number along with it.
- Follow Contributing Guidelines & Code of Conduct before start Contributing.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : 
- GitHub Profile Link : 
- Email ID :
- Participant ID (if applicable):
- Approach for this Project :
- What is your participant role? (Mention the Open Source program)

*************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by 123Vasu** [comment]
Please Assign this task to me .

**Comment by 123Vasu** [comment]
Name : Vasu Arora

**Comment by abhisheks008** [comment]
✅ To be Mentioned while taking the issue :

Full name :
GitHub Profile Link :
Email ID :
Participant ID (if applicable):
Approach for this Project :
What is your participant role? (Mention the Open Source program)

@123Vasu

**Comment by Rushijaviya** [comment]
Please follow the format mentioned.

**Comment by 123Vasu** [comment]
Full Name : Vasu Arora 
GitHub Profile Link : https://github.com/123Vasu
Email Id : shrisw2002@gmail.com
Approach for this Project :  I will use a variety of Deep learning and Machine Learning models and try to do my best.
What is your participant role? SSOC Open Source program
Please Assign this task to me .

**Comment by 072arushi** [comment]
@123Vasu you have been assigned the issue. All the best.

**Comment by 123Vasu** [comment]
Thank You

**Comment by abhisheks008** [comment]
@123Vasu updates please.

**Comment by 123Vasu** [comment]
It is in progress,Sir.

**Comment by abhisheks008** [comment]
Okay carry on and keep updating here @123Vasu

**Comment by abhisheks008** [comment]
Updates please @123Vasu

**Comment by 123Vasu** [comment]
Sir I have made 1 model Today or Tomorrow I will Make Pull Request.

**Comment by 123Vasu** [comment]
Sir, Iam Vasu Arora this side. I participated and submitted my project
within a time but  I didn't get  my Tshirt 👕. please check it.

**Comment by abhisheks008** [comment]
Drop a text in the SWOC channel and tag Jai Sadana, if he didn't respond, drop a message everyday by tagging him. Everything is on him, even the project admins didn't get any social media recognition.
