### ISSUE TITLE
Hand Navigation Landmarks Detection

### ISSUE THREAD

**Issue by abhisheks008** [abhisheks008/DL-Simplified#523]
### Deep Learning Simplified Repository (Proposing new issue)
:red_circle: **Project Title** : Hand Navigation Landmarks Detection</br>
:red_circle: **Aim** : The aim is to detect the landmarks made by the hand gestures using deep learning.</br>
:red_circle: **Dataset** : https://www.kaggle.com/datasets/harisudhan411/hand-navigation-landmarks</br>
:red_circle: **Approach** : Try to use 3-4 algorithms to implement the models and compare all the algorithms to find out the best fitted algorithm for the model by checking the accuracy scores. Also do not forget to do a exploratory data analysis before creating any model.

**********************************************************************************
### 📍 **Follow the Guidelines to Contribute in the Project :**
* You need to create a separate folder named as the Project Title.
* Inside that folder, there will be four main components.
   * Images - To store the required images.
   * Dataset - To store the dataset or, information/source about the dataset.
   * Model - To store the machine learning model you've created using the dataset.
   * `requirements.txt` - This file will contain the required packages/libraries to run the project in other machines.
* Inside the `Model` folder, the `README.md` file must be filled up properly, with proper visualizations and conclusions.

***********************************************************************
:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include issue number along with it.
- Follow Contributing Guidelines & Code of Conduct before start Contributing.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : 
- GitHub Profile Link : 
- Email ID :
- Participant ID (if applicable):
- Approach for this Project :
- What is your participant role? (Mention the Open Source program)

*************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by utsabsamadder** [comment]
@abhisheks008 I could work on this for GSSoC'24 as this is quite an interesting and could be done with a little bit of effort. 
Thank you and Best Regards.

**Comment by abhisheks008** [comment]
Sure @utsabsamadder, can you please share your approach and details as per the issue template?

**Comment by utsabsamadder** [comment]
@abhisheks008, here you go.
Full name : Utsab Samadder
GitHub Profile Link : https://github.com/utsabsamadder/
Email ID : utsab.samadder@gmail.com
Participant ID (if applicable): 
Approach for this Project: I would like to use YOLO(You Only Look Once) on this. I have recently learned about it and in some cases it is better than ANN or CNN.
What is your participant role? (Mention the Open Source program) :GSSoC'24

**Comment by utsabsamadder** [comment]
I am planning to mainly focus on YOLO but i will check the accuracy with  other models as well like ANN as you have asked in the issue.

**Comment by abhisheks008** [comment]
Issue assigned to you @utsabsamadder
