### ISSUE TITLE
[README Enhancement]: ChatGPT-Based Tweets Sentiment Analysis Using Deep Learning

### ISSUE THREAD

**Issue by abhisheks008** [abhisheks008/DL-Simplified#524]
### Deep Learning Simplified Repository (Proposing new issue)
:red_circle: **Project Title** : README Enhancement: ChatGPT-Based Tweets Sentiment Analysis Using Deep Learning</br>
:red_circle: **Aim** : The aim is to enhance the README file and make it eye pleasing, well documented using the given README template.</br>
:red_circle: **README to be enhanced** : https://github.com/abhisheks008/DL-Simplified/blob/main/ChatGPT%20Based%20Tweets%20Sentiment%20Analysis%20Using%20DL/Readme.md</br>
:red_circle: **README Template** : https://github.com/abhisheks008/DL-Simplified/blob/main/.github/readme_template.md

***********************************************************************
:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include issue number along with it.
- Follow Contributing Guidelines & Code of Conduct before start Contributing.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : 
- GitHub Profile Link : 
- Email ID :
- Participant ID (if applicable):
- Approach for this Project :
- What is your participant role? (Mention the Open Source program)

*************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by jindalpriyanshu101** [comment]
Hi @abhisheks008 can you assign it to me.

- **Full name:** Priyanshu Aggarwal
- **GitHub Profile Link:** https://github.com/jindalpriyanshu101
- **Email ID:** priyanshujindal101@gmail.com
- **Participant ID (if applicable):** N/A
- **Approach for this Project:** By following the template provided, i'll make it look significantly beautiful, while making sure the required content is organised in its place.
- **What is your participant role? (Mention the Open Source program):** GSSoC'24 Contributor

**Comment by abhisheks008** [comment]
Hi @jindalpriyanshu101 you can work on this issue, make sure you use the README template and also you can improvise from your end too.

**Comment by jindalpriyanshu101** [comment]
Hey @abhisheks008, while updating the readme, i found that [requirements.txt](https://github.com/abhisheks008/DL-Simplified/blob/main/ChatGPT%20Based%20Tweets%20Sentiment%20Analysis%20Using%20DL/requirement.txt) is seriously messed up, which will cause errors if anyone tries to install libraries through that. ScreenShot is attached for visualization of the same:
![image](https://github.com/abhisheks008/DL-Simplified/assets/52918255/ffd818bb-184f-4f96-b738-1304e1a1341a)


Am i supposed to fix that as well to ensure smooth usage?

**Comment by abhisheks008** [comment]
It'll be better if you make the changes. @jindalpriyanshu101

**Comment by jindalpriyanshu101** [comment]
Alright, thanks for clarification
