### ISSUE TITLE
[README Enhancement]: Children vs Adults Classification

### ISSUE THREAD

**Issue by abhisheks008** [abhisheks008/DL-Simplified#525]
### Deep Learning Simplified Repository (Proposing new issue)
:red_circle: **Project Title** : README Enhancement: Children vs Adults Classification</br>
:red_circle: **Aim** : The aim is to enhance the README file and make it eye pleasing, well documented using the given README template.</br>
:red_circle: **README to be enhanced** : https://github.com/abhisheks008/DL-Simplified/blob/main/Children%20vs%20Adults%20Classification%20using%20DL/Model/README.md</br>
:red_circle: **README Template** : https://github.com/abhisheks008/DL-Simplified/blob/main/.github/readme_template.md

***********************************************************************
:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include issue number along with it.
- Follow Contributing Guidelines & Code of Conduct before start Contributing.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : 
- GitHub Profile Link : 
- Email ID :
- Participant ID (if applicable):
- Approach for this Project :
- What is your participant role? (Mention the Open Source program)

*************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by vanshikab52** [comment]
@abhisheks008 Kindly assign this issue to me. I will make the necessary changes for the README file.
Full name : Vanshika Bisht
GitHub Profile Link : https://github.com/vanshikab52
Email ID : vanshikabisht777@gmail.com
Participant ID (if applicable): NA
Approach for this Project : To enhance the project's README file using the given template and make it properly well documented and appealing.
What is your participant role? (Mention the Open Source program) : GSSoC'24 Contributor

**Comment by abhisheks008** [comment]
Issue assigned to you @vanshikab52. Go ahead!
