### ISSUE TITLE
[README Enhancement]: Chocolate Classification using DL

### ISSUE THREAD

**Issue by abhisheks008** [abhisheks008/DL-Simplified#526]
### Deep Learning Simplified Repository (Proposing new issue)
:red_circle: **Project Title** : README Enhancement: Chocolate Classification using DL</br>
:red_circle: **Aim** : The aim is to enhance the README file and make it eye pleasing, well documented using the given README template.</br>
:red_circle: **README to be enhanced** : https://github.com/abhisheks008/DL-Simplified/blob/main/Chocolate%20Classification%20using%20DL/README.md</br>
:red_circle: **README Template** : https://github.com/abhisheks008/DL-Simplified/blob/main/.github/readme_template.md

***********************************************************************
:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include issue number along with it.
- Follow Contributing Guidelines & Code of Conduct before start Contributing.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : 
- GitHub Profile Link : 
- Email ID :
- Participant ID (if applicable):
- Approach for this Project :
- What is your participant role? (Mention the Open Source program)

*************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by mahi13singh2004** [comment]
Kindly assign this issue to me. Would like to work on it. Its a good first issue.
Full Name: Mahi Singh
GitHub Profile Link :https://github.com/mahi13singh2004
Email ID :mahi13singh2004@gmail.com
Participant ID (if applicable):
Approach for this Project : Would make this eye pleasing, Currently it looks very dull. Would add some emojis and mention tasks and aim in points. Would make it look as good as possible!
What is your participant role? (Mention the Open Source program): GSSOC'24

**Comment by mahi13singh2004** [comment]
@abhisheks008

**Comment by abhisheks008** [comment]
Hi @mahi13singh2004 issue assigned to you. Please follow the README template already mentioned in the issue template and you can also improvise on your own.

**Comment by mahi13singh2004** [comment]
> Hi @mahi13singh2004 issue assigned to you. Please follow the README template already mentioned in the issue template and you can also improvise on your own.

Thank you very much sir @abhisheks008 . i wanted to know about if any deadline is there? will it be okay if i complete till 6pm (IST) or please do mention if any deadline!

**Comment by abhisheks008** [comment]
> > Hi @mahi13singh2004 issue assigned to you. Please follow the README template already mentioned in the issue template and you can also improvise on your own.
> 
> Thank you very much sir @abhisheks008 . i wanted to know about if any deadline is there? will it be okay if i complete till 6pm (IST) or please do mention if any deadline!

Take your time, no need to hurry. Try to finish this issue within 4-5 days.

**Comment by mahi13singh2004** [comment]
> > > Hi @mahi13singh2004 issue assigned to you. Please follow the README template already mentioned in the issue template and you can also improvise on your own.
> > 
> > 
> > Thank you very much sir @abhisheks008 . i wanted to know about if any deadline is there? will it be okay if i complete till 6pm (IST) or please do mention if any deadline!
> 
> Take your time, no need to hurry. Try to finish this issue within 4-5 days.

Got it! Thanks!
