### ISSUE TITLE
[README Enhancement]: Colour Detection using DL

### ISSUE THREAD

**Issue by abhisheks008** [abhisheks008/DL-Simplified#527]
### Deep Learning Simplified Repository (Proposing new issue)
:red_circle: **Project Title** : README Enhancement: Colour Detection using DL</br>
:red_circle: **Aim** : The aim is to enhance the README file and make it eye pleasing, well documented using the given README template.</br>
:red_circle: **README to be enhanced** : https://github.com/abhisheks008/DL-Simplified/blob/main/Colour%20Detection%20using%20DL/README.md</br>
:red_circle: **README Template** : https://github.com/abhisheks008/DL-Simplified/blob/main/.github/readme_template.md

***********************************************************************
:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include issue number along with it.
- Follow Contributing Guidelines & Code of Conduct before start Contributing.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : 
- GitHub Profile Link : 
- Email ID :
- Participant ID (if applicable):
- Approach for this Project :
- What is your participant role? (Mention the Open Source program)

*************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by jahnvisahni31** [comment]
Full name : jahnvi sahni
GitHub Profile Link :  https://github.com/jahnvisahni31
Email ID : jahnvisahni98@gmail.com
Participant ID (if applicable):
Approach for this Project :  making the readme attractive
What is your participant role? (Mention the Open Source program) : contributor in gssoc
i want to contribute to this

**Comment by jahnvisahni31** [comment]
@abhisheks008

**Comment by jahnvisahni31** [comment]
Okay sorry for that i will do the requested changes first
