### ISSUE TITLE
[README Enhancement]: Concrete Compressive Strength Prediction Using Deep Learning

### ISSUE THREAD

**Issue by abhisheks008** [abhisheks008/DL-Simplified#528]
### Deep Learning Simplified Repository (Proposing new issue)
:red_circle: **Project Title** : README Enhancement: Concrete Compressive Strength Prediction Using Deep Learning</br>
:red_circle: **Aim** : The aim is to enhance the README file and make it eye pleasing, well documented using the given README template.</br>
:red_circle: **README to be enhanced** : https://github.com/abhisheks008/DL-Simplified/blob/main/Concrete%20Compressive%20Strength/Models/Readme.Md</br>
:red_circle: **README Template** : https://github.com/abhisheks008/DL-Simplified/blob/main/.github/readme_template.md

***********************************************************************
:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include issue number along with it.
- Follow Contributing Guidelines & Code of Conduct before start Contributing.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : 
- GitHub Profile Link : 
- Email ID :
- Participant ID (if applicable):
- Approach for this Project :
- What is your participant role? (Mention the Open Source program)

*************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by mahi13singh2004** [comment]
Kindly assign this issue to me. @abhisheks008  .Would like to work on it. Its a good first issue.
Full Name: Mahi Singh
GitHub Profile Link :https://github.com/mahi13singh2004
Email ID :[mahi13singh2004@gmail.com](mailto:mahi13singh2004@gmail.com)
Participant ID (if applicable): NA
Approach for this Project : Deep learning simplied repository Would make this eye pleasing, Currently it looks very dull. Would add some emojis and mention tasks and aim in points. Would make it look as good as possible!
What is your participant role? (Mention the Open Source program): GSSOC'24

**Comment by abhisheks008** [comment]
Hi @mahi13singh2004 it's better to work on one issue at a time.

**Comment by Shravya016** [comment]
please assign this issue to me under gssoc'24

Full name : Shravya pamu
GitHub Profile Link :https://github.com/Shravya016
Email ID :ss9599@srmist.edu.in
Participant ID (if applicable):NA
Approach for this Project : I want to enhance this project according to the template provided and make it easier to read for the user by adding points in it and more eye pleasing
What is your participant role? (Mention the Open Source program) GSSOC'24 contributor

**Comment by iamanolive** [comment]
hi @abhisheks008 i'd love to work on this issue if it's still available!
Full name : Anoushka Mahajan
GitHub Profile Link : https://github.com/iamanolive
Email ID : [olive.coding.xyz@gmail.com](mailto:olive.coding.xyz@gmail.com)
Participant ID (if applicable): N/A
Approach for this Project :

1. add styling to headings

2. use emojis to make it more colorful

3. seperate the different sections of the document

4. add bullet points wherever applicable to make the document more readable

What is your participant role? : GSSoC'24 Contributor

**Comment by abhisheks008** [comment]
Assigned to @Shravya016

**Comment by iamanolive** [comment]
> Assigned to @Shravya016

@abhisheks008 are there any other beginner-friendly issues that i can work on? all the ones i can find have been assigned already.

**Comment by abhisheks008** [comment]
Hi @iamanolive you can go through the existing projects' README files, if you find something is not correct there you can create an issue on that. I think doing documentation is a `good first issue` tagged issue.

**Comment by iamanolive** [comment]
> Hi @iamanolive you can go through the existing projects' README files, if you find something is not correct there you can create an issue on that. I think doing documentation is a `good first issue` tagged issue.

will do! thanks so much @abhisheks008
