### ISSUE TITLE
[Model Enhancement]: Colour Detection using DL

### ISSUE THREAD

**Issue by Arihant-Bhandari** [abhisheks008/DL-Simplified#529]
### Deep Learning Simplified Repository (Proposing new issue)
:red_circle: **Project Title** : Colour Detection using DL</br>
:red_circle: **Aim** : trying out a new custom CNN for the project</br>
:red_circle: **Dataset** :[ ](https://www.kaggle.com/datasets/adikurniawan/color-dataset-for-color-recognition)</br>
:red_circle: **Approach** : will try out creating a new custom built CNN model beac use i noticed how both train and val accuracy were bound at 0.9 accuracy. if the work ends up satisfactory i will be issuing a PR for the same, and if not, close this issue. I wiill be creating a new colour_detection.ipynb file so as to not affect the original copy of the code since it is a great implementation, and if need be changes can be transported over to the file on the PA end.

**********************************************************************************
### 📍 **Follow the Guidelines to Contribute in the Project :**
* You need to create a separate folder named as the Project Title.
* Inside that folder, there will be four main components.
   * Images - To store the required images.
   * Dataset - To store the dataset or, information/source about the dataset.
   * Model - To store the machine learning model you've created using the dataset.
   * `requirements.txt` - This file will contain the required packages/libraries to run the project in other machines.
* Inside the `Model` folder, the `README.md` file must be filled up properly, with proper visualizations and conclusions.

***********************************************************************
:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include issue number along with it.
- Follow Contributing Guidelines & Code of Conduct before start Contributing.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Arihant Bhandari
- GitHub Profile Link : https://github.com/Arihant-Bhandari
- Email ID : arihant.bhandari.2004@gmail.com
- Participant ID (if applicable): discord ID: Arihant-Bhandari (eternal_insight)
- Approach for this Project : creating a new CNN under a new file
- What is your participant role? (Mention the Open Source program)
 aprticipating as a Contributor under GSSoC 2024
*************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by abhisheks008** [comment]
Is it kind of an enhancement of the existing project? @Arihant-Bhandari

**Comment by Arihant-Bhandari** [comment]
Yes @abhisheks008 it would be an enhancement to the existing project. I thought of it as an experimental apprroach , seeing that the validation and training accuracy were both getting capped at 90%.

If I can enhance the existing project I will start a PR, and if I couldn't , I will close this issue.

The existing code is well written so I didn't want to intrude on the original , and hence am suggesting a new file with my code so that you can compare and decide what to keep , maybe even both.

**Comment by abhisheks008** [comment]
You can go ahead with it. Issue assigned to you @Arihant-Bhandari

**Comment by abhisheks008** [comment]
I have updated the issue title for better understanding, please make sure that the issue title will remain same as the pull request title.
