### ISSUE TITLE
fixing typos in the README.md file

### ISSUE THREAD

**Issue by iamanolive** [abhisheks008/DL-Simplified#531]
### Deep Learning Simplified Repository (Proposing new issue)
:red_circle: **Project Title** : fixing typos in the README.md file </br>
:red_circle: **Aim** : To fix grammatical, sentence and typing errors in the readme file of the project </br>
:red_circle: **README to be enhanced** : 
1. The line "composed of multiple processing layers to learn representations of data with multiple levels of abstraction" needs to be changed to "composed of multiple processing layers to learn **from** representations of data with multiple levels of abstraction". basically, a "from" needs to be added after "learn".
2. "It’s on hype nowadays" has a weird sentence structure, and I'd like to change it to "It's a very hyped topic nowadays"
3. Replace "in" with "into" in the line "deep learning and machine learning came **in** the picture."
4. Change "If the Dataset is not being able to uploaded in this folder due to the large size" to "If you are unable to upload the dataset into this folder due to it's large size"
5. Delete **there** in "Check out the existing issues present **there** in the Issues section."
6. Change "Comment out in the issue, you wanna work on." to "Comment on the issue you want to work on"
7. Change "criterias" to "criteria" in "If it satisfies all the criterias, your PR will be merged and your contributions will be counted." Criteria is the plural of criterion.
8. Change "Here are few articles" to "Here are a few articles"
9. In the line "start contributing **in** open source projects", change "in" to "to".
</br>
:red_circle: **README Template** : https://github.com/abhisheks008/DL-Simplified/blob/main/.github/readme_template.md

***********************************************************************
:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include issue number along with it.
- Follow Contributing Guidelines & Code of Conduct before start Contributing.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Anoushka Mahajan
- GitHub Profile Link : https://github.com/iamanolive
- Email ID : olive.coding.xyz@gmail.com
- Participant ID (if applicable): N/A
- Approach for this Project : 
1. The line "composed of multiple processing layers to learn representations of data with multiple levels of abstraction" needs to be changed to "composed of multiple processing layers to learn **from** representations of data with multiple levels of abstraction". basically, a "from" needs to be added after "learn".
2. "It’s on hype nowadays" has a weird sentence structure, and I'd like to change it to "It's a very hyped topic nowadays"
3. Replace "in" with "into" in the line "deep learning and machine learning came **in** the picture."
4. Change "If the Dataset is not being able to uploaded in this folder due to the large size" to "If you are unable to upload the dataset into this folder due to it's large size"
5. Delete **there** in "Check out the existing issues present **there** in the Issues section."
6. Change "Comment out in the issue, you wanna work on." to "Comment on the issue you want to work on"
7. Change "criterias" to "criteria" in "If it satisfies all the criterias, your PR will be merged and your contributions will be counted." Criteria is the plural of criterion.
8. Change "Here are few articles" to "Here are a few articles"
9. In the line "start contributing **in** open source projects", change "in" to "to".
- What is your participant role? : GSSoC'24 Contributor

*************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by iamanolive** [comment]
Full name : Anoushka Mahajan
GitHub Profile Link : https://github.com/iamanolive
Email ID : [olive.coding.xyz@gmail.com](mailto:olive.coding.xyz@gmail.com)
Participant ID (if applicable): N/A
Approach for this Project :
The line "composed of multiple processing layers to learn representations of data with multiple levels of abstraction" needs to be changed to "composed of multiple processing layers to learn from representations of data with multiple levels of abstraction". basically, a "from" needs to be added after "learn".
"It’s on hype nowadays" has a weird sentence structure, and I'd like to change it to "It's a very hyped topic nowadays"
Replace "in" with "into" in the line "deep learning and machine learning came in the picture."
Change "If the Dataset is not being able to uploaded in this folder due to the large size" to "If you are unable to upload the dataset into this folder due to it's large size"
Delete there in "Check out the existing issues present there in the Issues section."
Change "Comment out in the issue, you wanna work on." to "Comment on the issue you want to work on"
Change "criterias" to "criteria" in "If it satisfies all the criterias, your PR will be merged and your contributions will be counted." Criteria is the plural of criterion.
Change "Here are few articles" to "Here are a few articles"
In the line "start contributing in open source projects", change "in" to "to".
What is your participant role? : GSSoC'24 Contributor

**Comment by abhisheks008** [comment]
Hi @iamanolive which README file you wanna correct?

**Comment by iamanolive** [comment]
> Hi @iamanolive which README file you wanna correct?

https://github.com/abhisheks008/DL-Simplified/blob/main/README.md

**Comment by abhisheks008** [comment]
README enhancement was recently done by a contributor. You can check the
updated one.

**Comment by iamanolive** [comment]
Oh im so sorry, the README file was still on the old version when i started typing up this issue.

My 1st, 2nd, 5th and 6th points still apply though.

**Comment by abhisheks008** [comment]
Ummmm, I'll prefer not to go ahead with this as the README is just got updated. If you find any README issues in any of the existing project folders, you can create a new issue then.

Closing this issue.

**Comment by iamanolive** [comment]
@abhisheks008 they're pretty valid issues though. i spent over an hour working on it.
