### ISSUE TITLE
[README Enhancement]: AI Generated Fruits and Real Fruits Classification using Image Processing

### ISSUE THREAD

**Issue by abhisheks008** [abhisheks008/DL-Simplified#536]
### Deep Learning Simplified Repository (Proposing new issue)
:red_circle: **Project Title** : [README Enhancement]: AI Generated Fruits and Real Fruits Classification using Image Processing</br>
:red_circle: **Aim** : The aim is to enhance the README file and make it eye pleasing, well documented using the given README template.</br>
:red_circle: **README to be enhanced** : https://github.com/abhisheks008/DL-Simplified/blob/main/AI%20Generated%20Fruits%20and%20Real%20Fruits%20Classification%20using%20Image%20Processing/Model/readme.md</br>
:red_circle: **README Template** : https://github.com/abhisheks008/DL-Simplified/blob/main/.github/readme_template.md

***********************************************************************
:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include issue number along with it.
- Follow Contributing Guidelines & Code of Conduct before start Contributing.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : 
- GitHub Profile Link : 
- Email ID :
- Participant ID (if applicable):
- Approach for this Project :
- What is your participant role? (Mention the Open Source program)

*************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by abhisheks008** [comment]
Hi @iamanolive assigning this issue to you. Check out the README template and enhance the existing README into an eye-pleasing one. All the best!

**Comment by iamanolive** [comment]
> Hi @iamanolive assigning this issue to you. Check out the README template and enhance the existing README into an eye-pleasing one. All the best!

thank you so much!!

**Comment by iamanolive** [comment]
hi @abhisheks008 i just submitted a pull request with the necessary changes.
