### ISSUE TITLE
[Feature Addition]: Web Application for Age and Sex Prediction

### ISSUE THREAD

**Issue by abhisheks008** [abhisheks008/DL-Simplified#538]
### Deep Learning Simplified Repository (Proposing new issue)
:red_circle: **Project Title** : [Feature Addition]: Web Application for Age and Sex Prediction</br>
:red_circle: **Aim** : **The aim is to create a web application with the best accuracy scored existing model present /developed in the Model folder of the project.**</br>
:red_circle: **Dataset** : N/A</br>
:red_circle: **Approach** : Try to create a Flask/React app.

**********************************************************************************
### 📍 **Follow the Guidelines to Contribute in the Project :**
* You need to create a separate folder named as the Project Title.
* Inside that folder, there will be four main components.
   * Images - To store the required images.
   * Dataset - To store the dataset or, information/source about the dataset.
   * Model - To store the machine learning model you've created using the dataset.
   * `requirements.txt` - This file will contain the required packages/libraries to run the project in other machines.
* Inside the `Model` folder, the `README.md` file must be filled up properly, with proper visualizations and conclusions.

***********************************************************************
:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include issue number along with it.
- Follow Contributing Guidelines & Code of Conduct before start Contributing.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : 
- GitHub Profile Link : 
- Email ID :
- Participant ID (if applicable):
- Approach for this Project :
- What is your participant role? (Mention the Open Source program)

*************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by theiturhs** [comment]
@abhisheks008 

I would like to work on this issue. I have worked with Django and Gradio as well. I am familiar with Flask also. I do have uploaded a Django project on my GitHub Repository. You can visit [here](https://github.com/theiturhs/Online-Health-Prediction-using-Django).

Find the details:

Name: Shruti Shrivastava
GitHub Profile: [GitHub](https://github.com/theiturhs)
Email Id: shrutishrivastava22ss@gmail.com
Participant Role: GSSOC'24

Approch:

Model saving: Initially I will save the model in HDF5 format that can be used while user tried to predict. We don't need to train the model again and again.

Web Interface: Next a web interface will be created through which user can interact. For this I can either use Django or Flask. If Flask is needed, I will proceed with it.

For creating interactive templates, I will be using BootStrap for easy design and responsive web page.

Thank you

**Comment by abhisheks008** [comment]
Sure @theiturhs. As you can see that the existing project folder is containing the sub-folders as `Model`, `Dataset`, `Images`, you need to create a sub-folder as `Web App`. Inside the `Web App` folder, you need to put the file (Eg. `app.py`) and a `README` file. For the README file, please follow the [template](https://github.com/abhisheks008/DL-Simplified/blob/main/.github/web-app_readme_template.md).

After the deployment of the web app, make a video with the demonstration/working of the app and put that in the `Web App/README.md` file as per the template.

Here is the existing project, https://github.com/abhisheks008/DL-Simplified/tree/main/Age%20and%20Sex%20Prediction. **No need to create a separate project folder**.

I hope you understand what I'm trying to say.

**Comment by abhisheks008** [comment]
The project structure should be like this,
```
Project Dummy
|- Dataset
  |- dataset.csv
  |- README.md
|- Images
  |- img1.png
  |- img2.png
  |- img3.png
|- Model
  |- project_dummy.ipynb
  |- README.md
|- Web App
  |- app.py
  |- templates
  |- demo.mp4
  |- README.md
|- requirements.txt
```
Looking forward to hear from you @theiturhs

**Comment by theiturhs** [comment]
Yes I understood. Thanks for the clarification.

Thank you!

**Comment by abhisheks008** [comment]
Assigning this issue to you. You can start working on it @theiturhs

**Comment by abhisheks008** [comment]
Hi @theiturhs for your reference I have attached the link of the first web app implementation of a project in this repo, [Brain Tumor Detection](https://github.com/abhisheks008/DL-Simplified/tree/main/Brain%20Tumor%20Detection). I'm pretty sure this will help you understand the requirements.

**Comment by theiturhs** [comment]
Thanks @abhisheks008 for sharing this reference.
