### ISSUE TITLE
[Feature Addition]: Web Application for Alzheimers Detection

### ISSUE THREAD

**Issue by abhisheks008** [abhisheks008/DL-Simplified#539]
### Deep Learning Simplified Repository (Proposing new issue)
:red_circle: **Project Title** : [Feature Addition]: Web Application for Alzheimers Detection</br>
:red_circle: **Aim** : **The aim is to create a web application with the best accuracy scored existing model present /developed in the Model folder of the project.**</br>
:red_circle: **Dataset** : N/A</br>
:red_circle: **Approach** :  Try to create a Flask/React app.

**********************************************************************************
### 📍 **Follow the Guidelines to Contribute in the Project :**
* You need to create a separate folder named as the Project Title.
* Inside that folder, there will be four main components.
   * Images - To store the required images.
   * Dataset - To store the dataset or, information/source about the dataset.
   * Model - To store the machine learning model you've created using the dataset.
   * `requirements.txt` - This file will contain the required packages/libraries to run the project in other machines.
* Inside the `Model` folder, the `README.md` file must be filled up properly, with proper visualizations and conclusions.

***********************************************************************
:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include issue number along with it.
- Follow Contributing Guidelines & Code of Conduct before start Contributing.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : 
- GitHub Profile Link : 
- Email ID :
- Participant ID (if applicable):
- Approach for this Project :
- What is your participant role? (Mention the Open Source program)

*************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by aindree-2005** [comment]
Full name :  Aindree Chatterjee
GitHub Profile Link : aindree2005
Email ID : aindree2005@gmail.com
Participant ID (if applicable):
Approach for this Project : Trying a simple web app using Streamlit or Flask+ React
What is your participant role? `GSSOC 2024`
@abhisheks008 can I work on this?

**Comment by abhisheks008** [comment]
Sure @aindree-2005. As you can see that the existing project folder is containing the sub-folders as `Model`, `Dataset`, `Images`, you need to create a sub-folder as `Web App`. Inside the `Web App` folder, you need to put the file (Eg. `app.py`) and a `README` file. For the README file, please follow the [template](https://github.com/abhisheks008/DL-Simplified/blob/main/.github/web-app_readme_template.md).

After the deployment of the web app, make a video with the demonstration/working of the app and put that in the `Web App/README.md` file as per the template.

Here is the existing project, https://github.com/abhisheks008/DL-Simplified/tree/main/Alzheimers%20Detection. **No need to create a separate project folder**.

I hope you understand what I'm trying to say.

**Comment by abhisheks008** [comment]
The project structure should be like this,
```
Project Dummy
|- Dataset
  |- dataset.csv
  |- README.md
|- Images
  |- img1.png
  |- img2.png
  |- img3.png
|- Model
  |- project_dummy.ipynb
  |- README.md
|- Web App
  |- app.py
  |- templates
  |- demo.mp4
  |- README.md
|- requirements.txt
```

**Comment by abhisheks008** [comment]
Looking forward to hear from you @aindree-2005

**Comment by aindree-2005** [comment]
> The project structure should be like this,
> 
> ```
> Project Dummy
> |- Dataset
>   |- dataset.csv
>   |- README.md
> |- Images
>   |- img1.png
>   |- img2.png
>   |- img3.png
> |- Model
>   |- project_dummy.ipynb
>   |- README.md
> |- Web App
>   |- app.py
>   |- templates
>   |- demo.mp4
>   |- README.md
> |- requirements.txt
> ```

Yes understood the project structure! I will ask on discord about any doubts I have if I am stuck anywhere while working

**Comment by abhisheks008** [comment]
Sure assigning this issue to you @aindree-2005. All the best and you can start working on it.
