### ISSUE TITLE
[Feature Addition]: Web Application for American Sign Language Detection

### ISSUE THREAD

**Issue by abhisheks008** [abhisheks008/DL-Simplified#540]
### Deep Learning Simplified Repository (Proposing new issue)
:red_circle: **Project Title** : [Feature Addition]: Web Application for American Sign Language Detection</br>
:red_circle: **Aim** : **The aim is to create a web application with the best accuracy scored existing model present /developed in the Model folder of the project.**</br>
:red_circle: **Dataset** : N/A</br>
:red_circle: **Approach** : Try to create a Flask/React app.

**********************************************************************************
### 📍 **Follow the Guidelines to Contribute in the Project :**
* You need to create a separate folder named as the Project Title.
* Inside that folder, there will be four main components.
   * Images - To store the required images.
   * Dataset - To store the dataset or, information/source about the dataset.
   * Model - To store the machine learning model you've created using the dataset.
   * `requirements.txt` - This file will contain the required packages/libraries to run the project in other machines.
* Inside the `Model` folder, the `README.md` file must be filled up properly, with proper visualizations and conclusions.

***********************************************************************
:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include issue number along with it.
- Follow Contributing Guidelines & Code of Conduct before start Contributing.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : 
- GitHub Profile Link : 
- Email ID :
- Participant ID (if applicable):
- Approach for this Project :
- What is your participant role? (Mention the Open Source program)

*************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by RishitaChourey** [comment]
Full name :Rishita Chourey
GitHub Profile Link : https://github.com/RishitaChourey
Email ID : choureyrishita@gmail.com
Approach for this Project : Try to create a flask app for the american sign language model
What is your participant role? GSSoC'24 contributor

I would like to work on this.Please assign me this issue

**Comment by abhisheks008** [comment]
Cool. Make sure you use the existing project's model, dataset for implementing the web app as this an addition to the existing project structure. Here is the existing project, [American Sign Language Detection](https://github.com/abhisheks008/DL-Simplified/tree/main/American%20Sign%20Language%20Detection).

Follow this project structure,
```
Project Dummy
|- Dataset
  |- dataset.csv
  |- README.md
|- Images
  |- img1.png
  |- img2.png
  |- img3.png
|- Model
  |- project_dummy.ipynb
  |- README.md
|- Web App
  |- app.py
  |- templates
  |- demo.mp4
  |- README.md
|- requirements.txt
```

Here is a project which already deployed using the Web App, [Brain Tumor Detection](https://github.com/abhisheks008/DL-Simplified/tree/main/Brain%20Tumor%20Detection)

Looking forward to hearing from you @RishitaChourey

**Comment by Adhivp** [comment]
Full name : Adhithyan vp
GitHub Profile Link : Adhivp
Email ID : adhivp910@gmail.com
Participant ID (if applicable):
Approach for this Project : Will make a Flask app for the same, Will make a simple flask app to try out the model and will be easily deployable in any deployment platform
What is your participant role? (Mention the Open Source program) GSSoC'24 contributor

**Comment by abhisheks008** [comment]
> Cool. Make sure you use the existing project's model, dataset for implementing the web app as this an addition to the existing project structure. Here is the existing project, [American Sign Language Detection](https://github.com/abhisheks008/DL-Simplified/tree/main/American%20Sign%20Language%20Detection).
> 
> Follow this project structure,
> 
> ```
> Project Dummy
> |- Dataset
>   |- dataset.csv
>   |- README.md
> |- Images
>   |- img1.png
>   |- img2.png
>   |- img3.png
> |- Model
>   |- project_dummy.ipynb
>   |- README.md
> |- Web App
>   |- app.py
>   |- templates
>   |- demo.mp4
>   |- README.md
> |- requirements.txt
> ```
> 
> Here is a project which already deployed using the Web App, [Brain Tumor Detection](https://github.com/abhisheks008/DL-Simplified/tree/main/Brain%20Tumor%20Detection)
> 
> Looking forward to hearing from you @RishitaChourey

@Adhivp please go through the structure and requirements. Are you up for this?

**Comment by Adhivp** [comment]
Yeah ok

**Comment by Adhivp** [comment]
I feel like this is level 3 as I will be trying to deploy and also have to work with camera , what is your take on this @abhisheks008 ?

**Comment by abhisheks008** [comment]
Initially all the issues are being tagged as Lavel 2, after judging the quality of the pull request/contribution it can be upgraded to Level 3. No issues with that.

Assigning this issue to you @Adhivp

**Comment by Adhivp** [comment]
ok @abhisheks008

**Comment by Adhivp** [comment]
@abhisheks008 Should I make a image uploader kind of website , where we can upload image of the hand and then it will return the classification / should I make a live webcam where live predictions will come.

**Comment by abhisheks008** [comment]
> @abhisheks008 Should I make a image uploader kind of website , where we can upload image of the hand and then it will return the classification / should I make a live webcam where live predictions will come.

Yes a Flask app will be enough
