### ISSUE TITLE
[README Enhancement]: Age and Sex Prediction

### ISSUE THREAD

**Issue by iamanolive** [abhisheks008/DL-Simplified#543]
### Deep Learning Simplified Repository (Proposing new issue)
:red_circle: **Project Title** : Updating the README.md file of the "Age and Sex Prediction" project
:red_circle: **Aim** : The aim is to enhance the README file and make it eye pleasing, well documented using the given README template.</br>
:red_circle: **README to be enhanced** : https://github.com/abhisheks008/DL-Simplified/tree/main/Age%20and%20Sex%20Prediction/Model</br>
:red_circle: **README Template** : https://github.com/abhisheks008/DL-Simplified/blob/main/.github/readme_template.md

***********************************************************************
:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include issue number along with it.
- Follow Contributing Guidelines & Code of Conduct before start Contributing.

***********************************************************************
Full name : Anoushka Mahajan
GitHub Profile Link : https://github.com/iamanolive
Email ID : [olive.coding.xyz@gmail.com](mailto:olive.coding.xyz@gmail.com)
Participant ID (if applicable): N/A
Approach for this Project : Update the README file to match the provided template, fix typos and grammar errors, and add emojis to the document to make it more engaging.
What is your participant role? : GSSoC'24 Contributor

*************************************************************

**Comment by abhisheks008** [comment]
Issue assigned to you @iamanolive

**Comment by Cralsic123** [comment]
@abhisheks008 If its possible, can I be assigned to this too?

**Comment by abhisheks008** [comment]
Sorry @Cralsic123 this issue is already assigned. You can check out other issues present here in this repo.

**Comment by iamanolive** [comment]
> Issue assigned to you @iamanolive

thank you @abhisheks008

**Comment by iamanolive** [comment]
submitted a pull request @abhisheks008
