### ISSUE TITLE
[Feature Addition]: Web Application for Anti Spoofing Project

### ISSUE THREAD

**Issue by abhisheks008** [abhisheks008/DL-Simplified#544]
### Deep Learning Simplified Repository (Proposing new issue)
:red_circle: **Project Title** : [Feature Addition]: Web Application for Anti Spoofing Project</br>
:red_circle: **Aim** : **The aim is to create a web application with the best accuracy scored existing model present /developed in the Model folder of the project.**</br>
:red_circle: **Dataset** : N/A</br>
:red_circle: **Approach** :  Try to create a Flask/React app.</br>
:red_circle: **Reference Project for Implementation** : [**Brain Tumor Detection**](https://github.com/abhisheks008/DL-Simplified/tree/main/Brain%20Tumor%20Detection)

**********************************************************************************
### 📍 **Follow the Guidelines to Contribute in the Project :**
* You need to create a separate folder named as the Project Title.
* Inside that folder, there will be four main components.
   * Images - To store the required images.
   * Dataset - To store the dataset or, information/source about the dataset.
   * Model - To store the machine learning model you've created using the dataset.
   * `requirements.txt` - This file will contain the required packages/libraries to run the project in other machines.
* Inside the `Model` folder, the `README.md` file must be filled up properly, with proper visualizations and conclusions.

***********************************************************************
:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include issue number along with it.
- Follow Contributing Guidelines & Code of Conduct before start Contributing.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : 
- GitHub Profile Link : 
- Email ID :
- Participant ID (if applicable):
- Approach for this Project :
- What is your participant role? (Mention the Open Source program)

*************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by PABITRA34** [comment]
Full name : Pabitra Kumar Bera 
GitHub Profile Link : https://github.com/PABITRA34
Email ID : pabitrabera34@gmail.com
Participant ID (if applicable):
Approach for this Project : Will try to make  web app using Streamlit or Flask+ React
What is your participant role? GSSOC 2024
@abhisheks008 sir please assign this task to me

**Comment by abhisheks008** [comment]
Cool. Make sure you use the existing project's model, dataset for implementing the web app as this an addition to the existing project structure. Here is the existing project, [Anti Spoofing Project using DL](https://github.com/abhisheks008/DL-Simplified/tree/main/Anti%20Spoofing%20Project%20using%20DL).

Follow this project structure,
```
Project Dummy
|- Dataset
  |- dataset.csv
  |- README.md
|- Images
  |- img1.png
  |- img2.png
  |- img3.png
|- Model
  |- project_dummy.ipynb
  |- README.md
|- Web App
  |- app.py
  |- templates
  |- demo.mp4
  |- README.md
|- requirements.txt
```

Here is a project which already deployed using the Web App, [Brain Tumor Detection](https://github.com/abhisheks008/DL-Simplified/tree/main/Brain%20Tumor%20Detection)

Looking forward to hearing from you @PABITRA34

**Comment by PABITRA34** [comment]
@abhisheks008 Ok sir , I will follow this project structure
Please assign this project to me  under  GSSOC 2024 , so that i can start working on it

Thank You

**Comment by abhisheks008** [comment]
Sure. Assigned to you @PABITRA34

**Comment by PABITRA34** [comment]
@abhisheks008 Ok sir  , Thank You

**Comment by abhisheks008** [comment]
> Cool. Make sure you use the existing project's model, dataset for implementing the web app as this an addition to the existing project structure. Here is the existing project, [Anti Spoofing Project using DL](https://github.com/abhisheks008/DL-Simplified/tree/main/Anti%20Spoofing%20Project%20using%20DL).
> 
> Follow this project structure,
> 
> ```
> Project Dummy
> |- Dataset
>   |- dataset.csv
>   |- README.md
> |- Images
>   |- img1.png
>   |- img2.png
>   |- img3.png
> |- Model
>   |- project_dummy.ipynb
>   |- README.md
> |- Web App
>   |- app.py
>   |- templates
>   |- demo.mp4
>   |- README.md
> |- requirements.txt
> ```
> 
> Here is a project which already deployed using the Web App, [Brain Tumor Detection](https://github.com/abhisheks008/DL-Simplified/tree/main/Brain%20Tumor%20Detection)
> 
> Looking forward to hearing from you @PABITRA34

I have informed you about the approach earlier too.
