### ISSUE TITLE
[Feature Addition]: Web App for Dog Breeds Classification

### ISSUE THREAD

**Issue by abhisheks008** [abhisheks008/DL-Simplified#551]
### :red_circle: **Reference Project for Implementation** : [**Brain Tumor Detection**](https://github.com/abhisheks008/DL-Simplified/tree/main/Brain%20Tumor%20Detection)

**********************************************************************************
### 📍 **Follow the Guidelines to Contribute in the Project :**
* You need to create a separate folder named as the Project Title.
* Inside that folder, there will be four main components.
   * Images - To store the required images.
   * Dataset - To store the dataset or, information/source about the dataset.
   * Model - To store the machine learning model you've created using the dataset.
   * `requirements.txt` - This file will contain the required packages/libraries to run the project in other machines.
* Inside the `Model` folder, the `README.md` file must be filled up properly, with proper visualizations and conclusions.

***********************************************************************
:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include issue number along with it.
- Follow Contributing Guidelines & Code of Conduct before start Contributing.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : 
- GitHub Profile Link : 
- Email ID :
- Participant ID (if applicable):
- Approach for this Project :
- What is your participant role? (Mention the Open Source program)

*************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Himanshu8850** [comment]
hi @abhisheks008 , please assign this issue to me.
Full name : Himanshu Choudhary
GitHub Profile Link : https://github.com/Himanshu8850
Email ID : 1130himanshu@gmaill.com
Participant ID (if applicable):
Approach for this Project : I will be making a simple react based web app with functionality of loading images and sending them to the model and getting the predicted otuput diplayed on the app.
What is your participant role? I am participating  as contributor through gssoc' 24.

**Comment by abhisheks008** [comment]
Cool. Make sure you use the existing project's model, dataset for implementing the web app as this an addition to the existing project structure. Here is the existing project, [Dog Breeds Classification](https://github.com/abhisheks008/DL-Simplified/tree/main/Dog%20Breeds%20Classification).

Follow this project structure,
```
Project Dummy
|- Dataset
  |- dataset.csv
  |- README.md
|- Images
  |- img1.png
  |- img2.png
  |- img3.png
|- Model
  |- project_dummy.ipynb
  |- README.md
|- Web App
  |- app.py
  |- templates
  |- demo.mp4
  |- README.md
|- requirements.txt
```

Here is a project which already deployed using the Web App, [Brain Tumor Detection](https://github.com/abhisheks008/DL-Simplified/tree/main/Brain%20Tumor%20Detection)

Looking forward to hearing from you @Himanshu8850

**Comment by Himanshu8850** [comment]
Alright,  @abhisheks008 
I have seen the Brain tumor detection app.
So, I will be keeping minimalistic design and will add some extra dog breed info to be displayed on upload.

**Comment by abhisheks008** [comment]
Cool. Looking forward to have another web application for this repo. Assigned to you @Himanshu8850 

Hi @saikrishna823 thanks for your interest, but talks were already there with the assigned contributor. You can check out other issues present here in this repo.

**Comment by saikrishna823** [comment]
Okay

**Comment by Himanshu8850** [comment]
[Uploading final.webm…]()
hey @abhisheks008 ,does this look good enough.

**Comment by Himanshu8850** [comment]
[final.webm](https://github.com/abhisheks008/DL-Simplified/assets/128601673/99eac948-d19f-4897-91a2-aa9a3e426cce)

**Comment by abhisheks008** [comment]
I liked it. Really appreciated your efforts.
