### ISSUE TITLE
[Project Addition]: Breast Cancer Detection using DL - with Web App

### ISSUE THREAD

**Issue by TheNaiveSamosa** [abhisheks008/DL-Simplified#554]
### Deep Learning Simplified Repository (Proposing new issue)
:red_circle: **Project Title** : Breast Cancer Detection </br>
:red_circle: **Aim** : To develop a model for detecting breast cancer using deep learning techniques. </br>
:red_circle: **Dataset** : CSV dataset with numerical and categorical features related to breast cancer. </br>
:red_circle: **Approach** : Implement Neural Network for Regression using a CSV dataset with numerical features, Neural Network for Binary Classification using a CSV dataset with categorical and numerical features, and convert a logistic regression model into a deeper neural network with 7 layers. Compare the performance of these models to find the best-fitted algorithm by checking the accuracy scores. Also, perform exploratory data analysis before creating any model.

**********************************************************************************
### 📍 **Follow the Guidelines to Contribute to the Project :**
* You need to create a separate folder named as the Project Title.
* Inside that folder, there will be four main components.
   * Images - To store the required images.
   * Dataset - To store the dataset or, information/source about the dataset.
   * Model - To store the machine learning model you've created using the dataset.
   * `requirements.txt` - This file will contain the required packages/libraries to run the project in other machines.
* Inside the `Model` folder, the `README.md` file must be filled up properly, with proper visualizations and conclusions.

***********************************************************************
:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include issue number along with it.
- Follow Contributing Guidelines & Code of Conduct before start Contributing.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Aditya Khamitkar
- GitHub Profile Link : [GitHub](https://github.com/TheNaiveSamosa)
- Email ID : thenaivesamosa@gmail.com
- Approach for this Project : Implement Neural Network for Regression, Neural Network for Binary Classification, and convert a logistic regression model into a deeper neural network with 7 layers. Compare the performance of these models.
- What is your participant role? (Mention the Open Source program): Contributor at GSSoC 2024

*************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open-source journey ahead. 😎

**Comment by abhisheks008** [comment]
Hi @TheNaiveSamosa thanks for creating the new issue. Are you able to find out a dataset which contains images, so that you can process the images to get the proper prediction. It'll combine the CNN models too.

**Comment by Vis1hal** [comment]
please assign this issue to me , I have already made some project on CNN model based project

**Comment by TheNaiveSamosa** [comment]
@abhisheks008 I have images of Breast Histopathology but the thing is its maximum F1 is possible is 0.85. I did a model on that. Will try to increase accuracy this time. Please do assign it to me.

**Comment by abhisheks008** [comment]
> @abhisheks008 I have images of Breast Histopathology but the thing is its maximum F1 is possible is 0.85. I did a model on that. Will try to increase accuracy this time. And will also try to find out if I can work on the model with Mammogram or Ultra Sound Images. Please do assign it to me.

Cool, looks good to me. Assigned to you @TheNaiveSamosa.

Hi @Vis1hal thanks for showing up here. This issue is raised by the contributor that's why I assigned him this one. The issues which are raised by the username `abhisheks008`, are open for all, you can find them in the issues section by the `Status: Up for Grabs`.

**Comment by TheNaiveSamosa** [comment]
I also adding a web app to this project. Similar to previous one.

**Comment by abhisheks008** [comment]
> I also adding a web app to this project. Similar to previous one.

Cool! That's good, really appreciated your efforts.

**Comment by TheNaiveSamosa** [comment]
Can I get a few more days for this. Still working on the code. There isn't any time limit for each issue right?

**Comment by abhisheks008** [comment]
> Can I get a few more days for this. Still working on the code. There isn't any time limit for each issue right?

No issues with that, take your time.

**Comment by TheNaiveSamosa** [comment]
Hey. I'm almost done with the project. I will push the code soon. Could you once again recheck the level of this issue. I think the project was at a good level and time taking too.

**Comment by abhisheks008** [comment]
> Hey. I'm almost done with the project. I will push the code soon. Could you once again recheck the level of this issue. I think the project was at a good level and time taking too.

Create your PR and let us review the code. Depending on the quality of the codes issues can be re-lablled.

**Comment by TheNaiveSamosa** [comment]
Yes, PR has been created.
