### ISSUE TITLE
GitHub Automatic Greeting Bot

### ISSUE THREAD

**Issue by Hemu21** [abhisheks008/DL-Simplified#556]
As it is a Open source project. Everyone come and create Issues in this repo. Currently This repo does not have any greeting bot when issue is created. I can create a Greeting Bot for this repo.

**Comment by Hemu21** [comment]
@abhisheks008  can you please assign me this issue.

**Comment by abhisheks008** [comment]
Hi @Hemu21 in the past I have added 2-3 bots in this repo just like the one you are suggesting, but found them unnecessary in many occassions. That's why I removed them and left with `PR Welcome` bot only.

If you have any other suggestions you can drop them here. Thanks for your interest.

**Comment by abhisheks008** [comment]
Hi @Hemu21 can you create a GitHub bot, which will automatically fetch the PRs based on the labels and update a leaderboard solely for Deep Learning Simplified. Currently I am using an excel sheet where I manually put the PR numbers and contributors' names, so that I can have a clear picture of the contributions made in this repo.

**Comment by Hemu21** [comment]
> Hi @Hemu21 can you create a GitHub bot, which will automatically fetch the PRs based on the labels and update a leaderboard solely for Deep Learning Simplified. Currently I am using an excel sheet where I manually put the PR numbers and contributors' names, so that I can have a clear picture of the contributions made in this repo.
> 
> Leaderboard should be like this,
> 
> Name	Email ID	GitHub ID	Number of PRs merged	Total Points Gained
> XYZ	[xyz@gmail.com](mailto:xyz@gmail.com)	@xyzgithub	6	80

@abhisheks008 sorry I doesn't have much idea the thing you asked. I can't able to do it

**Comment by abhisheks008** [comment]
Cool no issues.
