### ISSUE TITLE
[README Enhancement]: Amazon Reviews Sentiment Analysis

### ISSUE THREAD

**Issue by iamanolive** [abhisheks008/DL-Simplified#563]
### Deep Learning Simplified Repository (Proposing new issue)
:red_circle: **Project Title** : Updating the README.md file of the "Amazon Reviews Sentiment Analysis" project</br>
:red_circle: **Aim** : The aim is to enhance the README file and make it eye pleasing, well documented using the given README template.</br>
:red_circle: **README to be enhanced** : https://github.com/abhisheks008/DL-Simplified/tree/main/Amazon%20Reviews%20Sentiment%20Analysis/Model</br>
:red_circle: **README Template** : https://github.com/abhisheks008/DL-Simplified/blob/main/.github/readme_template.md

***********************************************************************
:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include issue number along with it.
- Follow Contributing Guidelines & Code of Conduct before start Contributing.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Anoushka Mahajan
- GitHub Profile Link : https://github.com/iamanolive
- Email ID : [olive.coding.xyz@gmail.com](mailto:olive.coding.xyz@gmail.com)
- Participant ID (if applicable): N/A
- Approach for this Project : Update the README file to match the provided template, fix typos and grammar errors, and add emojis to the document to make it more engaging.
- What is your participant role?: GSSoC'24 Contributor

*************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by iamanolive** [comment]
hi @abhisheks008 can i please be assigned this issue to work on?

**Comment by abhisheks008** [comment]
Hi @iamanolive no more README enhancement please. You have already done two enhancement like this, you can check out other development related issues present here in the issues section.
