### ISSUE TITLE
[Model Enhancement]: Leukaemia Classification using DL

### ISSUE THREAD

**Issue by Arihant-Bhandari** [abhisheks008/DL-Simplified#569]
### Deep Learning Simplified Repository (Proposing new issue)
:red_circle: **Project Title** : Leukaemia Classification using DL</br>
:red_circle: **Aim** : Enhancing CNN model with Attention</br>
:red_circle: **Dataset** : https://www.kaggle.com/datasets/andrewmvd/leukemia-classification</br>
:red_circle: **Approach** : Adding Attention mechanism on top of CNN, to focus the model on classifying better and pushing accuracy of the model as well as other metrics.

**********************************************************************************
### 📍 **Follow the Guidelines to Contribute in the Project :**
* You need to create a separate folder named as the Project Title.
* Inside that folder, there will be four main components.
   * Images - To store the required images.
   * Dataset - To store the dataset or, information/source about the dataset.
   * Model - To store the machine learning model you've created using the dataset.
   * `requirements.txt` - This file will contain the required packages/libraries to run the project in other machines.
* Inside the `Model` folder, the `README.md` file must be filled up properly, with proper visualizations and conclusions.

***********************************************************************
:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include issue number along with it.
- Follow Contributing Guidelines & Code of Conduct before start Contributing.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Arihant Bhandari
- GitHub Profile Link : Arihant-Bhandari https://github.com/Arihant-Bhandari
- Email ID : arihant.bhandari.2004@gmail.com
- Participant ID (if applicable): Arihant Bhandari (discord : eternal_insight)
- Approach for this Project : applying Attention to CNN model for boosting metrics.
- What is your participant role? (Mention the Open Source program)
GSSoC 2024 Contributor
*************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Arihant-Bhandari** [comment]
@abhisheks008 hi, i hope i can be assigned this issue since the last project's PR is on final stages. I am hoping to apply Attention on this as well, seeing how attention introduces probability into training, and wanted to get experience in dealing with projects handling situations with attention.

**Comment by abhisheks008** [comment]
Let the assigned project merged to this repo, then you can work on this. But not before that, as the code of conduct suggests, one issue at a time. @Arihant-Bhandari

**Comment by Arihant-Bhandari** [comment]
hi @abhisheks008 since the last project is merged, can i start working on this ?

**Comment by abhisheks008** [comment]
Yes you can go ahead. @Arihant-Bhandari
