### ISSUE TITLE
[README ENHANCEMENT]  Email Spam Classification

### ISSUE THREAD

**Issue by aindree-2005** [abhisheks008/DL-Simplified#576]
### Deep Learning Simplified Repository (Proposing new issue)
:red_circle: **Project Title** : </br>[README ENHANCEMENT]  Email Spam Classification

:red_circle: **Aim** : The aim is to enhance the README file and make it eye pleasing, well documented using the given README template.</br>
:red_circle: **README to be enhanced** : </br>https://github.com/abhisheks008/DL-Simplified/blob/main/Email%20Spam%20Classification/Models/Readme.md
:red_circle: **README Template** : https://github.com/abhisheks008/DL-Simplified/blob/main/.github/readme_template.md

***********************************************************************
:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include issue number along with it.
- Follow Contributing Guidelines & Code of Conduct before start Contributing.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name :  Aindree Chatterjee
- GitHub Profile Link : aindree2005
- Email ID : aindree2005@gmail.com
- Participant ID (if applicable):
- Approach for this Project : Readme Fix
- What is your participant role? (Mention the Open Source program)
`GSSOC 2024`
*************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by aindree-2005** [comment]
@abhisheks008 Can I work on this once the previous PR is accepted?

**Comment by abhisheks008** [comment]
Currently I am not assigning any contributor in the README enhancement issues as large number of contributors are just trying to fix this kind of minor issues instead of going to proper development.

I hope you understand my point. Closing this issue.

**Comment by aindree-2005** [comment]
> Currently I am not assigning any contributor in the README enhancement issues as large number of contributors are just trying to fix this kind of minor issues instead of going to proper development.
> 
> I hope you understand my point. Closing this issue.

Got it
