### ISSUE TITLE
Heartbeat Classification using ECG

### ISSUE THREAD

**Issue by abhisheks008** [abhisheks008/DL-Simplified#58]
### Deep Learning Simplified Repository (Proposing new issue)
:red_circle: **Project Title** : Heartbeat Classification using ECG</br>
:red_circle: **Aim** : Analyse the heartbeats from the given set of ECGs.</br>
:red_circle: **Dataset** : https://www.kaggle.com/datasets/shayanfazeli/heartbeat</br>
:red_circle: **Approach** : Try to use 3-4 algorithms to implement the models and compare all the algorithms to find out the best fitted algorithm for the model by checking the accuracy scores. Also do not forget to do a exploratory data analysis before creating any model.

**********************************************************************************
### 📍 **Follow the Guidelines to Contribute in the Project :**
* You need to create a separate folder named as the Project Title.
* Inside that folder, there will be four main components.
   * Images - To store the required images.
   * Dataset - To store the dataset or, information/source about the dataset.
   * Model - To store the machine learning model you've created using the dataset.
   * `requirements.txt` - This file will contain the required packages/libraries to run the project in other machines.
* Inside the `Model` folder, the `README.md` file must be filled up properly, with proper visualizations and conclusions.

***********************************************************************
:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include issue number along with it.
- Follow Contributing Guidelines & Code of Conduct before start Contributing.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : 
- GitHub Profile Link : 
- Email ID :
- Participant ID (if applicable):
- Approach for this Project :
- What is your participant role? (Mention the Open Source program)

*************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by KushagraTomar** [comment]
Heartbeat Classification using ECG #58
Full name : Kushagra Tomar
GitHub Profile Link :  https://github.com/KushagraTomar
Email ID :  01fe20bcs063@kletech.ac.in
Approach for this Project : Thinking of using CNN based model using TensorFlow

**Comment by Rushijaviya** [comment]
Assigned to @KushagraTomar. Happy contributing.

**Comment by KushagraTomar** [comment]
I'm not able to push the dataset in the repo it says size exceed 100mb limit
dataset size is approx 400mb what should i do

**Comment by abhisheks008** [comment]
You can add the link of the dataset in the `Dataset/README.md` file, stating that, you have used the dataset from this source.
@KushagraTomar

**Comment by KushagraTomar** [comment]
Hey,
I have completed the work. Have a look at it.
https://github.com/KushagraTomar/Heartbeat-Classification-using-ECG

**Comment by abhisheks008** [comment]
You have not pushed a pull request. You have added the project in your GitHub profile, you have to fork the repo and push the files there. After that you need to create a PR.

About your project, it looks pretty good. But in the jupyter notebook file the plots are not visible and the cells are not showing the outputs. Please take a look at them, it may be a glitch.

@KushagraTomar

**Comment by KushagraTomar** [comment]
This is new to me... Need ur help
