### ISSUE TITLE
[Project Addition] Handwritten Equation Solver using DL with Web App

### ISSUE THREAD

**Issue by Sgvkamalakar** [abhisheks008/DL-Simplified#580]
### Deep Learning Simplified Repository (Proposing new issue)
:red_circle: **Project Title**: Handwritten Equation Solver using DL
:red_circle: **Aim**: Develop a deep learning-based solver for recognizing and solving handwritten mathematical equations.
:red_circle: **Dataset**: https://www.kaggle.com/datasets/xainano/handwrittenmathsymbols/data
:red_circle: **Approach**: Try to use 3-4 algorithms to implement the models and compare all the algorithms to find out the best fitted algorithm for the model by checking the accuracy scores. Also do not forget to do a exploratory data analysis before creating any model.

**********************************************************************************
### 📍 **Follow the Guidelines to Contribute in the Project :**
* You need to create a separate folder named as the Project Title.
* Inside that folder, there will be four main components.
   * Images - To store the required images.
   * Dataset - To store the dataset or, information/source about the dataset.
   * Model - To store the machine learning model you've created using the dataset.
   * `requirements.txt` - This file will contain the required packages/libraries to run the project in other machines.
* Inside the `Model` folder, the `README.md` file must be filled up properly, with proper visualizations and conclusions.

***********************************************************************
:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include issue number along with it.
- Follow Contributing Guidelines & Code of Conduct before start Contributing.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name: S G V Kamalakar
- GitHub Profile Link: https://github.com/Sgvkamalakar
- Email ID:  sgvkamalakar@gmail.com
- Participant ID (if applicable):
- Approach for this Project:
- What is your participant role? (Mention the Open Source program): GSSOC '24

*************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by abhisheks008** [comment]
My suggestion would be to create a web app as well for this real time project @Sgvkamalakar

**Comment by Sgvkamalakar** [comment]
Hi @abhisheks008 
Please review the above issue template and assign the issue to me.

**My approach for the Project:**
I plan to use a CNN, RNN, and a hybrid CNN-RNN model. Additionally, I will experiment with the Vision Transformer model to evaluate its performance.

**Expected Outcome**:
The goal is to identify the most suitable model for the dataset and develop a `Streamlit` web application for a real-time handwritten equation solver.

**Comment by abhisheks008** [comment]
> Hi @abhisheks008 Please review the above issue template and assign the issue to me.
> 
> **My approach for the Project:** I plan to use a CNN, RNN, and a hybrid CNN-RNN model. Additionally, I will experiment with the Vision Transformer model to evaluate its performance.
> 
> **Expected Outcome**: The goal is to identify the most suitable model for the dataset and develop a `Streamlit` web application for a real-time handwritten equation solver.

If you can implement this, it could be one of those finest addition to this repo. Go ahead @Sgvkamalakar 
Also please follow the same project structure as you have in the previous contribution.

**Comment by Sgvkamalakar** [comment]
> > Hi @abhisheks008 Please review the above issue template and assign the issue to me.
> > **My approach for the Project:** I plan to use a CNN, RNN, and a hybrid CNN-RNN model. Additionally, I will experiment with the Vision Transformer model to evaluate its performance.
> > **Expected Outcome**: The goal is to identify the most suitable model for the dataset and develop a `Streamlit` web application for a real-time handwritten equation solver.
> 
> If you can implement this, it could be one of those finest addition to this repo. Go ahead @Sgvkamalakar Also please follow the same project structure as you have in the previous contribution.

Sure, noted. Thank you!

**Comment by Pranali3103** [comment]
If this issue still open ,can you please assign me this issue. @abhisheks008
