### ISSUE TITLE
[Feature Addition]: Web App for Artwork Image Recognition

### ISSUE THREAD

**Issue by abhisheks008** [abhisheks008/DL-Simplified#582]
### Deep Learning Simplified Repository (Proposing new issue)
:red_circle: **Project Title** : [Feature Addition]: Web App for Artwork Image Recognition</br>
:red_circle: **Aim** : The aim is to create a web application with the best accuracy scored existing model present/developed in the Model folder of the project. Here is the project folder - [Artwork Image Recognition](https://github.com/abhisheks008/DL-Simplified/tree/main/Artwork%20Image%20Recognition)</br>
:red_circle: **Dataset** : N/A</br>
:red_circle: **Approach** : Try to create a Flask/React app.</br>
### :red_circle: **Reference Project for Implementation** : [**Brain Tumor Detection**](https://github.com/abhisheks008/DL-Simplified/tree/main/Brain%20Tumor%20Detection)

**********************************************************************************
### 📍 **Follow the Guidelines to Contribute in the Project :**
* You need to create a separate folder named as the Project Title.
* Inside that folder, there will be four main components.
   * Images - To store the required images.
   * Dataset - To store the dataset or, information/source about the dataset.
   * Model - To store the machine learning model you've created using the dataset.
   * `requirements.txt` - This file will contain the required packages/libraries to run the project in other machines.
* Inside the `Model` folder, the `README.md` file must be filled up properly, with proper visualizations and conclusions.

***********************************************************************
:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include issue number along with it.
- Follow Contributing Guidelines & Code of Conduct before start Contributing.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : 
- GitHub Profile Link : 
- Email ID :
- Participant ID (if applicable):
- Approach for this Project :
- What is your participant role? (Mention the Open Source program)

*************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by abhisheks008** [comment]
Here is the project structure to be followed for this Web App creation issue,
```
Project Dummy
|- Dataset
  |- dataset.csv
  |- README.md
|- Images
  |- img1.png
  |- img2.png
  |- img3.png
|- Model
  |- project_dummy.ipynb
  |- README.md
|- Web App
  |- app.py
  |- templates
  |- demo.mp4
  |- README.md
|- requirements.txt
```

- For Web App README template, [click here](https://github.com/abhisheks008/DL-Simplified/blob/main/.github/web-app_readme_template.md).

**Do not remove the existing project files, just create a separate folder Web App in the existing project folder, and put your deployment there.**

**Comment by ArkaDutta-Maker** [comment]
Full name :Arka Dutta
GitHub Profile Link :https://github.com/ArkaDutta-Maker
Email ID :arka08652@gmail.com
Participant ID (if applicable):
Approach for this Project : Will use the already present model and create a flask backend api with a frontend react application
What is your participant role? GSSOC'24 contributor

**Comment by abhisheks008** [comment]
Hi @ArkaDutta-Maker you can go ahead! Assigning this issue to you.
