### ISSUE TITLE
[Model Enhancement and Feature Addition]: Bank Loan Approval Prediction with Web App

### ISSUE THREAD

**Issue by abhisheks008** [abhisheks008/DL-Simplified#583]
### Deep Learning Simplified Repository (Proposing new issue)
:red_circle: **Project Title** : [Model Enhancement and Feature Addition]: Bank Loan Approval Prediction with Web App</br>
:red_circle: **Aim** : The aim is to enhance the existing model for this project and make a web application for the same using the best fitted model after the enhancement of the model implementation. </br>
:red_circle: **Dataset** : N/A</br>
:red_circle: **Approach** : Enhance the existing models with better architectures and create Flask/Streamlit/React app for this project.</br>
:red_circle: **Reference Project for Implementation** : [**Brain Tumor Detection**](https://github.com/abhisheks008/DL-Simplified/tree/main/Brain%20Tumor%20Detection)

**********************************************************************************
### 📍 **Follow the Guidelines to Contribute in the Project :**
* You need to create a separate folder named as the Project Title.
* Inside that folder, there will be four main components.
   * Images - To store the required images.
   * Dataset - To store the dataset or, information/source about the dataset.
   * Model - To store the machine learning model you've created using the dataset.
   * `requirements.txt` - This file will contain the required packages/libraries to run the project in other machines.
* Inside the `Model` folder, the `README.md` file must be filled up properly, with proper visualizations and conclusions.

***********************************************************************
:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include issue number along with it.
- Follow Contributing Guidelines & Code of Conduct before start Contributing.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : 
- GitHub Profile Link : 
- Email ID :
- Participant ID (if applicable):
- Approach for this Project :
- What is your participant role? (Mention the Open Source program)

*************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by theiturhs** [comment]
@abhisheks008

I would like to work on this issue.

Find the details:

Name: Shruti Shrivastava
GitHub Profile: [GitHub](https://github.com/theiturhs)
Email Id: [shrutishrivastava22ss@gmail.com](mailto:shrutishrivastava22ss@gmail.com)
Participant Role: GSSOC'24

Approch:

Data exploration: To understand the characteristics well and find patterns.

Training Model: Will start with basic ML models, then ensemble (bagging and boosting), and then Neural Networks.

Model saving: Further I will save the model in suitable format that can be used while user tried to predict.

Web Interface: Next a web interface will be created through which user can interact. For this I will use Flask. 

For creating interactive templates, I will be using BootStrap for easy design and responsive web page.

Thank you

**Comment by abhisheks008** [comment]
Hi @theiturhs this is an existing project. Here is the [link](https://github.com/abhisheks008/DL-Simplified/tree/main/Bank%20Loan%20Approval%20Prediction).

But in the existing project, only one architecture is implemented. Need to implement 3 more architectures for the same dataset even if the accuracy is less than the existing model.

After implementing and enhancing the number of models, you need to build the web app using the best fitted model just like you did in the previous project.

I hope you are getting my points.

**Comment by theiturhs** [comment]
@abhisheks008 

Yes I understood. Only one thing I wanted to ask. Do we have to implement only neural networks with different architectures or other ML models will also work?

**Comment by abhisheks008** [comment]
You can do that too, but mainly focus on deep learning methods. @theiturhs 

Assigning this issue to you @theiturhs

**Comment by theiturhs** [comment]
@abhisheks008 

Sure I will take care of it.
Thank you!

**Comment by diptarup794** [comment]
Hello! I want to work on this issue . Kindly assign it to me @abhisheks008

**Comment by abhisheks008** [comment]
> Hello! I want to work on this issue . Kindly assign it to me @abhisheks008

Hi @diptarup794 thanks for showing up. But unfortunately this issue is already assigned.
