### ISSUE TITLE
Add PR template

### ISSUE THREAD

**Issue by suhanipaliwal** [abhisheks008/DL-Simplified#586]
I would like to add a pull request template for this repository. Please assign me this issue under GSSOC'24.

**Comment by abhisheks008** [comment]
Hi @suhanipaliwal thanks for showing up. This [PR template](https://github.com/abhisheks008/DL-Simplified/blob/main/.github/pull_request_template.md) is doing a great job for me as well as other project admins are using the same in their repository.

What are the changes/updation you are planning to make in the existing one?

**Comment by suhanipaliwal** [comment]
This PR template lacks a section for screenshots/videos to demonstrate the changes made. I would like to add the screenshots section and also an additional context section in which contributors can add any additional information that might be helpful for reviewers.

**Comment by abhisheks008** [comment]
> This PR template lacks a section for screenshots/videos to demonstrate the changes made. I would like to add the screenshots section and also an additional context section in which contributors can add any additional information that might be helpful for reviewers.

Well thanks for your thoughts, as of now the existing one is performing well enough for this repository. Closing this issue.
