### ISSUE TITLE
[README Enhancement]: Google Recaptcha Image Classification

### ISSUE THREAD

**Issue by Avishek8136** [abhisheks008/DL-Simplified#587]
### Deep Learning Simplified Repository (Proposing new issue)
:red_circle: **Google Recaptcha Image Classification** : </br>
:red_circle: **Aim** : The aim is to enhance the README file and make it eye pleasing, well documented using the given README template.</br>
:red_circle: **README to be enhanced** : </br>
:red_circle: **README Template** : https://github.com/abhisheks008/DL-Simplified/blob/main/.github/readme_template.md

***********************************************************************
:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include issue number along with it.
- Follow Contributing Guidelines & Code of Conduct before start Contributing.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Avishek Rauniyar
- GitHub Profile Link : Avishek8136
- Email ID : avishekrauniyar07@gmail.com
- Participant ID (if applicable): 
- Approach for this Project :I want to make a Readme file to make it easy for understanding the dl concepts.
- What is your participant role? (Mention the Open Source program) : GSSoC

*************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by abhisheks008** [comment]
Hi @Avishek8136 assigned to you.

**Comment by Avishek8136** [comment]
thanks will update shortly
