### ISSUE TITLE
[Model and README Enhancement] Glass Bangle Defects Detection

### ISSUE THREAD

**Issue by Arihant-Bhandari** [abhisheks008/DL-Simplified#589]
### Deep Learning Simplified Repository (Proposing new issue)
:red_circle: **Project Title** : Glass Bangle Defects Detection</br>
:red_circle: **Aim** : enhancing README.md and adding Keras implementations of CNN and CNN-Attention models</br>
:red_circle: **Dataset** : https://www.kaggle.com/datasets/almique/glass-bangle-defect-detection-classification</br>
:red_circle: **Approach** : I will be creating 2 deep DL models: CNN and CNN-Attention using Keras library of TensorFlow. i will also be updating the README with images as well as other potential readability upgrades.
**********************************************************************************
### 📍 **Follow the Guidelines to Contribute in the Project :**
* You need to create a separate folder named as the Project Title.
* Inside that folder, there will be four main components.
   * Images - To store the required images.
   * Dataset - To store the dataset or, information/source about the dataset.
   * Model - To store the machine learning model you've created using the dataset.
   * `requirements.txt` - This file will contain the required packages/libraries to run the project in other machines.
* Inside the `Model` folder, the `README.md` file must be filled up properly, with proper visualizations and conclusions.

***********************************************************************
:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include issue number along with it.
- Follow Contributing Guidelines & Code of Conduct before start Contributing.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Arihant Bhandari
- GitHub Profile Link : https://github.com/Arihant-Bhandari
- Email ID : arihant.bhandari.2004@gmail.com
- Participant ID (if applicable): Arihant_Bhandari (eternal_insight)
- Approach for this Project : CNN, CNN-Attention based on keras, README update
- What is your participant role? (Mention the Open Source program)
GSSoC 2024 Contributor
*************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by abhisheks008** [comment]
Assigned to you @Arihant-Bhandari

**Comment by Arihant-Bhandari** [comment]
thanks will start working on it

**Comment by Arihant-Bhandari** [comment]
hi @abhisheks008 i am writing this message to inform you about me undergoing endsems from 22 to 30th, and hence I wouldnt be able to work as much on this. if you could keep this on hold for me, i will be extremely glad for your understanding. Hope to hear from you soon and thank you for listening.

**Comment by abhisheks008** [comment]
> hi @abhisheks008 i am writing this message to inform you about me undergoing endsems from 22 to 30th, and hence I wouldnt be able to work as much on this. if you could keep this on hold for me, i will be extremely glad for your understanding. Hope to hear from you soon and thank you for listening.

Take your time and comeback once you finish your exams. End sems are important than this stuff, all the best and give your best shot there. See you soon!

**Comment by Arihant-Bhandari** [comment]
thank you so much for this ❤️
