### ISSUE TITLE
README Enhancement - Bone Marrow Cells Classification

### ISSUE THREAD

**Issue by Santhosh-Siddhardha** [abhisheks008/DL-Simplified#600]
### Deep Learning Simplified Repository (Proposing new issue)
:red_circle: **Project Title** : Bone Marrow Cells Classification using Deep Learning</br>
:red_circle: **Aim** : The aim is to enhance the README file and make it eye pleasing, well documented using the given README template.</br>
:red_circle: **README to be enhanced** : https://github.com/abhisheks008/DL-Simplified/blob/main/Bone%20Marrow%20Cells%20Classification%20using%20Deep%20Learning/README.md </br>
:red_circle: **README Template** : https://github.com/abhisheks008/DL-Simplified/blob/main/.github/readme_template.md

***********************************************************************
:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include issue number along with it.
- Follow Contributing Guidelines & Code of Conduct before start Contributing.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Lingamuneni Santhosh Siddhardha
- GitHub Profile Link : [Santhosh-Siddhardha](https://github.com/Santhosh-Siddhardha)
- Email ID : [siddhardha.7085@gmail.com](mailto:siddhardha.7085@gmail.com)
- Participant ID (if applicable): NA
- Approach for this Project : 
Review Existing README: Thoroughly review the current README file and identify areas for improvement based on the provided template.
Enhancement Plan: Develop a plan to enhance the README file, incorporating visual elements, formatting improvements, and additional documentation as per the template.
Implementation: Make the necessary enhancements to the README file following the agreed-upon plan and guidelines.
Testing and Validation: Validate the enhanced README to ensure clarity, correctness, and visual appeal.
Documentation: Document the enhancements made in the README file and provide a summary of changes.
And also will place readme.md file in model folder.
- What is your participant role? (Mention the Open Source program) GSSoC24 Contributor

*************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by abhisheks008** [comment]
The existing README looks good to me. Not many changes are required tbh. Sorry closing this issue as there is nothing much to do about this README enhancement.
