### ISSUE TITLE
[Project Addition]:Market basket Analysis

### ISSUE THREAD

**Issue by manishh12** [abhisheks008/DL-Simplified#603]
### Deep Learning Simplified Repository (Proposing new issue)
:red_circle: **Project Title** : Market Basket Analysis</br>
:red_circle: **Aim** : Market basket analysis aims to identify patterns of co-occurring items in customer transactions, helping businesses optimize product placement, cross-selling, and marketing strategies to enhance sales and customer satisfaction.</br>
:red_circle: **Dataset** : https://www.kaggle.com/datasets/rashikrahmanpritom/groceries-dataset-for-market-basket-analysismba/data?select=Groceries+data.csv</br>
:red_circle: **Approach** : I will be implementing Apriori Algorithm for initial stage but later i will try to implement using FP-Tree.

**********************************************************************************
### 📍 **Follow the Guidelines to Contribute in the Project :**
* You need to create a separate folder named as the Project Title.
* Inside that folder, there will be four main components.
   * Images - To store the required images.
   * Dataset - To store the dataset or, information/source about the dataset.
   * Model - To store the machine learning model you've created using the dataset.
   * `requirements.txt` - This file will contain the required packages/libraries to run the project in other machines.
* Inside the `Model` folder, the `README.md` file must be filled up properly, with proper visualizations and conclusions.

***********************************************************************
:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include issue number along with it.
- Follow Contributing Guidelines & Code of Conduct before start Contributing.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Manish Kumar Gupta
- GitHub Profile Link : https://github.com/manishh12
- Email ID :manishdid360@gmail.com
- Participant ID (if applicable):manishh12
- Approach for this Project :
Association Rule Mining:
I will use the MLxtend library to perform association rule mining, specifically the Apriori algorithm, to find frequently occurring itemsets in the dataset.
I will generate association rules based on metrics like support, confidence, and lift.
I will calculate support values to identify itemsets that occur frequently together.
I will calculate confidence values to measure the likelihood of one item being purchased given that another item is purchased.
I will calculate lift values to determine the strength of association between items, considering the effect of itemset size on confidence.
I will filter rules based on certain thresholds for support, confidence, and lift to extract meaningful associations.

- What is your participant role? (Mention the Open Source program)Contributor in GSSOC'24
*************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by abhisheks008** [comment]
Hi @manishh12 thanks for showing up with this issue. As per the code of conduct you can work on one issue at a time.

**Comment by manishh12** [comment]
> Hi @manishh12 thanks for showing up with this issue. As per the code of conduct you can work on one issue at a time.

Okay Sure, I'll address the tasks one by one as I complete them.
