### ISSUE TITLE
[Project Addition]:Framing the Future

### ISSUE THREAD

**Issue by manishh12** [abhisheks008/DL-Simplified#604]
### Deep Learning Simplified Repository (Proposing new issue)
:red_circle: **Project Title** : Framing the Future(Image to Video)</br>
:red_circle: **Aim** : The aim of this project is that we will be generating sequence of frames from a single frame which can be combined together to make video from a single frame.</br>
:red_circle: **Dataset** :http://www.cs.toronto.edu/~nitish/unsupervised_video/ </br>
:red_circle: **Approach** : For now i will be implementing ConvLstm to generate the frames.

**********************************************************************************
### 📍 **Follow the Guidelines to Contribute in the Project :**
* You need to create a separate folder named as the Project Title.
* Inside that folder, there will be four main components.
   * Images - To store the required images.
   * Dataset - To store the dataset or, information/source about the dataset.
   * Model - To store the machine learning model you've created using the dataset.
   * `requirements.txt` - This file will contain the required packages/libraries to run the project in other machines.
* Inside the `Model` folder, the `README.md` file must be filled up properly, with proper visualizations and conclusions.

***********************************************************************
:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include issue number along with it.
- Follow Contributing Guidelines & Code of Conduct before start Contributing.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Manish Kumar Gupta
- GitHub Profile Link : https://github.com/manishh12
- Email ID :manishdid360@gmail.com
- Participant ID (if applicable):manishh12
- Approach for this Project :I'll utilize ConvLSTM to produce subsequent frames, assessing the quality of the generated images through the Signal-to-Noise Ratio (SNR) metric.
- What is your participant role? (Mention the Open Source program)Contributor in GSSOC'24

*************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by abhisheks008** [comment]
One issue at a time.

**Comment by manishh12** [comment]
@abhisheks008 I would like to work on this issue, but currently, I can only implement one model. There are no references available that demonstrate how to generate multiple further frames from a single frame. This will be a challenging part for me as I start this project from scratch.

**Comment by abhisheks008** [comment]
Go ahead. Let's see how much close you can reach to the optimum goal. Assigned to you @manishh12
