### ISSUE TITLE
Covid-19 prediction using DL 

### ISSUE THREAD

**Issue by jeet-Abhi123** [abhisheks008/DL-Simplified#608]
### Deep Learning Simplified Repository (Proposing new issue)
:red_circle: **Project Title** : Covid-19 prediction using DL </br>
:red_circle: **Aim** : This dataset was collected  in the initial phases of covid-19 during march and april 2020. The aim of the project is to predict a person is covid-19 +ve or not with minimum possible symtoms like fever, cough, age_above_60, sore_throat etc </br>
:red_circle: **Dataset** : Taken from research paper and provided by Israeli Ministry of Health  https://www.nature.com/articles/s41746-020-00372-6</br>
:red_circle: **Approach** : First will perform EDA on the dataset, and then perform feature engineering on the columns. Will experiment with multiple models like ANN. After will perform hyperparameter tuning through KerasTuner and will plot the results graph.

**Comment by abhisheks008** [comment]
Machine learning models will not help this project repository, as this repo majorly focuses on DL methods.

**Comment by jeet-Abhi123** [comment]
OK, so I will perform only DL techniques like ANN.

**Comment by abhisheks008** [comment]
You need to implement at least 2-3 models for any particular project.

**Comment by abhisheks008** [comment]
Closing this issue, as you have already assigned to an issue. If you wanna work on this later on, you can reopen this issue.
