### ISSUE TITLE
Feature for auto commenting on a new issue creation 

### ISSUE THREAD

**Issue by suhanipaliwal** [abhisheks008/DL-Simplified#611]
I would like an automated feature that posts a predefined comment on an issue as soon as it is created. This feature aims to address the problem of delayed and inconsistent communication following the creation of issues. By automatically commenting on issues as soon as they are created, it ensures that contributors receive immediate feedback and acknowledgment for their efforts. This fosters a positive and supportive environment for collaboration, encouraging continued participation and engagement from contributors.

Could you please assign me this issue under GSSOC'24.

**Comment by suhanipaliwal** [comment]
Please add the label of appropriate level as per gssoc guidelines on this issue.

**Comment by abhisheks008** [comment]
> Please add the label of appropriate level as per gssoc guidelines on this issue.

`level1` tag is assigned

**Comment by khushi-igupta** [comment]
Hello I am a GsSOC'24 contributor and I would like to work on this issue. Can you please assign it to me?

**Comment by abhisheks008** [comment]
This issue is already assigned to a contributor, please check out the issues which are having `Up for Grabs` tag/label.
