### ISSUE TITLE
[FEAT]: Create Issue forms and make the issue options more visually appealing

### ISSUE THREAD

**Issue by TonyStark-47** [abhisheks008/DL-Simplified#612]
Currently, the issue templates are not very user friendly, so I want to improve it which will look like this 👇

![image](https://github.com/abhisheks008/DL-Simplified/assets/73957207/dbe1aeb1-e440-4c48-9dd2-931590d9b97f)

Also I will add Issue Forms to the respective issues to make it easier for the contributor to raise it.
Here is an example of how a Bug Issue Form will look like 👇

![image](https://github.com/abhisheks008/DL-Simplified/assets/73957207/6114eec1-bf21-4012-ad3a-0fa57897d11e)

**Comment by TonyStark-47** [comment]
I want to work on this issue. So, kindly assign this issue to me ( GSSOC'24 ).

**Comment by abhisheks008** [comment]
The existing issue template is fine as of now. Thanks for your interest. Closing this issue.
