### ISSUE TITLE
[Project addition] : Football Analyser

### ISSUE THREAD

**Issue by chiragHimself** [abhisheks008/DL-Simplified#616]
### Deep Learning Simplified Repository (Proposing new issue)
:red_circle: **Project Title** : FootballAnalyser</br>
:red_circle: **Aim** :The project aims at harnessing the power of advance deep learning and object detection models like yolo to simplify the sport of football. </br>
:red_circle: **Dataset** : Football feeds - kaggle dataset</br>
:red_circle: **Approach** : The project uses Yolo algorithm for detecting various players and ball and other entities in video feed then further use advance utilities like OpenCV, Supervision etc. to add the advance features like possession calculation , speed calculation , distance estimator etc.

**********************************************************************************
### 📍 **Follow the Guidelines to Contribute in the Project :**
* You need to create a separate folder named as the Project Title.
* Inside that folder, there will be four main components.
   * Images - To store the required images.
   * Dataset - To store the dataset or, information/source about the dataset.
   * Model - To store the machine learning model you've created using the dataset.
   * `requirements.txt` - This file will contain the required packages/libraries to run the project in other machines.
* Inside the `Model` folder, the `README.md` file must be filled up properly, with proper visualizations and conclusions.

***********************************************************************
:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include issue number along with it.
- Follow Contributing Guidelines & Code of Conduct before start Contributing.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Chirag Sharma
- GitHub Profile Link : www.github.com/chiragHimself
- Email ID : itschirag21@gmail.com
- Participant ID (if applicable):
- Approach for this Project : I will train the YOLO model on the football video feed dataset through kaggle and start implementing detection utilities to it.
- What is your participant role? (Mention the Open Source program) - GSSOC'24

*************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by chiragHimself** [comment]
Please assign this issue to me under GSSOC'24.

**Comment by abhisheks008** [comment]
Can you please share the URL of the dataset? Other than YOLO what are the options you have for implementing in this project as you need to implement at least 2-3 deep learning models to make this project successful in terms of this repo.

@chiragHimself

**Comment by chiragHimself** [comment]
@abhisheks008 I can also test SSD(single shot detectors), OpenCV haarcascades which are also very capable in localization but I think it still would not be able to beat the results of Yolo newer versions. Further here is the link to the kaggle dataset: https://www.kaggle.com/competitions/dfl-bundesliga-data-shootout/data?select=clips , also this roboflow dataset will be great to fine train and will make localization highly accurate : https://universe.roboflow.com/roboflow-jvuqo/football-players-detection-3zvbc/dataset/1 .

**Comment by abhisheks008** [comment]
Assigned @chiragHimself
