### ISSUE TITLE
[Project Addition] Resume Parsing and Job Description comparision using Java

### ISSUE THREAD

**Issue by Damini2004** [abhisheks008/DL-Simplified#617]
Resume parsing and job description comparison using Java involves extracting relevant information from a resume and comparing it with a job description to determine the candidate's suitability for the job. This process can be automated using Java and various libraries such as Apache Tika, Apache OpenNLP, and Apache Lucene.

**Comment by abhisheks008** [comment]
This project repo solely focuses on deep learning projects. Closing this issue.
