### ISSUE TITLE
[Feat]: Workflow for closing old PRs

### ISSUE THREAD

**Issue by Asymtode712** [abhisheks008/DL-Simplified#623]
This feature aims to automate the management of open PRs in a repository, ensuring that outdated or abandoned PRs are closed in a timely manner. By doing so, it helps maintain repository hygiene, improves workflow efficiency, and provides a better experience for both maintainers and contributors.

![Close Old PRs](https://github.com/abhisheks008/DL-Simplified/assets/115717746/a716d779-42bd-4d6b-9bf9-b590fde54849)

**Comment by Asymtode712** [comment]
@abhisheks008 please assign me this issue

**Comment by abhisheks008** [comment]
Hi @Asymtode712 in this repo, I used to review each and every PR. After reviewing them, if I found them duplicate or not so worth it, I close them. There is no need to add a bot for this problem. I am happy to review the PRs.
