### ISSUE TITLE
[Feat]: Auto Commenting when an Issue is Closed

### ISSUE THREAD

**Issue by Asymtode712** [abhisheks008/DL-Simplified#624]
This feature aims to solve the problem of poor communication and lack of acknowledgment when issues are closed. By automatically commenting on closed issues, it ensures that contributors are informed about the closure and are thanked for their efforts. This helps maintain a positive and engaging community atmosphere, encouraging continued contributions and fostering good relationships between maintainers and contributors.

![issue closed](https://github.com/abhisheks008/DL-Simplified/assets/115717746/252edd09-2b5b-4acc-85f9-f4aae559ff3d)

**Comment by Asymtode712** [comment]
@abhisheks008 please assign me this issue

**Comment by abhisheks008** [comment]
This can be done. Issue assigned to you @Asymtode712
