### ISSUE TITLE
[Project Addition]: Facial Expression Detection

### ISSUE THREAD

**Issue by Karthik110505** [abhisheks008/DL-Simplified#631]
### Deep Learning Simplified Repository (Proposing new issue)
:red_circle: **Project Title** : Facial Expression Detection </br>
:red_circle: **Aim** : To Detect the Facial Expressions </br>
:red_circle: **Dataset** :https://www.kaggle.com/datasets/fatihkgg/affectnet-yolo-format </br>
:red_circle: **Approach** : Try to use 3-4 algorithms to implement the models and compare all the algorithms to find out the best fitted algorithm for the model by checking the accuracy scores. Also do not forget to do a exploratory data analysis before creating any model.

**********************************************************************************
### 📍 **Follow the Guidelines to Contribute in the Project :**
* You need to create a separate folder named as the Project Title.
* Inside that folder, there will be four main components.
   * Images - To store the required images.
   * Dataset - To store the dataset or, information/source about the dataset.
   * Model - To store the machine learning model you've created using the dataset.
   * `requirements.txt` - This file will contain the required packages/libraries to run the project in other machines.
* Inside the `Model` folder, the `README.md` file must be filled up properly, with proper visualizations and conclusions.

***********************************************************************
:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include issue number along with it.
- Follow Contributing Guidelines & Code of Conduct before start Contributing.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name :  Veera Venkata Karthik Barrenkala
- GitHub Profile Link : https://github.com/Karthik110505
- Email ID :bvvkarthik1155@gmail.com
- Approach for this Project : I will using some of the pretrained models like yolov8, yolov5, mediapipe and detect the facial expression and make a model to detect the expression from images. If possible from video and a webcam also.
- What is your participant role? (Mention the Open Source program): GSSoC24

*************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Karthik110505** [comment]
@abhisheks008  Please assign me this issue

**Comment by abhisheks008** [comment]
Hi @Karthik110505 this type of project is already present here in this repo. Have a look, https://github.com/abhisheks008/DL-Simplified/tree/main/Facial%20Emotion%20Detection

**Comment by Karthik110505** [comment]
@abhisheks008  Yes,bro. After seeing the project only I made this issue. In that project , he/she only took the data , perfromed some model training and implemnted some evaluation methods. 

But in  my project i want to build a detection model which can make bounding boxes and detect the expression, for the images. I also want to make this work for videos and while using webcam, which didn't done in the already present project.

Now, it's your wish . Should I continue or look for some other issue?
