### ISSUE TITLE
[Project Addition] : Sports Image Classification

### ISSUE THREAD

**Issue by kyra-09** [abhisheks008/DL-Simplified#633]
### Deep Learning Simplified Repository (Proposing new issue)
:red_circle: **Project Title** : Sports Image Classification</br>
:red_circle: **Aim** : To detect 100 different sports using DL models.</br>
:red_circle: **Dataset** : https://www.kaggle.com/datasets/gpiosenka/sports-classification </br>
:red_circle: **Approach** : Try to use 3-4 algorithms to implement the models and compare all the algorithms to find out the best fitted algorithm for the model by checking the accuracy scores. Also do not forget to do a exploratory data analysis before creating any model.

**********************************************************************************
### 📍 **Follow the Guidelines to Contribute in the Project :**
* You need to create a separate folder named as the Project Title.
* Inside that folder, there will be four main components.
   * Images - To store the required images.
   * Dataset - To store the dataset or, information/source about the dataset.
   * Model - To store the machine learning model you've created using the dataset.
   * `requirements.txt` - This file will contain the required packages/libraries to run the project in other machines.
* Inside the `Model` folder, the `README.md` file must be filled up properly, with proper visualizations and conclusions.

***********************************************************************
:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include issue number along with it.
- Follow Contributing Guidelines & Code of Conduct before start Contributing.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Aaradhya Singh
- GitHub Profile Link : https://github.com/kyra-09
- Email ID : aaradhyasinghgaur@gmail.com
- Participant ID (if applicable): GSSOC-2024 Contributor
- Approach for this Project :  1. ) Using various different available network architectures such as Xception , ResNet50 , VGG16 etc. to do catagorical classification for 100 different sports using dataset (mentioned below) .
2.) use data augmentation techniques to improve the accuarcy of models.
3.) Comparing performance and accuracy of models using accuracy score ,loss and accuracy graph , confusion matrix for better understanding.
4.) Perfroming EDA (data analysis) for dataset to understand the structure of data.
5.) Using README file for describing the work I've performed.
- What is your participant role? (Mention the Open Source program) :- GSSOC-2024 Contributor

*************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by abhisheks008** [comment]
Assigned @kyra-09

**Comment by abhisheks008** [comment]
You can't work on two issues at a time. Please complete the assigned issue, then only you can work on this issue and get the assignment.
@kyra-09

**Comment by rahulnarayaniitk** [comment]
Hey @abhisheks008, 
I would like to work on this issue under GSSoC '24.
Please assign this issue to me.

**Comment by Mehaksaini2808** [comment]
Full name : Mehak
GitHub Profile Link: https://github.com/Mehaksaini2808
Email ID: mehaksaini288@gmail.com
Participant ID (if applicable): GSSOC-2024 Contributor
Approach for this Project: 1.  Performing EDA
2.  Data processing for increasing efficiency of the model.
3. Model Building - Training model using  EfficientNet, VGG16 and  ResNet50. 
4. Compare all models based on accuracy, precision, recall, F1 score, and any other relevant metrics.
What is your participant role? (Mention the Open Source program) :- GSSOC-2024 Contributor

**Comment by aryaVishal1706** [comment]
Full name : Arya Vishal
GitHub Profile Link: https://github.com/aryaVishal1706
Email ID: vishalarya5250@gmail.com
Participant ID (if applicable): GSSOC-2024 Contributor
Approach for this Project: 1. Performing EDA
2. Data processing for increasing efficiency of the model.
3. Model Building - Training model using EfficientNet, VGG16 and ResNet50.
4. Compare all models based on accuracy, precision, recall, F1 score, and any other relevant metrics.
What is your participant role? (Mention the Open Source program) :- GSSOC-2024 Contributor

**Comment by abhisheks008** [comment]
Assigned to @Mehaksaini2808 based on FCFS.

**Comment by kyra-09** [comment]
@abhisheks008 if I implement atleast 5 different models can this issue be labled as Level 3?

**Comment by abhisheks008** [comment]
Yes @kyra-09

**Comment by abhisheks008** [comment]
> @abhisheks008 if I implement atleast 5 different models can this issue be labled as Level 3?

Yes

**Comment by kyra-09** [comment]
Pardon me for asking another question...bu do we get extra points for creating an issue as well?

**Comment by aryaVishal1706** [comment]
@kyra-09 can we both work on this problem??

**Comment by abhisheks008** [comment]
> Pardon me for asking another question...but do we get extra points for creating an issue as well?

Not sure. You can check with the core team for this. I am adding the labels properly, if they allot points for it, you'll automatically get it.

@aryaVishal1706 sorry mate, one contributor can work on one issue at a time.
