### ISSUE TITLE
[Project Addition] Terrain Recognition

### ISSUE THREAD

**Issue by MohanRocks999** [abhisheks008/DL-Simplified#636]
### Deep Learning Simplified Repository (Proposing new issue)
:red_circle: **Project Title** :  Terrain Recognition</br>
:red_circle: **Aim** :  To create a DL Model based on Pytorch to recognize different types of terrains </br>
:red_circle: **Dataset** : https://www.kaggle.com/datasets/arnaud58/landscape-pictures and custom dataset gathered using web scrapers </br>
:red_circle: **Approach** :  Using ViT (Vision Transformer), Yolov8 and EfficientNet as backbone  to classify the type of terrain from the given image and evaluating  their performance using a test dataset for choosing the best deep learning model for this particular scenario.  The classification is straight foward with image dataset with label corresponding to their terrain class and using a "text class" label mapping during inference to return as output during inference. Also for the frontend i have plans to use either gradio or a custom react js based front-end for the demo app.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Mohana Krishna
- GitHub Profile Link : https://github.com/MohanRocks999
- Email ID :  www.mohanakrishna123@gmail.com
- Participant ID (if applicable): Mohana krishna | contributor. Discord ID: codex_mohan
- Approach for this Project : As mentioned above.
- What is your participant role? GSSoC 2024

**Comment by abhisheks008** [comment]
Assigned @MohanRocks999

**Comment by aryaVishal1706** [comment]
@abhisheks008 how you assign the task ? i have to find the some short of problem then you assign me that task??

**Comment by abhisheks008** [comment]
> @abhisheks008 how you assign the task ? i have to find the some short of problem then you assign me that task??

Check out the issues with Up for Grabs label and are being opened by me only.

**Comment by aryaVishal1706** [comment]
@abhisheks008 can i make a translator? which translate French to English?

**Comment by abhisheks008** [comment]
> @abhisheks008 can i make a translator? which translate French to English?

No dude. These full fledged deep learning projects. For discussion purposes, pleas use the Discord server or the Deep Learning Simplified thread in Project Intro section of the GSSoC server.
