### ISSUE TITLE
Smoking Health Assessment

### ISSUE THREAD

**Issue by Chillthrower** [abhisheks008/DL-Simplified#647]
### Deep Learning Simplified Repository (Proposing new issue)
:red_circle: **Project Title** : Smoking Health Assessment</br>
:red_circle: **Aim** : The main purpose of this project is to develop machine learning models capable of predicting gross income based on demographic and behavioral factors. </br>
:red_circle: **Dataset** : https://www.kaggle.com/datasets/utkarshx27/smoking-dataset-from-uk</br>
:red_circle: **Approach** : Develop and evaluate machine learning models to predict income using demographic and behavioral factors, followed by performance evaluation and visualization.
models used:
![WhatsApp Image 2024-05-27 at 22 55 04_4b55263e](https://github.com/abhisheks008/DL-Simplified/assets/109269103/e0a0791c-2b94-4840-9ee1-393580154547)
One of the EDA:
![WhatsApp Image 2024-05-27 at 22 55 13_0555123c](https://github.com/abhisheks008/DL-Simplified/assets/109269103/392086c9-16bd-4d21-bef8-1fa7effb9ca9)

**********************************************************************************
### 📍 **Follow the Guidelines to Contribute in the Project :**
* You need to create a separate folder named as the Project Title.
* Inside that folder, there will be four main components.
   * Images - To store the required images.
   * Dataset - To store the dataset or, information/source about the dataset.
   * Model - To store the machine learning model you've created using the dataset.
   * `requirements.txt` - This file will contain the required packages/libraries to run the project in other machines.
* Inside the `Model` folder, the `README.md` file must be filled up properly, with proper visualizations and conclusions.

***********************************************************************
:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include issue number along with it.
- Follow Contributing Guidelines & Code of Conduct before start Contributing.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Sarvajith Adyanthaya
- GitHub Profile Link : https://github.com/Chillthrower
- Email ID : sarvajithadyanthaya@gmail.com
- Participant ID (if applicable):
- Approach for this Project :
- What is your participant role? (Mention the Open Source program)
Contributor, GGSOC'24

*************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by abhisheks008** [comment]
Hi  @Chillthrower as this project repo mainly focuses on deep learning issues, I'd recommend you to please focus on the same instead of machine learning techniques.

**Comment by Chillthrower** [comment]
Oh my bad i will keep that in mind
