### ISSUE TITLE
[Feature Addition] Web Application For the project Bone Fracture Detection

### ISSUE THREAD

**Issue by binguliki** [abhisheks008/DL-Simplified#650]
### Deep Learning Simplified Repository (Proposing new issue)
:red_circle: **Project Title** : Web Application for the project Bone Fracture Detection </br>
:red_circle: **Aim** :  I would be developing a web application using the developed models of the mentioned project</br>
:red_circle: **Approach** : I would be using flask as backend to develop the web application

**********************************************************************************
### 📍 **Follow the Guidelines to Contribute in the Project :**
* You need to create a separate folder named as the Project Title.
* Inside that folder, there will be four main components.
   * Images - To store the required images.
   * Dataset - To store the dataset or, information/source about the dataset.
   * Model - To store the machine learning model you've created using the dataset.
   * `requirements.txt` - This file will contain the required packages/libraries to run the project in other machines.
* Inside the `Model` folder, the `README.md` file must be filled up properly, with proper visualizations and conclusions.

***********************************************************************
:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include issue number along with it.
- Follow Contributing Guidelines & Code of Conduct before start Contributing.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : 
- GitHub Profile Link : 
- Email ID :
- Participant ID (if applicable):
- Approach for this Project :
- What is your participant role? (Mention the Open Source program)

*************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by binguliki** [comment]
@abhisheks008 Hey bro 👋 , Can you please assign the issue to me with appropriate level tag for GSSoC ' 24

**Comment by abhisheks008** [comment]
Issues can be upgraded after reviewing the contribution.
