### ISSUE TITLE
[Project Addition] Real or Fake Job Posting Prediction

### ISSUE THREAD

**Issue by Karthik110505** [abhisheks008/DL-Simplified#660]
### Deep Learning Simplified Repository (Proposing new issue)
:red_circle: **Project Title** :  Real / Fake Job Posting Prediction </br>
:red_circle: **Aim**  :To predict whether the given job post description is real or fake using DL </br>
:red_circle: **Dataset** : https://www.kaggle.com/datasets/shivamb/real-or-fake-fake-jobposting-prediction/data  </br>
:red_circle: **Approach** : Try to use 3-4 algorithms to implement the models and compare all the algorithms to find out the best fitted algorithm for the model by checking the accuracy scores. Also do not forget to do a exploratory data analysis before creating any model.

**********************************************************************************
### 📍 **Follow the Guidelines to Contribute in the Project :**
* You need to create a separate folder named as the Project Title.
* Inside that folder, there will be four main components.
   * Images - To store the required images.
   * Dataset - To store the dataset or, information/source about the dataset.
   * Model - To store the machine learning model you've created using the dataset.
   * `requirements.txt` - This file will contain the required packages/libraries to run the project in other machines.
* Inside the `Model` folder, the `README.md` file must be filled up properly, with proper visualizations and conclusions.

***********************************************************************
:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include issue number along with it.
- Follow Contributing Guidelines & Code of Conduct before start Contributing.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Veera Venkata Karthik Barrenkala
- GitHub Profile Link : https://github.com/Karthik110505
- Email ID :bvvkarthik1155@gmail.com
- Approach for this Project : 
    1. Import the dataset
    2. Data Preprocessing , Cleaning and Preparation
    3. Vectorization
    4. Model building, Training (Using ANN, LSTM, BiLSTM , other pretrained model like BERT )
    5. Model Evaluatioin 
- What is your participant role? (Mention the Open Source program) GSSoC24

*************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Karthik110505** [comment]
@thevirengarg  Please assign me this issue.

**Comment by abhisheks008** [comment]
What are the models you are planning to implement? Can you please mention them.

**Comment by Karthik110505** [comment]
I planned to solve this issue using LSTM, BiLSTM. Before that I'll try with ANN . If necessary I'll go with pretrained models like BERT
@abhisheks008

**Comment by abhisheks008** [comment]
Assigned go ahead with this issue @Karthik110505
