### ISSUE TITLE
[Project Addition] AI Generated vs Real Images Classification using DL

### ISSUE THREAD

**Issue by Arihant-Bhandari** [abhisheks008/DL-Simplified#662]
### Deep Learning Simplified Repository (Proposing new issue)
:red_circle: **Project Title** : AI Generated vs Real Images Classification using DL</br>
:red_circle: **Aim** : Classifying images based on whether they were AI Generated or Real images ( clicked or painted by humans ).</br>
:red_circle: **Dataset** : https://www.kaggle.com/datasets/cashbowman/ai-generated-images-vs-real-images </br>
:red_circle: **Approach** : Creating custom CNN and CNN-Attention based models as well as 5-8 pre-trained models for binary classification task.

**********************************************************************************
### 📍 **Follow the Guidelines to Contribute in the Project :**
* You need to create a separate folder named as the Project Title.
* Inside that folder, there will be four main components.
   * Images - To store the required images.
   * Dataset - To store the dataset or, information/source about the dataset.
   * Model - To store the machine learning model you've created using the dataset.
   * `requirements.txt` - This file will contain the required packages/libraries to run the project in other machines.
* Inside the `Model` folder, the `README.md` file must be filled up properly, with proper visualizations and conclusions.

***********************************************************************
:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include issue number along with it.
- Follow Contributing Guidelines & Code of Conduct before start Contributing.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Arihant Bhandari
- GitHub Profile Link : https://github.com/Arihant-Bhandari
- Email ID : arihant.bhandari.2004@gmail.com
- Participant ID (if applicable): Arihant Bhandari (eternal_insight)
- Approach for this Project : using pretrained and custom cnn models for classification
- What is your participant role? (Mention the Open Source program)
GSSoC 2024 Contributor
*************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by abhisheks008** [comment]
How many models in total are you planning for this project?
@Arihant-Bhandari

**Comment by Arihant-Bhandari** [comment]
5-6 pre-trained , and 2 custom CNN's , I can reduce things down , my inital work is ready to be committed for review actually

**Comment by abhisheks008** [comment]
Wait @Arihant-Bhandari

**Comment by Arihant-Bhandari** [comment]
Hi @abhisheks008 I'm ready for this project and another as well. I will be sending initial work soon on both would you be kind and check them out.

I was looking to rank push actually, that's why 2 projects 😅😅.

**Comment by abhisheks008** [comment]
Without assignment you can't create a pull request. If this happens then what's the point of assigning an issue to a contributor? No need to create issues then, push your codes as much as you can. When there is a transparent system for the whole open source then why are you trying to bypassing the same? 

You are creating issues, that's fine. What's so hurry? You are pushing your PRs one after another without an assignment to the created issues. This is not ethical and against the code of conduct.

**Comment by Arihant-Bhandari** [comment]
> Without assignment you can't create a pull request. If this happens then what's the point of assigning an issue to a contributor? No need to create issues then, push your codes as much as you can. When there is a transparent system for the whole open source then why are you trying to bypassing the same?
> 
> You are creating issues, that's fine. What's so hurry? You are pushing your PRs one after another without an assignment to the created issues. This is not ethical and against the code of conduct.

extremely sorry for this, will not happen again. will follow procedures from next time

**Comment by abhisheks008** [comment]
It's not about spamming your PRs to the repo, collecting points. If you really wanna collect points for swags, there lots of projects please you can collect your points there.

Do not spam here.
