### ISSUE TITLE
[Project Addition] : Covid-19 X-Ray Image Classification

### ISSUE THREAD

**Issue by kyra-09** [abhisheks008/DL-Simplified#664]
### Deep Learning Simplified Repository (Proposing new issue)
:red_circle: **Project Title** : [Project Addition] : Covid-19 X-Ray Image Classification</br>
:red_circle: **Aim** : To classify various and prediction of COVID-19 using chest X-ray image dataset.</br>
:red_circle: **Dataset** : https://www.kaggle.com/datasets/pranavraikokte/covid19-image-dataset</br>
:red_circle: **Approach** : Try to use 3-4 algorithms to implement the models and compare all the algorithms to find out the best fitted algorithm for the model by checking the accuracy scores. Also do not forget to do a exploratory data analysis before creating any model.

**********************************************************************************
### 📍 **Follow the Guidelines to Contribute in the Project :**
* You need to create a separate folder named as the Project Title.
* Inside that folder, there will be four main components.
   * Images - To store the required images.
   * Dataset - To store the dataset or, information/source about the dataset.
   * Model - To store the machine learning model you've created using the dataset.
   * `requirements.txt` - This file will contain the required packages/libraries to run the project in other machines.
* Inside the `Model` folder, the `README.md` file must be filled up properly, with proper visualizations and conclusions.

***********************************************************************
:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include issue number along with it.
- Follow Contributing Guidelines & Code of Conduct before start Contributing.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Aaradhya Singh
- GitHub Profile Link : https://github.com/kyra-09
- Email ID : aaradhyasinghgaur@gmail.com
- Participant ID (if applicable):
- Approach for this Project : 
1. ) Using 5 different available network architectures such as DenseNet121 , Xception , VGG16 etc. to do catagorical classification for chest X-ray images to detect COVID19 symptom .
2.) use data augmentation techniques to improve the accuarcy of models.
3.) Comparing performance and accuracy of models using accuracy score ,loss and accuracy graph , confusion matrix for better understanding.
4.) Perfroming EDA (data analysis) for dataset to understand the structure of data.
5.) Using README file for describing the work I've performed.
- What is your participant role? (Mention the Open Source program) - GSSOC-2024 Contributor

kindly assign this issue to me @abhisheks008 

*************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by abhisheks008** [comment]
Wait for the existing PR to be merged with the repository.
@kyra-09

**Comment by kyra-09** [comment]
Okay... I'll soon make the changes and get back to you

**Comment by abhisheks008** [comment]
At least wait for this issue to get assigned to you. Without an assignment why have you pushed your code?
@kyra-09

**Comment by kyra-09** [comment]
Pardon me @abhisheks008 for my ignorance..do you want me to close the pr and get assigned first?

**Comment by abhisheks008** [comment]
> Pardon me @abhisheks008 for my ignorance..do you want me to close the pr and get assigned first?

Yes. If the GSSOC core team observed this kind of thing, your contributions will be disqualified. That's why I haven't added any labels there.

**Comment by kyra-09** [comment]
@abhisheks008 assign this issue to me.

**Comment by abhisheks008** [comment]
Make your pull request in the evening.
