### ISSUE TITLE
[Project Addition] : Thyroid Recurrence Prediction

### ISSUE THREAD

**Issue by arpy8** [abhisheks008/DL-Simplified#665]
### Deep Learning Simplified Repository (Proposing new issue)
:red_circle: **Project Title** : Thyroid Recurrence Prediction </br>
:red_circle: **Aim** : To classify whether a person is prone to have thyroid again or not using Thyroid Disease Dataset.</br>
:red_circle: **Dataset** : https://www.kaggle.com/datasets/jainaru/thyroid-disease-data/data</br>
:red_circle: **Approach** : Try to use 3-4 algorithms to implement the models and compare all the algorithms to find out the best fitted algorithm for the model by checking the accuracy scores. Also do not forget to do a exploratory data analysis before creating any model.

**********************************************************************************
### 📍 **Follow the Guidelines to Contribute in the Project :**
* You need to create a separate folder named as the Project Title.
* Inside that folder, there will be four main components.
   * Images - To store the required images.
   * Dataset - To store the dataset or, information/source about the dataset.
   * Model - To store the machine learning model you've created using the dataset.
   * `requirements.txt` - This file will contain the required packages/libraries to run the project in other machines.
* Inside the `Model` folder, the `README.md` file must be filled up properly, with proper visualizations and conclusions.

***********************************************************************
:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include issue number along with it.
- Follow Contributing Guidelines & Code of Conduct before start Contributing.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Arpit Sengar
- GitHub Profile Link : https://github.com/arpy8
- Email ID : arpitsengar99@gmail.com
- Participant ID (if applicable): 
- Approach for this Project :
- What is your participant role? (Mention the Open Source program) GSSOC Contributor

*************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by abhisheks008** [comment]
What are deep learning models you are planning to implement for this project?
@arpy8

**Comment by arpy8** [comment]
> What are deep learning models you are planning to implement for this project? @arpy8

I am planning to use MLP and TabNet

**Comment by abhisheks008** [comment]
> > What are deep learning models you are planning to implement for this project? @arpy8
> 
> I am planning to use MLP and TabNet

Need to implement 3 models. Please share your updated approach.

**Comment by arpy8** [comment]
> I am planning to use MLP and TabNet

Okay I'll like to include an `autogluon` model as my third one.

List of all the three approaches:
- MLP
- TabNet
- autogluon

**Comment by abhisheks008** [comment]
Assigned @arpy8
