### ISSUE TITLE
Alzheimer detection

### ISSUE THREAD

**Issue by Pranshu-jais** [abhisheks008/DL-Simplified#669]
### Deep Learning Simplified Repository (Proposing new issue)
:red_circle: **Project Title** : Web application for Alzheimer detection</br>
:red_circle: **Aim** : To identify the stage of Alzhhemir's Disease using  Alzheimer's dataset consists of MRI images and showing result using flask app</br>
:red_circle: **Dataset** : https://www.kaggle.com/datasets/tourist55/alzheimers-dataset-4-class-of-images</br>
:red_circle: **Approach** : using CNN  and  InceptionV3 model for  classification of alzhemir disease evaluating their performance using a test dataset for choosing the best deep learning model  and deploying it to a flask app 

**********************************************************************************
### 📍 **Follow the Guidelines to Contribute in the Project :**
* You need to create a separate folder named as the Project Title.
* Inside that folder, there will be four main components.
   * Images - To store the required images.
   * Dataset - To store the dataset or, information/source about the dataset.
   * Model - To store the machine learning model you've created using the dataset.
   * `requirements.txt` - This file will contain the required packages/libraries to run the project in other machines.
* Inside the `Model` folder, the `README.md` file must be filled up properly, with proper visualizations and conclusions.

***********************************************************************
:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include issue number along with it.
- Follow Contributing Guidelines & Code of Conduct before start Contributing.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Pranshu jaiswal
- GitHub Profile Link : https://github.com/Pranshu-jais
- Email ID :pranshuj690@gmail.com
- Participant ID (if applicable):Pranshu | Contributor. Discord ID: anurag342
- Approach for this Project :As mentioned above
- What is your participant role? GSSoC 2024

*************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by abhisheks008** [comment]
This problem statement is already done by the contributors. 

https://github.com/abhisheks008/DL-Simplified/tree/main/Alzheimers%20Detection

Closing this issue as duplicate.
