### ISSUE TITLE
 Classification of emotions

### ISSUE THREAD

**Issue by Pranshu-jais** [abhisheks008/DL-Simplified#670]
### Deep Learning Simplified Repository (Proposing new issue)
:red_circle: **Project Title** : Classification of emotions</br>
:red_circle: **Aim** : classification of emotions of a persion in image and video</br>
:red_circle: **Dataset** : https://www.kaggle.com/datasets/sujaykapadnis/emotion-recognition-dataset</br>
:red_circle: **Approach** : Training CNN model to identify emotions in text as well as in video  and  evaluting it on various performance  matrix  

**********************************************************************************
### 📍 **Follow the Guidelines to Contribute in the Project :**
* You need to create a separate folder named as the Project Title.
* Inside that folder, there will be four main components.
   * Images - To store the required images.
   * Dataset - To store the dataset or, information/source about the dataset.
   * Model - To store the machine learning model you've created using the dataset.
   * `requirements.txt` - This file will contain the required packages/libraries to run the project in other machines.
* Inside the `Model` folder, the `README.md` file must be filled up properly, with proper visualizations and conclusions.

***********************************************************************
:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include issue number along with it.
- Follow Contributing Guidelines & Code of Conduct before start Contributing.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Pranshu Jaiswal
- GitHub Profile Link : https://github.com/Pranshu-jais
- Email ID :pranshuj690@gmail.com
- Participant ID (if applicable):Pranshu | Contributor. Discord ID: anurag342
- Approach for this Project :As mentioned above
- What is your participant role? GSSoC 2024

*************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by abhisheks008** [comment]
This type of problem statement/project is already present in this repo.

https://github.com/abhisheks008/DL-Simplified/tree/main/Facial%20Emotion%20Detection

Closing this issue as duplicate.
