### ISSUE TITLE
[Feature]: add codeql ci/cd workflow for `Python`

### ISSUE THREAD

**Issue by harmeetsingh11** [abhisheks008/DL-Simplified#671]
### Describe the feature

The repository contains code in `Python` , it does not have workflow for code scanning. 

### How would you like to see it implemented?

I aim to implement the CodeQL workflow to automate security checks. CodeQL, GitHub's code analysis engine, will identify vulnerabilities in the code and present the findings as code scanning alerts. This workflow will be activated for every push, commit, and pull request through GitHub Actions.

### Record

- [X] I'm a GSSOC'24 contributor
- [X] I agree to follow project's code of conduct
- [X] I want to work on this issue

**Comment by abhisheks008** [comment]
Workflow issues are not being considered as a contribution for GSSoC.
Closing this issue.
