### ISSUE TITLE
Emojify 😉

### ISSUE THREAD

**Issue by binguliki** [abhisheks008/DL-Simplified#673]
### Deep Learning Simplified Repository (Proposing new issue)
:red_circle: **Project Title** :  Emojify </br>
:red_circle: **Aim** :  The aim of this model is to predict appropriate EMOJIS for a given sentence </br>
:red_circle: **Dataset** : https://www.kaggle.com/datasets/hariharasudhanas/twitter-emoji-prediction </br>
:red_circle: **Approach** : I would be first fetching the data and apply basic preprocessing and then i would be using 2-3 models such as LSTM , Bidirectional LSTM and GRU after which perform hyperparameter tuning over the Best model.

**********************************************************************************
### 📍 **Follow the Guidelines to Contribute in the Project :**
* You need to create a separate folder named as the Project Title.
* Inside that folder, there will be four main components.
   * Images - To store the required images.
   * Dataset - To store the dataset or, information/source about the dataset.
   * Model - To store the machine learning model you've created using the dataset.
   * `requirements.txt` - This file will contain the required packages/libraries to run the project in other machines.
* Inside the `Model` folder, the `README.md` file must be filled up properly, with proper visualizations and conclusions.

***********************************************************************
:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include issue number along with it.
- Follow Contributing Guidelines & Code of Conduct before start Contributing.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name :  Bingumalla Likith
- GitHub Profile Link : [binguliki](https://github.com/binguliki)
- Email ID : blikith86@gmail.com
- Participant ID (if applicable): NA
- Approach for this Project :
- What is your participant role? (Mention the Open Source program) : `GSSoC'24 | Contributor`

*************************************************************

**Comment by binguliki** [comment]
@abhisheks008 , 👋 Hey bro can you please assign me this issue under GSSoC'24 with a appropriate level tag

**Comment by abhisheks008** [comment]
One issue at a time.

**Comment by binguliki** [comment]
@abhisheks008 Hey bro, Done with my previous task can you please assign me this

**Comment by abhisheks008** [comment]
Assigned @binguliki
