### ISSUE TITLE
Condition Monitoring using DL Techniques

### ISSUE THREAD

**Issue by jeet-Abhi123** [abhisheks008/DL-Simplified#680]
### Deep Learning Simplified Repository (Proposing new issue)
:red_circle: ** Condition Monitoring of Industrial equipment** : </br>
:red_circle: **Aim** : To predict the Remaining useful life of the airplane engine so that huge loss in terms of money and time can be prevented.</br>
:red_circle: **Dataset** :  Dataset is available on NASA's website 
https://data.nasa.gov/Aerospace/CMAPSS-Jet-Engine-Simulated-Data/ff5v-kuh6/about_data</br>
:red_circle: **Approach** : I will perform data preprocessing steps to convert the dataset in csv file format because it is present in text files. Then I will do EDA and will remove unnecessary columns. After that will implement LSTM, CNN, ANN or may be GRU (Gated recurrent units). Will evaluate the results through RMSE and draw meaningful graphs.

:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Abhijeet Kaithwas
- GitHub Profile Link : 
- Email ID : abhijeet.kaithwas13@gmail.com
- What is your participant role? (Mention the Open Source program) : Contributor GSSOC'24 

*************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by abhisheks008** [comment]
Assigned @jeet-Abhi123
