### ISSUE TITLE
 Dog Breed Classification

### ISSUE THREAD

**Issue by Pranshu-jais** [abhisheks008/DL-Simplified#683]
### Deep Learning Simplified Repository (Proposing new issue)
:red_circle: **Project Title** : Dog Breed Classification</br>
:red_circle: **Aim** : End-to-end Multil-class Dog Breed Classification</br>
:red_circle: **Dataset** : https://www.kaggle.com/c/dog-breed-identification/data</br>
:red_circle: **Approach** : Building  and training Multil-class Dog Breed Classification deeplearning model to classify breed breed of a dog   l

**********************************************************************************
### 📍 **Follow the Guidelines to Contribute in the Project :**
* You need to create a separate folder named as the Project Title.
* Inside that folder, there will be four main components.
   * Images - To store the required images.
   * Dataset - To store the dataset or, information/source about the dataset.
   * Model - To store the machine learning model you've created using the dataset.
   * `requirements.txt` - This file will contain the required packages/libraries to run the project in other machines.
* Inside the `Model` folder, the `README.md` file must be filled up properly, with proper visualizations and conclusions.

***********************************************************************
:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include issue number along with it.
- Follow Contributing Guidelines & Code of Conduct before start Contributing.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Pranshu Jaiswal 
- GitHub Profile Link : https://github.com/Pranshu-jais
- Email ID :pranshuj690@gmail.com
- Participant ID (if applicable):Pranshu | Contributor. Discord ID: anurag342
- Approach for this Project :As mentioned above 
- What is your participant role? GSSoC 2024

*************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Pratzybha** [comment]
Deep Learning Simplified Repository (Proposing new issue)
🔴 Project Title : Dog Breed Classification

🔴 Aim : End-to-end Multil-class Dog Breed Classification

🔴 Dataset : https://www.kaggle.com/c/dog-breed-identification/data

🔴 Approach :
Baseline Model: Start with a simple CNN architecture to establish a baseline.
Transfer Learning: Fine-tune VGG16, ResNet50, or InceptionV3 pre-trained models using the dog breed data.

📍 Follow the Guidelines to Contribute in the Project :
You need to create a separate folder named as the Project Title.
Inside that folder, there will be four main components.
Images - To store the required images.
Dataset - To store the dataset or, information/source about the dataset.
Model - To store the machine learning model you've created using the dataset.
requirements.txt - This file will contain the required packages/libraries to run the project in other machines.
Inside the Model folder, the README.md file must be filled up properly, with proper visualizations and conclusions.
🔴🟡 Points to Note :

The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
"Issue Title" and "PR Title should be the same. Include issue number along with it.
Follow Contributing Guidelines & Code of Conduct before start Contributing.
✅ To be Mentioned while taking the issue :

Full name : Pratibha Balgi
GitHub Profile Link : https://github.com/Pratzybha
Email ID :pratibhabalgi02@gmail.com
Participant ID (if applicable):PratibhaBalgi | Contributor
Approach for this Project :As mentioned above
What is your participant role? GSSoC 2024 - ext

**Comment by abhisheks008** [comment]
Closing this issue as a similar kind of problem statement is already present here in this repository.
