### ISSUE TITLE
[Feature Addition]: Web App for Fake News Detection

### ISSUE THREAD

**Issue by AKing-283** [abhisheks008/DL-Simplified#687]
### Deep Learning Simplified Repository (Proposing new issue)
:red_circle: **Project Title** : Fake. News Detection </br>
:red_circle: **Aim** : Integrating frontend for this model</br>
:red_circle: **Dataset** : using the provided one datasets and using gradio for frontend </br>
:red_circle: **Approach** : Trying to build a front end for this project where user can insert  the news and can get predictions. 

**********************************************************************************
### 📍 **Follow the Guidelines to Contribute in the Project :**
* You need to create a separate folder named as the Project Title.
* Inside that folder, there will be four main components.
   * Images - To store the required images.
   * Dataset - To store the dataset or, information/source about the dataset.
   * Model - To store the machine learning model you've created using the dataset.
   * `requirements.txt` - This file will contain the required packages/libraries to run the project in other machines.
* Inside the `Model` folder, the `README.md` file must be filled up properly, with proper visualizations and conclusions.

***********************************************************************
:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include issue number along with it.
- Follow Contributing Guidelines & Code of Conduct before start Contributing.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Puspak Dakkata
- GitHub Profile Link : https://github.com/AKing-283
- Email ID :dpreddy294@gmail.ccom
- Participant ID (if applicable):
- Approach for this Project : Girlscript summer of code projects 2024
- What is your participant role? (Mention the Open Source program): Girlscript Summer of Code 2024

*************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by abhisheks008** [comment]
Are you trying to create a web app for this project?
https://github.com/abhisheks008/DL-Simplified/tree/main/Fake%20News%20Detection

@AKing-283

**Comment by AKing-283** [comment]
yess I am looking for usage of  Streamlit or Gradio for this

**Comment by abhisheks008** [comment]
Cool go ahead @AKing-283

**Comment by AKing-283** [comment]
Thanks @abhisheks008 👍🏻

**Comment by AKing-283** [comment]
**Here is my work for Fake news detector:**
<img width="1164" alt="Screenshot 2024-06-13 at 9 26 46 AM" src="https://github.com/abhisheks008/DL-Simplified/assets/154039781/5a3afa71-6dc3-4702-9683-2afc3f74e851">
