### ISSUE TITLE
[Project Addition] AI Generated vs Real Images Classification using DL

### ISSUE THREAD

**Issue by Arihant-Bhandari** [abhisheks008/DL-Simplified#701]
### Deep Learning Simplified Repository (Proposing new issue)
:red_circle: **Project Title** : AI Generated vs Real Images Classification using DL</br>
:red_circle: **Aim** : Classifying images based on whether they were AI Generated or Real images ( clicked or painted by humans ).</br>
:red_circle: **Dataset** : https://www.kaggle.com/datasets/cashbowman/ai-generated-images-vs-real-images </br>
:red_circle: **Approach** : Creating custom CNN and CNN-Attention based models as well as 5 pre-trained models for binary classification task.

**********************************************************************************
### 📍 **Follow the Guidelines to Contribute in the Project :**
* You need to create a separate folder named as the Project Title.
* Inside that folder, there will be four main components.
   * Images - To store the required images.
   * Dataset - To store the dataset or, information/source about the dataset.
   * Model - To store the machine learning model you've created using the dataset.
   * `requirements.txt` - This file will contain the required packages/libraries to run the project in other machines.
* Inside the `Model` folder, the `README.md` file must be filled up properly, with proper visualizations and conclusions.

***********************************************************************
:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include issue number along with it.
- Follow Contributing Guidelines & Code of Conduct before start Contributing.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Arihant Bhandari
- GitHub Profile Link : https://github.com/Arihant-Bhandari
- Email ID : arihant.bhandari.2004@gmail.com
- Participant ID (if applicable): Arihant Bhandari (eternal_insight)
- Approach for this Project : using pretrained and custom cnn models for classification
- What is your participant role? (Mention the Open Source program)
GSSoC 2024 Contributor
*************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Arihant-Bhandari** [comment]
hi @abhisheks008 this is the next project i want to take on. pls assign this to me, thank you for the same.

**Comment by abhisheks008** [comment]
Assigned @Arihant-Bhandari

**Comment by Arihant-Bhandari** [comment]
@abhisheks008 i had something on the side i wanted to discuss with you beforehand.

i had a project i worked on previously, using NVIDIA stock data, and created RNNs for opening and closing prediction.

can it be considered for submission if i were to create ANNs for the same, so in total there will be 4 models ANN and RNN for opening and closing respectively ?
