### ISSUE TITLE
[Project Addition]:Intrusion Detection

### ISSUE THREAD

**Issue by manishh12** [abhisheks008/DL-Simplified#703]
### Deep Learning Simplified Repository (Proposing new issue)
:red_circle: **Project Title** : Intrusion Detection</br>
:red_circle: **Aim** : The aim of the project is to build  network intrusion detector, a predictive model capable of distinguishing between bad'' connections, called intrusions or attacks, and good' normal connections. </br>
:red_circle: **Dataset** :https://www.kaggle.com/datasets/galaxyh/kdd-cup-1999-data?select=kddcup.data_10_percent.gz </br>
:red_circle: **Approach** : Try to use 3-4 algorithms to implement the models and compare all the algorithms to find out the best fitted algorithm for the model by checking the accuracy scores. Also do not forget to do a exploratory data analysis before creating any model.

**********************************************************************************
### 📍 **Follow the Guidelines to Contribute in the Project :**
* You need to create a separate folder named as the Project Title.
* Inside that folder, there will be four main components.
   * Images - To store the required images.
   * Dataset - To store the dataset or, information/source about the dataset.
   * Model - To store the machine learning model you've created using the dataset.
   * `requirements.txt` - This file will contain the required packages/libraries to run the project in other machines.
* Inside the `Model` folder, the `README.md` file must be filled up properly, with proper visualizations and conclusions.

***********************************************************************
:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include issue number along with it.
- Follow Contributing Guidelines & Code of Conduct before start Contributing.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Manish Kumar Gupta
- GitHub Profile Link : manishh12
- Email ID :manishdid360@gmail.com
- Participant ID (if applicable):
- Approach for this Project : I will be implementing the 2-3 Neural Network Models and do the comparison between them with EDA of the dataset.
- What is your participant role? (Mention the Open Source program)GSSOC'24 Contributor

*************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by abhisheks008** [comment]
Assigned @manishh12
