### ISSUE TITLE
Quality Prediction in a Mining Process

### ISSUE THREAD

**Issue by abhisheks008** [abhisheks008/DL-Simplified#72]
### Deep Learning Simplified Repository (Proposing new issue)
:red_circle: **Project Title** : Quality Prediction in a Mining Process</br>
:red_circle: **Aim** : Explore real industrial data and help manufacturing plants to be more efficient</br>
:red_circle: **Dataset** : https://www.kaggle.com/datasets/edumagalhaes/quality-prediction-in-a-mining-process</br>
:red_circle: **Approach** : Try to use 3-4 algorithms to implement the models and compare all the algorithms to find out the best fitted algorithm for the model by checking the accuracy scores. Also do not forget to do a exploratory data analysis before creating any model.

**********************************************************************************
### 📍 **Follow the Guidelines to Contribute in the Project :**
* You need to create a separate folder named as the Project Title.
* Inside that folder, there will be four main components.
   * Images - To store the required images.
   * Dataset - To store the dataset or, information/source about the dataset.
   * Model - To store the machine learning model you've created using the dataset.
   * `requirements.txt` - This file will contain the required packages/libraries to run the project in other machines.
* Inside the `Model` folder, the `README.md` file must be filled up properly, with proper visualizations and conclusions.

***********************************************************************
:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include issue number along with it.
- Follow Contributing Guidelines & Code of Conduct before start Contributing.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : 
- GitHub Profile Link : 
- Email ID :
- Participant ID (if applicable):
- Approach for this Project :
- What is your participant role? (Mention the Open Source program)

*************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by vryan-06** [comment]
Hey @abhisheks008, I would like to give this a try

Full name : Valiaparambil Ryan Taffy
GitHub Profile Link : https://github.com/vryan-06
Email ID : [ryan19vt@gmail.com](mailto:ryan19vt@gmail.com)
Approach for this Project : Would initially try solving this with some Classifier algorithm and then move on to ANN. (Suggestions if any would be helpful)
Participant role : SSOC - 2022

**Comment by abhisheks008** [comment]
Issue assigned to you @vryan-06

**Comment by abhisheks008** [comment]
Updates please @vryan-06

**Comment by abhisheks008** [comment]
If possible try to finish this by this week, as your exams are knocking at the door. If not possible then, don't worry you can finish this issue after your exams are over.
@vryan-06

**Comment by abhisheks008** [comment]
@vryan-06 updates please.

**Comment by vryan-06** [comment]
I have made models using LR, DT and RF. Will try ANN now and submit it. College schedule has been a little too hectic, so will try to complete it by tomorrow.
