### ISSUE TITLE
[Project Addition] : Pharmaceutical Drugs and Vitamins Images Detection 

### ISSUE THREAD

**Issue by kyra-09** [abhisheks008/DL-Simplified#721]
### Deep Learning Simplified Repository (Proposing new issue)
:red_circle: **Project Title** : Pharmaceutical Drugs and Vitamins Images Detection </br>
:red_circle: **Aim** : The below dataset includes images of popular pharmaceutical drugs and vitamins in the Philippines. This is dataset can be used for classifying drug images using CNN and transfer learning. Currently, there are ten available classes of pill images.</br>
:red_circle: **Dataset** : https://www.kaggle.com/datasets/vencerlanz09/pharmaceutical-drugs-and-vitamins-dataset-v2 </br>
:red_circle: **Approach** : Try to use 3-4 algorithms to implement the models and compare all the algorithms to find out the best fitted algorithm for the model by checking the accuracy scores. Also do not forget to do a exploratory data analysis before creating any model.

**********************************************************************************
### 📍 **Follow the Guidelines to Contribute in the Project :**
* You need to create a separate folder named as the Project Title.
* Inside that folder, there will be four main components.
   * Images - To store the required images.
   * Dataset - To store the dataset or, information/source about the dataset.
   * Model - To store the machine learning model you've created using the dataset.
   * `requirements.txt` - This file will contain the required packages/libraries to run the project in other machines.
* Inside the `Model` folder, the `README.md` file must be filled up properly, with proper visualizations and conclusions.

***********************************************************************
:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include issue number along with it.
- Follow Contributing Guidelines & Code of Conduct before start Contributing.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Aaradhya Singh
- GitHub Profile Link : https://github.com/kyra-09
- Email ID : aaradhyasinggaur@gmail.com
- Participant ID (if applicable):
- Approach for this Project :

   1. Utilizing 5 models such as DenseNet121 , Xception, VGG16, ResNet50, and InceptionV3 for image classification.
   2. Applying data augmentation (rotation, zooming, flipping, shearing, brightness) to enhance dataset robustness.
   3. Comparing model performance using accuracy scores, loss/accuracy graphs, and confusion matrices.
   4. Conducting EDA for dataset insights, including image distribution, quality, class imbalances, and sample visualization.
   5. Documening the process in a comprehensive README file.

- What is your participant role? (Mention the Open Source program) - GSSOC-2024 Contributor

*************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by abhisheks008** [comment]
Hi @kyra-09 assigning this issue to you.
