### ISSUE TITLE
[Project Addition] Arabic Date Species Classification using DL

### ISSUE THREAD

**Issue by Arihant-Bhandari** [abhisheks008/DL-Simplified#733]
### Deep Learning Simplified Repository (Proposing new issue)
:red_circle: **Project Title** : Arabic Date Species Classification using DL</br>
:red_circle: **Aim** : Classifying Arabic Dates into 9 different species found in the arabic region.</br>
:red_circle: **Dataset** : https://www.kaggle.com/datasets/wadhasnalhamdan/date-fruit-image-dataset-in-controlled-environment</br>
:red_circle: **Approach** : Creating custom CNN model as well as 5 pre-trained models for multi-class classification task.

**********************************************************************************
### 📍 **Follow the Guidelines to Contribute in the Project :**
* You need to create a separate folder named as the Project Title.
* Inside that folder, there will be four main components.
   * Images - To store the required images.
   * Dataset - To store the dataset or, information/source about the dataset.
   * Model - To store the machine learning model you've created using the dataset.
   * `requirements.txt` - This file will contain the required packages/libraries to run the project in other machines.
* Inside the `Model` folder, the `README.md` file must be filled up properly, with proper visualizations and conclusions.

***********************************************************************
:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include issue number along with it.
- Follow Contributing Guidelines & Code of Conduct before start Contributing.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Arihant Bhandari
- GitHub Profile Link : https://github.com/Arihant-Bhandari
- Email ID : arihant.bhandari.2004@gmail.com
- Participant ID (if applicable): Arihant Bhandari (eternal_insight)
- Approach for this Project : using pretrained and custom cnn models for classification (pre-trained: resent50, vgg16, inception, xception)
- What is your participant role? (Mention the Open Source program)
GSSoC 2024 Contributor
*************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Arihant-Bhandari** [comment]
hi @abhisheks008 pls assign this to me if the previous PR is approved. Thank you as always for your time and patience.

**Comment by Arihant-Bhandari** [comment]
Hi @abhisheks008 pls add tags to this so that I can start a PR for this , to switch over to this issue.

Rock classification's main issue is in its diversity, and due to rock patterns, CNNs can't generalize them well.

I am trying out hugging face transformers currently on it , but it will take me time , and I have other projects lined up that I can submit to you today.

**Comment by abhisheks008** [comment]
Assigned @Arihant-Bhandari

**Comment by Arihant-Bhandari** [comment]
Thank you so much for this ❤️
