### ISSUE TITLE
[Project Addition]: Simple object Detection

### ISSUE THREAD

**Issue by manishh12** [abhisheks008/DL-Simplified#734]
### Deep Learning Simplified Repository (Proposing new issue)
:red_circle: **Project Title** : Simple Object Detetction
:red_circle: **Aim** : The aim of the project is to  build neural network which is able to detect objects in frame.
:red_circle: **Dataset** : https://www.kaggle.com/datasets/kishanj/simple-object-detection/data
:red_circle: **Approach** : Try to use 3-4 algorithms to implement the models and compare all the algorithms to find out the best fitted algorithm for the model by checking the accuracy scores. Also do not forget to do a exploratory data analysis before creating any model.

**********************************************************************************
### 📍 **Follow the Guidelines to Contribute in the Project :**
* You need to create a separate folder named as the Project Title.
* Inside that folder, there will be four main components.
   * Images - To store the required images.
   * Dataset - To store the dataset or, information/source about the dataset.
   * Model - To store the machine learning model you've created using the dataset.
   * `requirements.txt` - This file will contain the required packages/libraries to run the project in other machines.
* Inside the `Model` folder, the `README.md` file must be filled up properly, with proper visualizations and conclusions.

***********************************************************************
:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include issue number along with it.
- Follow Contributing Guidelines & Code of Conduct before start Contributing.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Manish Kumar Gupta
- GitHub Profile Link : manishh12
- Email ID :manishdid360@gmail.com
- Participant ID (if applicable):
- Approach for this Project : I will be implementing 4-5 Neural Network models and will do the comparison with EDA of Dataset.
- What is your participant role? GSSOC"24

*************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by abhisheks008** [comment]
Assigned @manishh12
