### ISSUE TITLE
Indian Medicinal Plants Classification 

### ISSUE THREAD

**Issue by aaradhyasinghgaur** [abhisheks008/DL-Simplified#738]
### Deep Learning Simplified Repository (Proposing new issue)
:red_circle: **Project Title** : Indian Medicinal Plants Classification </br>
:red_circle: **Aim** : The below dataset consists of medicinal leaf images. It comprises 40 distinct Indian leaf varieties renowned for their potent medicinal properties and offers a rich opportunity for advancing healthcare, botanical studies, and machine learning applications.</br>
:red_circle: **Dataset** : https://www.kaggle.com/datasets/crypticfate5/medicinal-plants </br>
:red_circle: **Approach** : Try to use 3-4 algorithms to implement the models and compare all the algorithms to find out the best fitted algorithm for the model by checking the accuracy scores. Also do not forget to do a exploratory data analysis before creating any model.

**********************************************************************************
### 📍 **Follow the Guidelines to Contribute in the Project :**
* You need to create a separate folder named as the Project Title.
* Inside that folder, there will be four main components.
   * Images - To store the required images.
   * Dataset - To store the dataset or, information/source about the dataset.
   * Model - To store the machine learning model you've created using the dataset.
   * `requirements.txt` - This file will contain the required packages/libraries to run the project in other machines.
* Inside the `Model` folder, the `README.md` file must be filled up properly, with proper visualizations and conclusions.

***********************************************************************
:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include issue number along with it.
- Follow Contributing Guidelines & Code of Conduct before start Contributing.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Aaradhya Singh 
- GitHub Profile Link : https://github.com/kyra-09
- Email ID : aaradhyasinghgaur@gmail.com
- Participant ID (if applicable):
- Approach for this Project : I will use 5 different dl models suchas MobileNet , EfficientNetB1 , DenseNet121 etc. to classify between different medicinal plants and will modify them to beter accuracy by suing custom layers and use performance matrices to comapre between them to analyse the better model.

- What is your participant role? (Mention the Open Source program) - GSSOC-2024 Contributor

*************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by abhisheks008** [comment]
Assigned @kyra-09

**Comment by abhisheks008** [comment]
Hi @kyra-09 you have been already assigned to an issue. Please complete that first.

**Comment by kyra-09** [comment]
@abhisheks008 kindly assign this issue to me.

**Comment by abhisheks008** [comment]
Assigned @kyra-09

**Comment by kyra-09** [comment]
@abhisheks008 I think you mistakenly added wrong lable of "status : Approved"
