### ISSUE TITLE
feature: adding dark mode to web site

### ISSUE THREAD

**Issue by dnyandeepchute** [abhisheks008/DL-Simplified#747]
there will be a field(symbol) on right top corner for changing the mode of web to dark and again back to normal.

useful for the user as it help the user to use it and see content in better way and also useful for website as it gives a different look and experience.

using dark mode help user to-
Reduces eye strain
Gives a productivity boost
Saves battery life

Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by dnyandeepchute** [comment]
hey @abhisheks008 please assign this to me, thank you.

**Comment by abhisheks008** [comment]
Not required right now. Thanks for your interest.

Closing this issue as not required.
