### ISSUE TITLE
SARS COV 2 CT Scan Classification

### ISSUE THREAD

**Issue by abhisheks008** [abhisheks008/DL-Simplified#76]
### Deep Learning Simplified Repository (Proposing new issue)
:red_circle: **Project Title** : SARS COV 2 CT Scan Classification</br>
:red_circle: **Aim** : An image processing model to identify the images of SARS COV 2 affected patients.</br>
:red_circle: **Dataset** : https://www.kaggle.com/datasets/plameneduardo/sarscov2-ctscan-dataset</br>
:red_circle: **Approach** : Try to use 3-4 algorithms to implement the models and compare all the algorithms to find out the best fitted algorithm for the model by checking the accuracy scores. Also do not forget to do a exploratory data analysis before creating any model.

**********************************************************************************
### 📍 **Follow the Guidelines to Contribute in the Project :**
* You need to create a separate folder named as the Project Title.
* Inside that folder, there will be four main components.
   * Images - To store the required images.
   * Dataset - To store the dataset or, information/source about the dataset.
   * Model - To store the machine learning model you've created using the dataset.
   * `requirements.txt` - This file will contain the required packages/libraries to run the project in other machines.
* Inside the `Model` folder, the `README.md` file must be filled up properly, with proper visualizations and conclusions.

***********************************************************************
:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include issue number along with it.
- Follow Contributing Guidelines & Code of Conduct before start Contributing.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : 
- GitHub Profile Link : 
- Email ID :
- Participant ID (if applicable):
- Approach for this Project :
- What is your participant role? (Mention the Open Source program)

*************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by KushagraTomar** [comment]
SARS COV 2 CT Scan Classification #76
pls assign this to me

**Comment by abhisheks008** [comment]
Can you explain your approach please @KushagraTomar

**Comment by KushagraTomar** [comment]
tBasic Idea: thinking of using a predefined model like DenseNet or vgg16 if the model shows decent accuracy else I will need to create a CNN model  from scratch that performs well

https://github.com/KushagraTomar

**Comment by KushagraTomar** [comment]
???

**Comment by abhisheks008** [comment]
Sorry for the inconvenience caused, @KushagraTomar issue assigned to you. You can start working on it.

Best wishes 🚀

**Comment by KushagraTomar** [comment]
@abhisheks008 what exact changes are required

**Comment by abhisheks008** [comment]
I have commented there in the pull request check that.

**Comment by KushagraTomar** [comment]
hey,
I am sorry to bother you like you said you have commented on the issue in the pull request but I am still not able to see it... If possible can you reply here . It would be really help me

**Comment by abhisheks008** [comment]
Remove the `Heartbeat Classification using ECG/requirements.txt` file. This is causing a merging issue and your PR couldn't be merged unless and until you fix this.

@KushagraTomar
