### ISSUE TITLE
[Project Addition] Kidney Stone Images Classification

### ISSUE THREAD

**Issue by SayantikaLaskar** [abhisheks008/DL-Simplified#771]
🔴 Project Title : Kidney Stone Images Classification

🔴 Aim : The aim of this project is to classify the images given in the dataset using deep learning methods.

🔴 Dataset : https://www.kaggle.com/datasets/safurahajiheidari/kidney-stone-images

🔴 Approach : Creating models for multi-class classification task. using decision tree and random forest classsifier.

📍 Follow the Guidelines to Contribute in the Project :
You need to create a separate folder named as the Project Title.
Inside that folder, there will be four main components.
- Images - To store the required images.
- Dataset - To store the dataset or, information/source about the dataset.
- Model - To store the machine learning model you've created using the dataset.
- requirements.txt - This file will contain the required packages/libraries to run the project in other machines.
Inside the Model folder, the README.md file must be filled up properly, with proper visualizations and conclusions.

🔴🟡 Points to Note :

The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
"Issue Title" and "PR Title should be the same. Include issue number along with it.
Follow Contributing Guidelines & Code of Conduct before start Contributing.
✅ To be Mentioned while taking the issue :

Full name : Sayantika laskar
GitHub Profile Link :https://github.com/SayantikaLaskar
Email ID : [sayantikalaskar2002@gmail.com](mailto:sayantikalaskar2002@gmail.com)
Approach for this Project : Creating models for multi-class classification task. using decision tree and random forest classsifier.
What is your participant role? (Mention the Open Source program)
GSSoC 2024 Contributor
Happy Contributing 🚀

All the best. Enjoy your open source journey ahead. 😎

**Comment by SayantikaLaskar** [comment]
Hi @abhisheks008  I want to work on this issue. Please assign me this issue.

**Comment by abhisheks008** [comment]
What are models you are planning to implement here for this problem statement?
@SayantikaLaskar

**Comment by SayantikaLaskar** [comment]
I am planning to use extratree classifier, random forest and KNeighbors algorithms for the model @abhisheks008

**Comment by abhisheks008** [comment]
As this repo mainly focuses on deep learning methods, you should implement deep learning techniques rather than going with the machine learning methods.

**Comment by SayantikaLaskar** [comment]
I can work with CNN with the following dataset
https://www.kaggle.com/datasets/harshghadiya/kidneystone/code
Will it be okay?

**Comment by abhisheks008** [comment]
> I can work with CNN with the following dataset https://www.kaggle.com/datasets/harshghadiya/kidneystone/code Will it be okay? @abhisheks008

You need to implement 3-4 architectures for this dataset/problem statement.

**Comment by SayantikaLaskar** [comment]
Okay I am working on it. Thank you

**Comment by SayantikaLaskar** [comment]
I have done the model using CNN, VGG and resnet model. Kindly assign me the issue @abhisheks008

**Comment by abhisheks008** [comment]
> I have done the model using CNN, VGG and resnet model. Kindly assign me the issue @abhisheks008

Assigned @SayantikaLaskar
