### ISSUE TITLE
[Project Addition] :Real Time Sudoku Solver Using OpenCV

### ISSUE THREAD

**Issue by abckhush** [abhisheks008/DL-Simplified#774]
### Deep Learning Simplified Repository (Proposing new issue)
:red_circle: **Project Title** : Real Time Sudoku Solver Using OpenCV</br>
:red_circle: **Aim** : To solve sudoku in seconds.</br>
:red_circle: **Dataset** : Any Sudoku Image.</br>
:red_circle: **Approach** :  CNN and backtracking algorithm.

**********************************************************************************
### 📍 **Follow the Guidelines to Contribute in the Project :**
* You need to create a separate folder named as the Project Title.
* Inside that folder, there will be four main components.
   * Images - To store the required images.
   * Dataset - To store the dataset or, information/source about the dataset.
   * Model - To store the machine learning model you've created using the dataset.
   * `requirements.txt` - This file will contain the required packages/libraries to run the project in other machines.
* Inside the `Model` folder, the `README.md` file must be filled up properly, with proper visualizations and conclusions.

***********************************************************************
:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include issue number along with it.
- Follow Contributing Guidelines & Code of Conduct before start Contributing.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Khushi Kalra
- GitHub Profile Link : <a href="https://github.com/abckhush">abckhush</a>
- Email ID : kalra.khushi@outlook.comm
- Participant ID (if applicable):
- Approach for this Project : CNN  and Backtracking Algorithm
- What is your participant role? (Mention the Open Source program): GSSoC 2024 Contributor

*************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by abhisheks008** [comment]
This repo demands to implement at least 2-3 models for each and every problem statement.
What are the models you are planning for this?

**Comment by abckhush** [comment]
I could do one with backtracking algorithm (brute force), then optimize it in the next, and then develop using recursion when needed in the third. These could work on a dataset of 50 difficult sudoku that I have downloaded. The only thing here would be that I wouldn't use OpenCV. 
Would this be ok?

**Comment by abhisheks008** [comment]
As you are going to build this solver application, a web app should be there to showcase the working of the model you are going to implement. Are you up for this?

**Comment by abckhush** [comment]
A ReactJS website with minimal UI would work. 
1. If I am going to implement a web app, would I need to make different models?
2. Web App using OpenCV or manual entries of the sudoku?

**Comment by abhisheks008** [comment]
> A ReactJS website with minimal UI would work.
> 
> 1. If I am going to implement a web app, would I need to make different models?
> 2. Web App using OpenCV or manual entries of the sudoku?

Use the best model as the backend of the web app. This should be like this, user uploads an unsolved sudoku image and the model will solve the sudoku and show the user the correct result.

**Comment by abckhush** [comment]
How about I make a python application and, using the camera, user shows the image of the sudoku and using opencv it overlays the answers ?

**Comment by abhisheks008** [comment]
> How about I make a python application and, using the camera, user shows the image of the sudoku and using opencv it overlays the answers ?

Cool that will work too. Showing the implementation of the model is the priority for me from a layman's perspective.

**Comment by abckhush** [comment]
Ok. Can you assign me this issue then?

**Comment by abhisheks008** [comment]
Assigned @abckhush
