### ISSUE TITLE
[Project Addition]: Pet's Facial Expression Detection using DL

### ISSUE THREAD

**Issue by abckhush** [abhisheks008/DL-Simplified#776]
### Deep Learning Simplified Repository (Proposing new issue)
:red_circle: **Project Title** : Pet's Facial Expression Detection</br>
:red_circle: **Aim** : To identify the facial expressions of pet using images.</br>
:red_circle: **Dataset** : <a href="https://www.kaggle.com/datasets/anshtanwar/pets-facial-expression-dataset">Kaggle Dataset</a></br>
:red_circle: **Approach** : Using custom and pretrained CNN models.

**********************************************************************************
### 📍 **Follow the Guidelines to Contribute in the Project :**
* You need to create a separate folder named as the Project Title.
* Inside that folder, there will be four main components.
   * Images - To store the required images.
   * Dataset - To store the dataset or, information/source about the dataset.
   * Model - To store the machine learning model you've created using the dataset.
   * `requirements.txt` - This file will contain the required packages/libraries to run the project in other machines.
* Inside the `Model` folder, the `README.md` file must be filled up properly, with proper visualizations and conclusions.

***********************************************************************
:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include issue number along with it.
- Follow Contributing Guidelines & Code of Conduct before start Contributing.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Khushi Kalra
- GitHub Profile Link : <a href="https://github.com/abckhush">abckhush</a>
- Email ID : kalra.khushi@outlook.comm
- Participant ID (if applicable):
- Approach for this Project : Using custom and different CNN models.
- What is your participant role? (Mention the Open Source program): GSSoC 2024 Contributor

*************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by abhisheks008** [comment]
One issue at a time.

**Comment by abckhush** [comment]
Hi @abhisheks008. Can you assign me this issue now?

**Comment by abckhush** [comment]
Kindly assign me the issue

**Comment by abhisheks008** [comment]
What are the architectures you are following for this problem statement?

**Comment by abckhush** [comment]
ResNet-50, EfficientNet, ViT

**Comment by abckhush** [comment]
Hi @abhisheks008 could you pls assign me?

**Comment by abhisheks008** [comment]
Assigned @abckhush
