### ISSUE TITLE
Add dynamic year code in footer section

### ISSUE THREAD

**Issue by arpit4521** [abhisheks008/DL-Simplified#782]
![Screenshot 2024-06-11 221110](https://github.com/abhisheks008/DL-Simplified/assets/127679958/a1762188-ff13-4196-9bb3-dfec25a63059)

@abhisheks008 please assign me this under gssoc and apt level label

**Comment by abhisheks008** [comment]
This issue is not compatible with this repo's contributions.

Closing this issue.
