### ISSUE TITLE
titanic task on kaggle

### ISSUE THREAD

**Issue by nagamukesh** [abhisheks008/DL-Simplified#787]
### Deep Learning Simplified Repository (Proposing new issue)
:red_circle: **PROJECT TITLE** : Walk through to solve titanic task in kaggle</br>
:red_circle: **Aim** : to solve famous titanic task which is considered as a basic task to do to get a gist of machine learninig</br>
:red_circle: **Dataset** : kaggle dataset for titanic task(https://www.kaggle.com/competitions/titanic/data)</br>
:red_circle: **Approach** : Try to use 3-4 algorithms to implement the models and compare all the algorithms to find out the best fitted algorithm for the model by checking the accuracy scores. Also do not forget to do a exploratory data analysis before creating any model.

**********************************************************************************
### 📍 **Follow the Guidelines to Contribute in the Project :**
* You need to create a separate folder named as the Project Title.
* Inside that folder, there will be four main components.
   * Images - To store the required images.
   * Dataset - To store the dataset or, information/source about the dataset.
   * Model - To store the machine learning model you've created using the dataset.
   * `requirements.txt` - This file will contain the required packages/libraries to run the project in other machines.
* Inside the `Model` folder, the `README.md` file must be filled up properly, with proper visualizations and conclusions.

***********************************************************************
:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include issue number along with it.
- Follow Contributing Guidelines & Code of Conduct before start Contributing.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : konatham naga mukesh
- GitHub Profile Link : https://github.com/nagamukesh
- Email ID :konathamnagamukesh2005@gmail.com
- Participant ID (if applicable):
- Approach for this Project :I already completed the task and its just to get the dataset, clean the data,impute missing data, do feature engineering and pca and then build a model to predict whether the passenger survived or not in titanic
- What is your participant role? (Mention the Open Source program)
GSSOC 2024
*************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by abhisheks008** [comment]
What are the deep learning models you are planning to implement here for this problem statement?

**Comment by nagamukesh** [comment]
a neural network to train on the data

**Comment by abhisheks008** [comment]
> a neural network to train on the data

Can you elaborate on the problem statement and the approach for this project?

**Comment by ojaswichopra** [comment]
Please assign this issue to me. I will first begin with EDA, to understand the dataset's structure, identify missing values, and analyze feature distributions and relationships. Then I'll preprocess the data, which involves handling missing values, encoding categorical variables, engineering new features, and normalizing the data. Then I'll implement multiple machine learning algorithms, such as Logistic Regression, Decision Tree, Random Forest, and Support Vector Machine (SVM), to build predictive models. At last I'll evaluate each model  based on its accuracy score and confusion matrix, with cross-validation used to ensure robustness.

**Comment by abhisheks008** [comment]
Machine learning models will not work here. Need to focus and implement deep learning models.
