### ISSUE TITLE
spam ham detector 

### ISSUE THREAD

**Issue by nagamukesh** [abhisheks008/DL-Simplified#788]
### Deep Learning Simplified Repository (Proposing new issue)
:red_circle: **Project Title** : spam ham detector for SMSs</br>
:red_circle: **Aim** : to detect whether the given message is spam or ham using nlp techniques</br>
:red_circle: **Dataset** : SMS dataset(https://www.kaggle.com/datasets/uciml/sms-spam-collection-dataset)</br>
:red_circle: **Approach** : Try to use 3-4 algorithms to implement the models and compare all the algorithms to find out the best fitted algorithm for the model by checking the accuracy scores. Also do not forget to do a exploratory data analysis before creating any model.

**********************************************************************************
### 📍 **Follow the Guidelines to Contribute in the Project :**
* You need to create a separate folder named as the Project Title.
* Inside that folder, there will be four main components.
   * Images - To store the required images.
   * Dataset - To store the dataset or, information/source about the dataset.
   * Model - To store the machine learning model you've created using the dataset.
   * `requirements.txt` - This file will contain the required packages/libraries to run the project in other machines.
* Inside the `Model` folder, the `README.md` file must be filled up properly, with proper visualizations and conclusions.

***********************************************************************
:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include issue number along with it.
- Follow Contributing Guidelines & Code of Conduct before start Contributing.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : konatham naga mukesh
- GitHub Profile Link : https://github.com/nagamukesh
- Email ID :konathamnagamukesh2005@gmail.com
- Participant ID (if applicable):
- Approach for this Project :I will convert the text into sentences and then to words and then words to vectors using word2vec/bag of words etc techniques and then build a model to take these vectors as input and then predict whether these messages are spam or ham
- What is your participant role? (Mention the Open Source program)
GSSOC 2024
*************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by abhisheks008** [comment]
Already present in this repo.

Closing this issue as duplicate.
