### ISSUE TITLE
Analysis of Online Food Delivery Preferences

### ISSUE THREAD

**Issue by Nndna9** [abhisheks008/DL-Simplified#793]
### Deep Learning Simplified Repository (Proposing new issue)
:red_circle: **Project Title** : </br>Online Food Delivery Preferences
:red_circle: **Aim** : </br> Finding factors which are contributing to the demand of food delivery in the city.
:red_circle: **Dataset** : [</br>]https://www.kaggle.com/datasets/benroshan/online-food-delivery-preferencesbangalore-region?resource=download
:red_circle: **Approach** : Exploratory data analysis and implementation of 5 models. 

**********************************************************************************
### 📍 **Follow the Guidelines to Contribute in the Project :**
* You need to create a separate folder named as the Project Title.
* Inside that folder, there will be four main components.
   * Images - To store the required images.
   * Dataset - To store the dataset or, information/source about the dataset.
   * Model - To store the machine learning model you've created using the dataset.
   * `requirements.txt` - This file will contain the required packages/libraries to run the project in other machines.
* Inside the `Model` folder, the `README.md` file must be filled up properly, with proper visualizations and conclusions.

***********************************************************************
:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include issue number along with it.
- Follow Contributing Guidelines & Code of Conduct before start Contributing.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Nandana Santhosh
- GitHub Profile Link :  github.com/Nndna9
- Email ID : nndna9@gmail.com
- Participant ID (if applicable): 
- Approach for this Project : Exploratory data analysis- Univariate, Bivariate and Multivariate
Geospatial Analysis, time factor Analysis , Models - Logistic Regression model
Decision Tree model
Random Forest Classifier model
kNNClassifier model
Naive Bayes Classifier model
- What is your participant role? GSSOC

*************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Nidhi-Satyapriya** [comment]
hi @Nndna9 , please assign this issue to me  with an appropriate level tag

**Comment by Nndna9** [comment]
> hi @Nndna9 , please assign this issue to me with an appropriate level tag

Hey , I'd actually like to work on this.

Thank you.

**Comment by abhisheks008** [comment]
What is the parameter you are planning to predict here? Can you elaborate more on your approach.

**Comment by Nndna9** [comment]
Here using the data we're trying to different EDAs along with Geospatial and Time factor Analysis. As this is my first open source contribution I'd like to start with this the main aim of this is to help beginners understand different EDAs.

Thank you

**Comment by abhisheks008** [comment]
> Here using the data we're trying to different EDAs along with Geospatial and Time factor Analysis. As this is my first open source contribution I'd like to start with this the main aim of this is to help beginners understand different EDAs.
> 
> Thank you

Cool I understand the analysis part. Is there any involvement of deep learning models in this project?

**Comment by Nndna9** [comment]
Actually I was planning to do only the EDA, but now I'll use Logistic Regression model
Decision Tree model 
Random Forest Classifier model
kNNClassifier model 
Naive Bayes Classifier model and taking their accuracies.

**Comment by abhisheks008** [comment]
> Actually, I was planning to do only the EDA, but now I'll use Logistic Regression model Decision Tree model Random Forest Classifier model kNN Classifier model Naive Bayes Classifier model .

Analysis part is okay. But as this project repository demands deep learning models, you need to focus on deep learning methods.

**Comment by Pratzybha** [comment]
Deep Learning Simplified Repository (Proposing new issue)
->Project Title : Online Food Delivery Preferences
-> Aim : Finding factors which are contributing to the demand of food delivery in the city.
->Dataset : https://www.kaggle.com/datasets/benroshan/online-food-delivery-preferencesbangalore-region?resource=download
->Approach : 

1)Data Preprocessing:

Handle missing values, duplicate entries, and outliers.
Normalize and encode categorical data for modeling.

2)Exploratory Data Analysis (EDA):

Use Pandas, Matplotlib, and Seaborn for statistical analysis and visualizations.
Correlation analysis between features like delivery time, location, and ratings.

3)Deep Learning Models:

Model 1: RNN or Transformer-based Model for user behavior prediction.
Model 2: Recommendation System using embeddings to recommend popular food items.
Model 3: LSTM for Time Series Forecasting to predict demand and optimize resource allocation.

4)Model Evaluation:

Use MAE, RMSE for time series models.
Use accuracy, precision, and recall metrics for classification tasks.
Compare deep learning models with simpler baselines (like logistic regression) to justify the complexity.

**Comment by abhisheks008** [comment]
Assigning this issue to you @Pratzybha
