### ISSUE TITLE
Automated Essay Scores 

### ISSUE THREAD

**Issue by Salma-Mamdoh** [abhisheks008/DL-Simplified#794]
---

🔴 **Project Title**: Automated Essay Scoring with Deep Learning Models

🔴 **Aim**: Develop deep learning models to automatically score student essays, aiming to reduce grading time and provide consistent feedback.

🔴 **Dataset**: Utilize the provided dataset of student essays aligned with educational standards 
https://www.kaggle.com/competitions/learning-agency-lab-automated-essay-scoring-2/data

🔴 **Approach**: Perform exploratory data analysis (EDA) on the dataset to understand its characteristics and prepare it for modeling. Implement 3-4 deep learning algorithms such as LSTM, GRU, Transformer, and possibly others. Compare these algorithms based on their performance metrics, particularly focusing on metrics like quadratic weighted kappa for evaluation.

**********************************************************************************

### 📍 **Follow the Guidelines to Contribute in the Project:**
* Create a separate folder named "Automated Essay Scoring" under the main repository.
* Inside the "Automated Essay Scoring" folder, include the following components:
   * **Images**: For any necessary visualizations or diagrams.
   * **Dataset**: Store the dataset or provide information/source about the dataset.
   * **Model**: Implement machine learning models using the dataset.
   * **requirements.txt**: List required packages/libraries for project replication.
* Inside the `Model` folder, ensure the `README.md` file is filled with visualizations and conclusions.

**********************************************************************************

🔴🟡 **Points to Note:**

- Issues are assigned on a first-come, first-serve basis; 1 Issue == 1 Pull Request (PR).
- Issue Title and PR Title should be identical, including the issue number.
- Follow Contributing Guidelines & Code of Conduct before starting to contribute.

**********************************************************************************

✅ **To be Mentioned while taking the issue:**
- **Full name**: Salma Mamdoh Sabry
- **GitHub Profile Link**: https://github.com/Salma-Mamdoh
- **Email ID**: smmdwh985@gmail.com
- **Participant ID (if applicable)**: [NA or mention if applicable]
- **Approach for this Project**: Perform EDA, implement LSTM, GRU, and Transformer models and compare their performance using metrics like quadratic weighted kappa.
- **What is your participant role?**: GSSoC'24 | Contributor

*************************************************************
Happy Contributing! 🚀

All the best. Enjoy your open source journey ahead. 😎

**Comment by Salma-Mamdoh** [comment]
@abhisheks008 , 👋 Hey bro can you please assign me this issue under GSSoC'24 with an appropriate level tag

**Comment by abhisheks008** [comment]
Can you please the models you are planning to implement for this problem statement?

Mention at least 3-4 models for this project.

**Comment by ojaswichopra** [comment]
Please assign this issue to me

**Comment by ojaswichopra** [comment]
I am planning to try 
Long Short-Term Memory (LSTM) Network, Gated Recurrent Unit (GRU) Network, Transformer Model and Convolutional Neural Network (CNN) for Text

**Comment by abhisheks008** [comment]
Hi @ojaswichopra based on your approach this issue is assigned to you.
