### ISSUE TITLE
 Implementing Workflow for Closing Old Issues

### ISSUE THREAD

**Issue by thevijayshankersharma** [abhisheks008/DL-Simplified#797]
This feature proposes the establishment of a workflow for automatically closing old issues within the project management system. The workflow aims to declutter the issue tracker, maintain its relevance, and ensure that active tasks receive appropriate attention.

**Comment by abhisheks008** [comment]
Not required.

**Comment by thevijayshankersharma** [comment]
@abhisheks008 in future if you need for auto comment on closing the PR or any other workflow then let me know. I would like to make.
