### ISSUE TITLE
Bank customer Segementation

### ISSUE THREAD

**Issue by adityasingh-0803** [abhisheks008/DL-Simplified#809]
We can make bank customer segmentation using k means dbscan as we can get segregation of customers on the basis of income daily wage spend etc. I will do the needful kindly assign with necessary labels

**Comment by abhisheks008** [comment]
> We can make bank customer segmentation using k means dbscan as we can get segregation of customers on the basis of income daily wage spend etc. I will do the needful kindly assign with necessary labels

Share the details of the proposed issue as per the given issue template.

**Comment by adityasingh-0803** [comment]
Evaluate the quality of clusters using internal metrics (e.g., silhouette score) or external metrics if ground truth labels are available.
Compare the results of K-means and DBSCAN to see which algorithm provides better insights for your specific task

**Comment by abhisheks008** [comment]
Simple machine learning models won't work here.

Thanks for showing your interest. Closing this issue as not required.
