### ISSUE TITLE
Gen 1 Pokemon Classification using Deep Learning

### ISSUE THREAD

**Issue by RajKhanke** [abhisheks008/DL-Simplified#816]
Deep Learning Simplified Repository (Proposing new issue)
🔴 Project Title : Pokémon classification using Deep learning
🔴 Aim : To  classify 150 different Pokémon species of gen1 based on 7000+ labelled image dataset
🔴 Dataset : https://www.kaggle.com/datasets/lantian773030/pokemonclassification
🔴 Approach :

Algorithms :-

1) CNN
2) VGG16
3) Inception

📍 Follow the Guidelines to Contribute in the Project :
You need to create a separate folder named as the Project Title.
Inside that folder, there will be four main components.
Images - To store the required images.
Dataset - To store the dataset or, information/source about the dataset.
Model - To store the machine learning model you've created using the dataset.
requirements.txt - This file will contain the required packages/libraries to run the project in other machines.
Inside the Model folder, the README.md file must be filled up properly, with proper visualizations and conclusions.
🔴🟡 Points to Note :

The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
"Issue Title" and "PR Title should be the same. Include issue number along with it.
Follow Contributing Guidelines & Code of Conduct before start Contributing.
✅ To be Mentioned while taking the issue :

Full name : Raj Khanke
GitHub Profile Link : https://github.com/RajKhanke
Email ID : rajvkhanke@gmail.com
Participant ID (if applicable): -
Approach for this Project : CNN
What is your participant role? (Mention the Open Source program) GSSoC'24 Contributor
Happy Contributing 🚀

All the best. Enjoy your open source journey ahead. 😎

**Comment by RajKhanke** [comment]
@abhisheks008 please assign this issue to me along with label and level

**Comment by abhisheks008** [comment]
You can start working on it. Assigned this issue to you @RajKhanke

**Comment by Pratzybha** [comment]
@abhisheks008 I would like to work on this project. Please assign it to me.
