### ISSUE TITLE
Animal Classification [New issue]

### ISSUE THREAD

**Issue by SayantikaLaskar** [abhisheks008/DL-Simplified#817]
Deep Learning Simplified Repository (Proposing new issue)
🔴 Project Title : Animals Classification

🔴 Aim : Create a DL model which will classify 5 categories of animals: cats, dogs, elephants, horses & lions.

🔴 Dataset : [Animals classification dataset](https://www.kaggle.com/datasets/antobenedetti/animals)

🔴 Approach : Try to use 3-4 algorithms to implement the models and compare all the algorithms to find out the best fitted algorithm for the model by checking the accuracy scores. Also do not forget to do a exploratory data analysis before creating any model.(VGG, CNN, ResNet)

📍 Follow the Guidelines to Contribute in the Project :
You need to create a separate folder named as the Project Title.
Inside that folder, there will be four main components.
Images - To store the required images.
Dataset - To store the dataset or, information/source about the dataset.
Model - To store the machine learning model you've created using the dataset.
requirements.txt - This file will contain the required packages/libraries to run the project in other machines.
Inside the Model folder, the README.md file must be filled up properly, with proper visualizations and conclusions.
🔴🟡 Points to Note :

The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
"Issue Title" and "PR Title should be the same. Include issue number along with it.
Follow Contributing Guidelines & Code of Conduct before start Contributing.
✅ To be Mentioned while taking the issue :

Full name : Sayantika Laskar
GitHub Profile Link : https://github.com/SayantikaLaskar
Email ID : sayantikalaskar2002@gmail.com
Participant ID (if applicable): GSSoC 2024 participant
Approach for this Project : Try to use 3-4 algorithms to implement the models and compare all the algorithms to find out the best fitted algorithm for the model by checking the accuracy scores. Also do not forget to do a exploratory data analysis before creating any model.(VGG, CNN, ResNet)
What is your participant role?

GSSoC 2024 participant

Happy Contributing 🚀

All the best. Enjoy your open source journey ahead. 😎

**Comment by abhisheks008** [comment]
This type of problem statement is already present in this repository.
@SayantikaLaskar
