### ISSUE TITLE
[PROJECT ADDITION] Autism Identification System

### ISSUE THREAD

**Issue by pavitraag** [abhisheks008/DL-Simplified#833]
### Deep Learning Simplified Repository (Proposing new issue)
:red_circle: **Autism Identification System** : </br>
:red_circle: **Aim** : This project aims to address the need for a time-efficient and accessible ASD screening tool using machine learning techniques.</br>

***********************************************************************
:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include issue number along with it.
- Follow Contributing Guidelines & Code of Conduct before start Contributing.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Pavitraa G
- GitHub Profile Link : @pavitraag
- Email ID :pavitraagopi@gmail.com
- What is your participant role? GSSOC 24 Contributor

**Comment by abhisheks008** [comment]
Hi @pavitraag can you share the dataset URL and the models you are planning to implement here?

**Comment by pavitraag** [comment]
Models used are:

Logistic Regression

Support Vector Machine

Random Forest Classifier

**Comment by abhisheks008** [comment]
> Models used are:
> 
> 1. Logistic Regression
> 2. Support Vector Machine
> 3. Random Forest Classifier
> 
> Data
> 
> [Data.csv](https://github.com/user-attachments/files/16118573/Data.csv)

Machine learning models will not work here, you need to implement deep learning models for this problem statement.

Looking forward to hearing from you.

**Comment by pavitraag** [comment]
I would like to add ANN model in it

**Comment by abhisheks008** [comment]
> @abhisheks008 I would like to add ANN model in it

Need to be brief with the proposed approach. At least add 3-4 deep learning arechitectures for this problem statement.
