### ISSUE TITLE
Human Detection using Deep Learning

### ISSUE THREAD

**Issue by SayantikaLaskar** [abhisheks008/DL-Simplified#839]
Deep Learning Simplified Repository (Proposing new issue)
🔴 Project Title :
 Human Detection using Deep Learning
🔴 Aim :
 To build a deep learning model that can analyze human using CCTV footage, etc.
🔴 Dataset :
 Datasets available for human detection in Kaggle
🔴 Approach : Try to use 3-4 algorithms to implement the models and compare all the algorithms to find out the best fitted algorithm for the model by checking the accuracy scores. Also do not forget to do a exploratory data analysis before creating any model.

📍 Follow the Guidelines to Contribute in the Project :
You need to create a separate folder named as the Project Title.
Inside that folder, there will be four main components.
Images - To store the required images.
Dataset - To store the dataset or, information/source about the dataset.
Model - To store the machine learning model you've created using the dataset.
requirements.txt - This file will contain the required packages/libraries to run the project in other machines.
Inside the Model folder, the README.md file must be filled up properly, with proper visualizations and conclusions.
🔴🟡 Points to Note :

The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
"Issue Title" and "PR Title should be the same. Include issue number along with it.
Follow Contributing Guidelines & Code of Conduct before start Contributing.
✅ To be Mentioned while taking the issue :

Full name : Sayantika Laskar
GitHub Profile Link : https://github.com/SayantikaLaskar
Email ID : [sayantikalaskar2002@gmail.com](mailto:sayantikalaskar2002@gmail.com)
Participant ID (if applicable): GSSoC'24 Participant
Approach for this Project : Try to use 3-4 algorithms to implement the models and compare all the algorithms to find out the best fitted algorithm for the model by checking the accuracy scores. Also do not forget to do a exploratory data analysis before creating any model.
Load the Dataset
Exploratory Data Analysis (EDA): Visualise common patterns and features in audio signals.
Feature Extraction: Extract features such as MFCC, Chroma, Mel Spectrogram, etc.
Model Implementation: Convolutional Neural Network (CNN) , Xception, ResNet50, VGG16
Train and Evaluate Each Model
Compare Performance using accuracy and loss metrics.
What is your participant role? (Mention the Open Source program) 
GSSoC'24 participant
Happy Contributing 🚀

All the best. Enjoy your open source journey ahead. 😎

**Comment by abhisheks008** [comment]
Already present in this repository. Closing this issue as duplicate.
