### ISSUE TITLE
Military Aircraft Detection

### ISSUE THREAD

**Issue by abhisheks008** [abhisheks008/DL-Simplified#84]
### Deep Learning Simplified Repository (Proposing new issue)
:red_circle: **Project Title** : Military Aircraft Detection</br>
:red_circle: **Aim** : Create a model which will idenitfy the aircrafts of Military forces and commercial ones.</br>
:red_circle: **Dataset** : https://www.kaggle.com/datasets/a2015003713/militaryaircraftdetectiondataset</br>
:red_circle: **Approach** : Try to use 3-4 algorithms to implement the models and compare all the algorithms to find out the best fitted algorithm for the model by checking the accuracy scores. Also do not forget to do a exploratory data analysis before creating any model.

**********************************************************************************
### 📍 **Follow the Guidelines to Contribute in the Project :**
* You need to create a separate folder named as the Project Title.
* Inside that folder, there will be four main components.
   * Images - To store the required images.
   * Dataset - To store the dataset or, information/source about the dataset.
   * Model - To store the machine learning model you've created using the dataset.
   * `requirements.txt` - This file will contain the required packages/libraries to run the project in other machines.
* Inside the `Model` folder, the `README.md` file must be filled up properly, with proper visualizations and conclusions.

***********************************************************************
:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include issue number along with it.
- Follow Contributing Guidelines & Code of Conduct before start Contributing.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : 
- GitHub Profile Link : 
- Email ID :
- Participant ID (if applicable):
- Approach for this Project :
- What is your participant role? (Mention the Open Source program)

*************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by mridulpal019** [comment]
Hey @abhisheks008, I'd like to try this.

Full name: Mridul Kumar Pal
GitHub Profile Link : https://github.com/mridulpal019
Email ID : mridulpal19@gmail.com
Approach for this Project: I will try to it by using neural network (CNN).
Participant role : SSOC - 2022

**Comment by abhisheks008** [comment]
Issue assigned to you @mridulpal019 

Try to use more than 3 models and compare them to get the better model for this project using the accuracy scores.

**Comment by abhisheks008** [comment]
Updates please @mridulpal019

**Comment by mridulpal019** [comment]
@abhisheks008 
Hi,
Sorry actually I caught in some lab practicals  and project of the  college.. and as this week I have my exams going.. So you can unassign the issue as of now.. and as soon as I got free... I will contribute to some other issue.
Thanks.

**Comment by abhisheks008** [comment]
As you wish @mridulpal019. Hope to see you soon again.

**Comment by guptaaryan16** [comment]
Hey this is Aryan Gupta,
GitHub Profile Link : https://github.com/guptaaryan16
Email ID : [guptaaryan16@gmail.com](mailto:guptaaryan16@gmail.com)
Participant ID (if applicable): Not available
Approach for this Project : 
I would like to work on this by using neural network architectures like ResNet, EfficientNet and GoogleNet as this is a heavy dataset and I need some effective algorithms in order to classify the dataset into different aircrafts.

**Comment by abhisheks008** [comment]
Complete the required changes in the previous PR first, then start you can be able start working with this. @guptaaryan16

**Comment by guptaaryan16** [comment]
Hey can you assign this to me

**Comment by abhisheks008** [comment]
Issue assigned to you @guptaaryan16. You can start working on it.
