### ISSUE TITLE
[Project Addition]: Tesla Historic Stock Price Analysis

### ISSUE THREAD

**Issue by abckhush** [abhisheks008/DL-Simplified#845]
### Deep Learning Simplified Repository (Proposing new issue)
:red_circle: **Project Title** : Tesla Historic Stock Price Analysis
:red_circle: **Aim** : o predict the future stock prices of Tesla using deep learning models
:red_circle: **Dataset** : https://www.kaggle.com/datasets/muhammadibrahimqasmi/tesla-stock-insights-and-predictions/data
:red_circle: **Approach** : 
1. GRU
2. BiGRU

**********************************************************************************
### 📍 **Follow the Guidelines to Contribute in the Project :**
* You need to create a separate folder named as the Project Title.
* Inside that folder, there will be four main components.
   * Images - To store the required images.
   * Dataset - To store the dataset or, information/source about the dataset.
   * Model - To store the machine learning model you've created using the dataset.
   * `requirements.txt` - This file will contain the required packages/libraries to run the project in other machines.
* Inside the `Model` folder, the `README.md` file must be filled up properly, with proper visualizations and conclusions.

***********************************************************************
:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include issue number along with it.
- Follow Contributing Guidelines & Code of Conduct before start Contributing.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name :  Khushi Kalra
- GitHub Profile Link : https://www.github.com/abckhush
- Email ID : kalra.khushi@outlook.com
- Participant ID (if applicable):
- Approach for this Project : GRU
- What is your participant role? (Mention the Open Source program) GSSoC'24 Contributor

*************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by abhisheks008** [comment]
Need to implement at least one more model @abckhush

**Comment by abckhush** [comment]
I think the dataset has been made private. I worked with this dataset on only these two models. If it's ok, I'll upload those two only.

**Comment by abhisheks008** [comment]
Then it'll go with level 2 tag. hope this will be okay with you.

**Comment by abckhush** [comment]
Yeah sure.

**Comment by abhisheks008** [comment]
Assigned @abckhush
