### ISSUE TITLE
[Project Addition]: Apple Stock Price Prediction Based On 40 Years Data

### ISSUE THREAD

**Issue by abckhush** [abhisheks008/DL-Simplified#850]
### Deep Learning Simplified Repository (Proposing new issue)
:red_circle: **Project Title** : Apple Stock Price from 1980-2021
:red_circle: **Aim** : To predict the stock prices of Tesla using deep learning models
:red_circle: **Dataset** : https://www.kaggle.com/datasets/meetnagadia/apple-stock-price-from-19802021/data
:red_circle: **Approach** : 
1. LSTM
2. LSTM+CONV1D
3. Time Series Analysis using the Prophet Model

**********************************************************************************
### 📍 **Follow the Guidelines to Contribute in the Project :**
* You need to create a separate folder named as the Project Title.
* Inside that folder, there will be four main components.
   * Images - To store the required images.
   * Dataset - To store the dataset or, information/source about the dataset.
   * Model - To store the machine learning model you've created using the dataset.
   * `requirements.txt` - This file will contain the required packages/libraries to run the project in other machines.
* Inside the `Model` folder, the `README.md` file must be filled up properly, with proper visualizations and conclusions.

***********************************************************************
:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include issue number along with it.
- Follow Contributing Guidelines & Code of Conduct before start Contributing.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name :  Khushi Kalra
- GitHub Profile Link : https://www.github.com/abckhush
- Email ID : kalra.khushi@outlook.com
- Participant ID (if applicable):
- Approach for this Project : LSTM
- What is your participant role? (Mention the Open Source program) GSSoC'24 Contributor
*************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by abhisheks008** [comment]
Updated the project name a bit. Make sure you use the same name of the project in your contribution.

Assigned @abckhush
