### ISSUE TITLE
Deepfake Videos and Images Detector using DL

### ISSUE THREAD

**Issue by anushka29github** [abhisheks008/DL-Simplified#853]
### Deep Learning Simplified Repository (Proposing new issue)
:red_circle: **Project Title** : Deepfake Detection : </br>
:red_circle:  **Aim** :  To develop and compare multiple machine learning models to detect deepfake videos/images.: </br>
:red_circle: **Dataset ** : https://www.kaggle.com/datasets/manjilkarki/deepfake-and-real-images : </br>
:red_circle: **Approach** : 
1. CNN
2. CapsNets

**********************************************************************************
### 📍 **Follow the Guidelines to Contribute in the Project :**
* You need to create a separate folder named as the Project Title.
* Inside that folder, there will be four main components.
   * Images - To store the required images.
   * Dataset - To store the dataset or, information/source about the dataset.
   * Model - To store the machine learning model you've created using the dataset.
   * `requirements.txt` - This file will contain the required packages/libraries to run the project in other machines.
* Inside the `Model` folder, the `README.md` file must be filled up properly, with proper visualizations and conclusions.

***********************************************************************
:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include issue number along with it.
- Follow Contributing Guidelines & Code of Conduct before start Contributing.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name :  Anushka Ray
- GitHub Profile Link : https://github.com/anushka29github
- Email ID : rayanushka29@gmail.com
- Participant ID (if applicable):
- Approach for this Project : CNN
- What is your participant role? (Mention the Open Source program) GSSoC'24 Contributor

*************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by abhisheks008** [comment]
Hi @anushka29github need to implement 3 models at least for any project.

**Comment by abhisheks008** [comment]
Assigned @zul132

**Comment by zul132** [comment]
@abhisheks008 Hey I accidently created a PR from my project's branch to the main of my forked repo. I have closed that PR now and created a new PR to your repository's main branch. I don't think this will cause any issues now but I wanted to inform you just in case.
