### ISSUE TITLE
Attendance Management System using Face Recognition

### ISSUE THREAD

**Issue by ShraddhaSabde** [abhisheks008/DL-Simplified#854]
### Deep Learning Simplified Repository (Proposing new issue)
:red_circle: **Project Title** : Face Recognition using Deep Learning for Attendance Management System.</br>
:red_circle: **Aim** : I want to add Deep Learning Project - Face Recognition For Attendance Management System. please accept this issue. </br>
:red_circle: **Dataset** : Own dataset</br>
:red_circle: **Approach** : The implementation of a Facial Recognition System can aid in identifying or verifying a
person's identity from a digital image. Accurate attendance records are vital to classroom evaluation.
However, manual attendance tracking can result in errors, missed students, or duplicate entries. The
adoption of the Face Recognition-based attendance system could help eliminate these shortcomings.

**********************************************************************************
### 📍 **Follow the Guidelines to Contribute in the Project :**
* You need to create a separate folder named as the Project Title.
* Inside that folder, there will be four main components.
   * Images - To store the required images.
   * Dataset - To store the dataset or, information/source about the dataset.
   * Model - To store the machine learning model you've created using the dataset.
   * `requirements.txt` - This file will contain the required packages/libraries to run the project in other machines.
* Inside the `Model` folder, the `README.md` file must be filled up properly, with proper visualizations and conclusions.

***********************************************************************
:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include issue number along with it.
- Follow Contributing Guidelines & Code of Conduct before start Contributing.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Shraddha Vikas Sabde
- GitHub Profile Link : https://github.com/ShraddhaSabde
- Email ID : shraddhavsabde@gmail.com
- Participant ID (if applicable):
- Approach for this Project :
![face1](https://github.com/user-attachments/assets/7485a398-b0bd-496b-82ab-d81f857f722d)
![face2](https://github.com/user-attachments/assets/22e34a63-c6f8-48fd-893c-b50dd330ec60)

- What is your participant role? (Mention the Open Source program)

*************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by ShraddhaSabde** [comment]
Please assign this issue to me, I want to work on it.

**Comment by abhisheks008** [comment]
I have updated the issue name. Please follow the same while contributing. Assigned to you @ShraddhaSabde

**Comment by abhisheks008** [comment]
> I have updated the issue name. Please follow the same while contributing. Assigned to you @ShraddhaSabde

Make sure you implement 3 deep learning models for this problem statement. And use the best fitted model for the final implementation of the project. Showcase all the model implementations in the Jupyter Notebook file.

**Comment by ShraddhaSabde** [comment]
Sir actually I have made this project, but I have only used 1 DL model i.e. CNN so, I can only implement it.
but I will try to implement others also, till then Can You consider only this one.

**Comment by abhisheks008** [comment]
> Sir actually I have made this project, but I have only used 1 DL model i.e. CNN so, I can only implement it. but I will try to implement others also, till then Can You consider only this one.

For contributing in this repository you need to showcase the implementations of three models at least. Implementing one model could not able to find out the best fitted model among the existing ones.

If you are unable to implement two more models then you will only get Level 1 tag for the whole contribution.

**Comment by ShraddhaSabde** [comment]
ok sir I will try to make it in all 3 models
