### ISSUE TITLE
Sarcasm Detection For Cross Domain Applications.

### ISSUE THREAD

**Issue by ShraddhaSabde** [abhisheks008/DL-Simplified#855]
### Deep Learning Simplified Repository (Proposing new issue)
:red_circle: **Project Title** : Sarcasm Detection For Cross Domain Applications. </br>
:red_circle: **Aim** : Implement Sarcasm Detection in Cross Domain Applications</br>
:red_circle: **Dataset** : </br>
:red_circle: **Approach** : Sarcasm Detection in Cross Domain Applications
This project proposes the accuracy and efficiency of ML and NN models trained on one dataset and tested on other dataset. SARC dataset is used for training and amazon review dataset is used for testing the models. This enables Sarcasm detection on Cross Domain applications.

**********************************************************************************
### 📍 **Follow the Guidelines to Contribute in the Project :**
* You need to create a separate folder named as the Project Title.
* Inside that folder, there will be four main components.
   * Images - To store the required images.
   * Dataset - To store the dataset or, information/source about the dataset.
   * Model - To store the machine learning model you've created using the dataset.
   * `requirements.txt` - This file will contain the required packages/libraries to run the project in other machines.
* Inside the `Model` folder, the `README.md` file must be filled up properly, with proper visualizations and conclusions.

***********************************************************************
:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include issue number along with it.
- Follow Contributing Guidelines & Code of Conduct before start Contributing.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Shraddha Vikas Sabde
- GitHub Profile Link : https://github.com/ShraddhaSabde
- Email ID : shraddhavsabde@gmail.com
- Participant ID (if applicable):
- Approach for this Project : This project proposes the accuracy and efficiency of ML and NN models trained on one dataset and tested on other dataset. SARC dataset is used for training and amazon review dataset is used for testing the models. This enables Sarcasm detection on Cross Domain applications.
- What is your participant role? (Mention the Open Source program)

*************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by ShraddhaSabde** [comment]
Please assign this issue to me, I want to work on this issue.

**Comment by abhisheks008** [comment]
One issue at a time.
