### ISSUE TITLE
[Project Addition]: Housing Price Prediction 

### ISSUE THREAD

**Issue by Sanjeev-Kumar78** [abhisheks008/DL-Simplified#862]
### Deep Learning Simplified Repository (Proposing new issue)
:red_circle: **Project Title** : Housing Price Prediction </br>
:red_circle: **Aim** : Predict housing prices using linear regression, random forests, and XGBoost, and compare the models to find the best-performing one.</br>
:red_circle: **Dataset** : [Link](https://docs.google.com/spreadsheets/d/1caaR9pT24GNmq3rDQpMiIMJrmiTGarbs/edit?gid=1150341366#gid=1150341366) </br>
:red_circle: **Approach** : Perform exploratory data analysis (EDA) to understand the dataset, followed by implementing and comparing linear regression, random forests, and XGBoost models. Evaluate the models based on accuracy scores and select the best one.

**********************************************************************************
### 📍 **Follow the Guidelines to Contribute in the Project :**
* You need to create a separate folder named as the Project Title.
* Inside that folder, there will be four main components.
   * Images - To store the required images.
   * Dataset - To store the dataset or, information/source about the dataset.
   * Model - To store the machine learning model you've created using the dataset.
   * `requirements.txt` - This file will contain the required packages/libraries to run the project in other machines.
* Inside the `Model` folder, the `README.md` file must be filled up properly, with proper visualizations and conclusions.

***********************************************************************
:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include issue number along with it.
- Follow Contributing Guidelines & Code of Conduct before start Contributing.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Sanjeev Kumar
- GitHub Profile Link : https://github.com/Sanjeev-Kumar78
- Email ID : sanjeev-kumar78@outlook.com
- What is your participant role? 
**Contributor role in GSSOC'24**

*************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by abhisheks008** [comment]
Hi @Sanjeev-Kumar78 machine learning models will not work here, you need to implement deep learning architectures for this project repository.

Closing this issue as not planned.
