### ISSUE TITLE
Plant disease classification

### ISSUE THREAD

**Issue by MohanRocks999** [abhisheks008/DL-Simplified#864]
### Deep Learning Simplified Repository (Proposing new issue)
:red_circle: **Project Title** : Plant leaf disease Classification</br>
:red_circle: **Aim** : To classify healthy and diseased plant leaves</br>
:red_circle: **Dataset** : https://www.kaggle.com/datasets/vipoooool/new-plant-diseases-dataset/ </br>
:red_circle: **Approach** : using 4 different types of networks Xception,EfficientViT, MobileNetV4 and EfficientnetV2 for classification.  The images will be augmented and processed before training. The dataset has around 38,000 images and has splits for training and validation. The plants covered include apple, blueberry, cherry, corn, grapes, orange, peach, potato, pepper, raspberry, soy bean, strawberry and tomato

**********************************************************************************
### 📍 **Follow the Guidelines to Contribute in the Project :**
* You need to create a separate folder named as the Project Title.
* Inside that folder, there will be four main components.
   * Images - To store the required images.
   * Dataset - To store the dataset or, information/source about the dataset.
   * Model - To store the machine learning model you've created using the dataset.
   * `requirements.txt` - This file will contain the required packages/libraries to run the project in other machines.
* Inside the `Model` folder, the `README.md` file must be filled up properly, with proper visualizations and conclusions.

***********************************************************************
:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include issue number along with it.
- Follow Contributing Guidelines & Code of Conduct before start Contributing.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Mohana Krishna
- GitHub Profile Link : https://github.com/MohanRocks999
- Email ID : www.mohanakrishna123@gmail.com
- Participant ID (if applicable):
- What is your participant role? (Mention the Open Source program) GSSoC 2024

*************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by abhisheks008** [comment]
Hi @MohanRocks999 thanks for coming up with a new issue. But this type of issues are already present in the repository hence I am not going with this issue.

Closing this isse as not planned.
