### ISSUE TITLE
Chest Cancer Detection using DL 

### ISSUE THREAD

**Issue by Amarta113** [abhisheks008/DL-Simplified#878]
### Deep Learning Simplified Repository (Proposing new issue)
:red_circle: **Chest Caner Detection** : </br>
:red_circle: **Addition of DL new project** : </br>
:red_circle: **Dataset :** [link](https://www.kaggle.com/datasets/mohamedhanyyy/chest-ctscan-images/data)  : </br>
:red_circle: **Approach: CNN, MLP, AutoEncoder** : Try to use 3-4 algorithms to implement the models and compare all the algorithms to find out the best fitted algorithm for the model by checking the accuracy scores. Also do not forget to do a exploratory data analysis before creating any model.

**********************************************************************************
### 📍 **Follow the Guidelines to Contribute in the Project :**
* You need to create a separate folder named as the Project Title.
* Inside that folder, there will be four main components.
   * Images - To store the required images.
   * Dataset - To store the dataset or, information/source about the dataset.
   * Model - To store the machine learning model you've created using the dataset.
   * `requirements.txt` - This file will contain the required packages/libraries to run the project in other machines.
* Inside the `Model` folder, the `README.md` file must be filled up properly, with proper visualizations and conclusions.

***********************************************************************
:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include issue number along with it.
- Follow Contributing Guidelines & Code of Conduct before start Contributing.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Amarta Waghani
- GitHub Profile Link : https://github.com/Amarta113
- Email ID : amartawaghani@gmail.com
- Participant ID (if applicable): no
- Approach for this Project : DL models CNN, MLP, Autoencoder
- What is your participant role? Gssoc Contributor

*************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by abhisheks008** [comment]
Similar problem statements are already present in this repo.

Closing this issue as not planned.
