### ISSUE TITLE
Automatic Music Generation

### ISSUE THREAD

**Issue by PradnyaGaitonde** [abhisheks008/DL-Simplified#879]
### Deep Learning Simplified Repository (Proposing new issue)
:red_circle: **Project Title** : </br> Automatic Music Generation
:red_circle: **Aim** : </br> Automatic music generation involves creating a system that can compose short pieces of music using parameters such as pitch, notes, chords, and tempo. This project uses Long Short Term Memory (LSTM) networks, a type of Recurrent Neural Network (RNN), to generate music, focusing on classical piano compositions.
:red_circle: **Dataset** : </br> https://www.kaggle.com/datasets/soumikrakshit/classical-music-midi
:red_circle: **Approach** : Try to use 3-4 algorithms to implement the models and compare all the algorithms to find out the best fitted algorithm for the model by checking the accuracy scores. Also do not forget to do a exploratory data analysis before creating any model.

**********************************************************************************
### 📍 **Follow the Guidelines to Contribute in the Project :**
* You need to create a separate folder named as the Project Title.
* Inside that folder, there will be four main components.
   * Images - To store the required images.
   * Dataset - To store the dataset or, information/source about the dataset.
   * Model - To store the machine learning model you've created using the dataset.
   * `requirements.txt` - This file will contain the required packages/libraries to run the project in other machines.
* Inside the `Model` folder, the `README.md` file must be filled up properly, with proper visualizations and conclusions.

***********************************************************************
:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include issue number along with it.
- Follow Contributing Guidelines & Code of Conduct before start Contributing.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Pradnya Gaitonde
- GitHub Profile Link : https://github.com/PradnyaGaitonde
- Email ID : pradnya7886@gmail.com
- Participant ID (if applicable):
- Approach for this Project : The project leverages deep learning techniques, specifically LSTM networks, to create an automatic music generation system. By training on classical piano compositions, the model learns to predict sequences of notes, generating new music pieces with a reasonable accuracy. The final output is saved as a MIDI file, showcasing the potential of deep learning in the creative domain of music composition.
- What is your participant role? (Mention the Open Source program) GSSOC24

*************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by abhisheks008** [comment]
LSTM is one of those finest models for this kind of problem statement, apart from LSTM what are the other models you are planning to implement here? As you need to mention at least 3 models in your approach for taking any issue.

@PradnyaGaitonde

**Comment by PradnyaGaitonde** [comment]
@abhisheks008 I am planning to implement WaveNet model which would provide superior results in generating raw audio waveforms and Multi-layer LSTM as well for ABC Sheet Music to transform the problem into an NLP task, resulting in improved music generation performance.

**Comment by abhisheks008** [comment]
Assigned @PradnyaGaitonde. You can go ahead.
