### ISSUE TITLE
Stock Analysis

### ISSUE THREAD

**Issue by aygarg02** [abhisheks008/DL-Simplified#893]
### Deep Learning Simplified Repository (Proposing new issue)
:red_circle: **Project Title** :Stock analysis  </br>
:red_circle: **Aim** : this project provide the analysis of the provided stock like unseen pattern visualization etc </br>
:red_circle: **Dataset** :depend on the given stock  </br>
:red_circle: **Approach** : Try to use 3-4 algorithms to implement the models and compare all the algorithms to find out the best fitted algorithm for the model by checking the accuracy scores. Also do not forget to do a exploratory data analysis before creating any model 

**********************************************************************************
### 📍 **Follow the Guidelines to Contribute in the Project :**
* You need to create a separate folder named as the Project Title.
* Inside that folder, there will be four main components.
   * Images - To store the required images.
   * Dataset - To store the dataset or, information/source about the dataset.
   * Model - To store the machine learning model you've created using the dataset.
   * `requirements.txt` - This file will contain the required packages/libraries to run the project in other machines.
* Inside the `Model` folder, the `README.md` file must be filled up properly, with proper visualizations and conclusions.

***********************************************************************
:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include issue number along with it.
- Follow Contributing Guidelines & Code of Conduct before start Contributing.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Ayush garg
- GitHub Profile Link : https://github.com/aygarg02
- Email ID :aygarg02@gmail.com
- Participant ID (if applicable):
- Approach for this Project :ARIMA ,ACF, PCF ,RNN
- What is your participant role? (Mention the Open Source program)

*************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by abhisheks008** [comment]
What are deep learning models you are planning to use here for this problem statement?
@aygarg02

**Comment by aygarg02** [comment]
i decided to use some on the ML methods and from the Deep learning i will use the RNN and then will give the single output on the basis of the output from all the modes. and ML methods like ARIMA

**Comment by abhisheks008** [comment]
> i decided to use some on the ML methods and from the Deep learning i will use the RNN and then will give the single output on the basis of the output from all the modes. and ML methods like ARIMA

It should be better if you focus on deep learning models only instead of machine learning models.

**Comment by aygarg02** [comment]
okk should i start ??

**Comment by abhisheks008** [comment]
> okk should i start ??

What are the deep learning models you are planning to use for this problem statement? Can you please explain?

**Comment by Itachii27** [comment]
Hi @abhisheks008 I want to work on this issue. Please assign this issue to me

Full name: Surbhi Bahukhandi
GitHub Profile Link: https://github.com/Itachii27  
Email ID: surbhibahukhandi1999@gmail.com  
Participant ID (if applicable):  
Approach for this Project: RNN, LSTM, GRU, CNN  
What is your participant role? Gssoc-extd, hacktoberfest, hacktoberfest-accepted

**Comment by abhisheks008** [comment]
Hi @Itachii27 thanks for sharing your approach. Issue assigned to you. You can start working on this.

**Comment by Itachii27** [comment]
Hi @abhisheks008 There's an issue in cloning this repository. It was giving issues to the files which has **colon** in it(as i am working on windows). Ex : **Bone Fracture Detection/Images/RCNN:results.png**
So, I ran commands:
`git clone --depth 1 git@github.com:Itachii27/DL-Simplified.git`
`git clone -c core.protectNTFS=false https://github.com/abhisheks008/DL-Simplified.git`
![image](https://github.com/user-attachments/assets/74c53961-64a9-417e-b68f-cd3acac3dde1)

these commands delete these files. 
So, I did my changes (hoping that i'll reset these files afterwards), I still came to an error in restoring them
![image](https://github.com/user-attachments/assets/09e73369-87ad-4818-9932-12cecd3aab39)

Could you please let me know how to resolve this. I have done the changes already.

**Comment by Itachii27** [comment]
Hi @abhisheks008 I have done. Please the review.
