### ISSUE TITLE
Landmark Detection Project

### ISSUE THREAD

**Issue by yashksaini-coder** [abhisheks008/DL-Simplified#898]
### Deep Learning Simplified Repository (Proposing new issue)
:red_circle: **Project Title** : Landmark Detection Project</br>
:red_circle: **Aim** : To add a Landmark detect web app project in Data Science category</br>
:red_circle: **Dataset** : google-landmark-dataset</br>
:red_circle: **Approach** : Try to use an open source model and use it to detect the landmark from the images given by the user. Using streamlit to create a web app that will be used to provide a simple interface.

**********************************************************************************
### 📍 **Follow the Guidelines to Contribute in the Project :**
* You need to create a separate folder named as the Project Title.
* Inside that folder, there will be four main components.
   * Images - To store the required images.
   * Dataset - To store the dataset or, information/source about the dataset.
   * Model - To store the machine learning model you've created using the dataset.
   * `requirements.txt` - This file will contain the required packages/libraries to run the project in other machines.
* Inside the `Model` folder, the `README.md` file must be filled up properly, with proper visualizations and conclusions.

***********************************************************************
:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include issue number along with it.
- Follow Contributing Guidelines & Code of Conduct before start Contributing.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Yash Kumar Saini
- GitHub Profile Link :  https://github.com/yashksaini-coder
- Email ID : yashkumarsaini366@gmail.com
- Participant ID (if applicable): NA
- Approach for this Project : Contributor
- What is your participant role? (Mention the Open Source program) Gssoc'24 contributor

*************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by yashksaini-coder** [comment]
@abhisheks008 I want to add this project can you assign me this issue to me.

**Comment by abhisheks008** [comment]
Hi @yashksaini-coder what are the models you are planning to implement here?

**Comment by yashksaini-coder** [comment]
> Hi @yashksaini-coder what are the models you are planning to implement here?

I am thinking of using open source models or hugging face models.

With streamlit or flask to create a interactive window.

@abhisheks008

**Comment by abhisheks008** [comment]
Cool go ahead @yashksaini-coder. You can start working on it.

**Comment by yashksaini-coder** [comment]
[Landmark detection.webm](https://github.com/user-attachments/assets/288f8938-f052-482b-914e-5a5b751e0911)
