### ISSUE TITLE
Handwriting Recognition Project

### ISSUE THREAD

**Issue by abhisheks008** [abhisheks008/DL-Simplified#9]
### Deep Learning Simplified Repository (Proposing new issue)
:red_circle: **Project Title** : Handwriting Recognition Project</br>
:red_circle: **Aim** : The aim is to create a deep learning project which will recognize the handwritings and detect them with an accuracy of more than 85%</br>
:red_circle: **Dataset** : https://www.kaggle.com/datasets/landlord/handwriting-recognition</br>
:red_circle: **Approach** : Try to use 3-4 algorithms to implement the models and compare all the algorithms to find out the best fitted algorithm for the model by checking the accuracy scores. Also do not forget to do a exploratory data analysis before creating any model.

**********************************************************************************
### 📍 **Follow the Guidelines to Contribute in the Project :**
* You need to create a separate folder named as the Project Title.
* Inside that folder, there will be four main components.
   * Images - To store the required images.
   * Dataset - To store the dataset or, information/source about the dataset.
   * Model - To store the machine learning model you've created using the dataset.
   * `requirements.txt` - This file will contain the required packages/libraries to run the project in other machines.
* Inside the `Model` folder, the `README.md` file must be filled up properly, with proper visualizations and conclusions.

***********************************************************************
:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include issue number along with it.
- Follow Contributing Guidelines & Code of Conduct before start Contributing.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : 
- GitHub Profile Link : 
- Email ID :
- Participant ID (if applicable):
- Approach for this Project :
- What is your participant role? (Mention the Open Source program)

*************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by SHAY2407** [comment]
Full name : Yashwardhan Khanna
GitHub Profile Link : https://github.com/SHAY2407
Email ID : yashwardhan2407@gmail.com
Participant ID (if applicable):
Approach for this Project : I will first try to make the model with the help of Random Forest Classification Algorithm. If I get some time left, I will learn about SVM and will try to make it with the same.
What is your participant role? (Mention the Open Source program): Social Summer of Code (SSOC)

**Comment by abhisheks008** [comment]
Thanks for choosing **Deep Learning Simplified** for your contributions. Wait for the Inauguration Ceremony, which is going to happen by today, 6 PM. After that, I'll start accepting the comments and assign the issues.

Best wishes! ✨ 
@SHAY2407
