### ISSUE TITLE
Feature request: Autocorrect

### ISSUE THREAD

**Issue by Vishisht16** [abhisheks008/DL-Simplified#901]
### Deep Learning Simplified Repository (Proposing new issue)
:red_circle: **Project Title** : Autocorrect using DL model</br>
:red_circle: **Aim** : To make a model that uses text as input and fixes any spelling or grammatical errors.</br>
:red_circle: **Dataset** : http://www.manythings.org/anki/fra-eng.zip </br>
:red_circle: **Approach** : An LSTM trained on English sentence pairs and tested on different data after adding noise.

**********************************************************************************
### 📍 **Follow the Guidelines to Contribute in the Project :**
* You need to create a separate folder named as the Project Title.
* Inside that folder, there will be four main components.
   * Images - To store the required images.
   * Dataset - To store the dataset or, information/source about the dataset.
   * Model - To store the machine learning model you've created using the dataset.
   * `requirements.txt` - This file will contain the required packages/libraries to run the project in other machines.
* Inside the `Model` folder, the `README.md` file must be filled up properly, with proper visualizations and conclusions.

***********************************************************************
:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include issue number along with it.
- Follow Contributing Guidelines & Code of Conduct before start Contributing.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Vishisht Mishra
- GitHub Profile Link : https://github.com/Vishisht16
- Email ID : vishishtmishra150@gmail.com
- Participant ID (if applicable):
- Approach for this Project : LSTM
- What is your participant role? GSSoC Extd - Contributor

*************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by abhisheks008** [comment]
Apart from LSTM is there any other model(s) you can implement here for this same problem statement?
@Vishisht16

**Comment by Vishisht16** [comment]
That seems to be a good approach. What do you want me to do?
@Vishisht16

**Comment by abhisheks008** [comment]
> That seems to be a good approach. What do you want me to do? @Vishisht16

Here in this repository we used to implement at least 3 models for each problem statement and find out the best fitted one based on the accuracy scores.

**Benefits for implementing different models:**
1. Majority of the contributors are new to this open source and deep learning field, implementing multiple models will help contributors to explore more about the topic.
2. Students can also explore how different models work for a single dataset.
3. Students can help themselves out, why some model is best fitted with a particular dataset and others are not.
4. Multiple models will also justify the "Best Fitted" term based on the comparison of the accuracy scores.
