### ISSUE TITLE
Match the column names in the code to the column names in the dataset

### ISSUE THREAD

**Issue by shristirwt** [abhisheks008/DL-Simplified#908]
### Deep Learning Simplified Repository (Proposing new issue)
:red_circle: **Project Title** : AI Based Book Recommendation System </br>
:red_circle: **Aim** : To match the column names in the code to the column names in the dataset</br>
:red_circle: **Dataset** :final_data.csv </br>
:red_circle: **Approach** : To change the column names so that the error can be corrected for expected output

**********************************************************************************
### 📍 **Follow the Guidelines to Contribute in the Project :**
* You need to create a separate folder named as the Project Title.
* Inside that folder, there will be four main components.
   * Images - To store the required images.
   * Dataset - To store the dataset or, information/source about the dataset.
   * Model - To store the machine learning model you've created using the dataset.
   * `requirements.txt` - This file will contain the required packages/libraries to run the project in other machines.
* Inside the `Model` folder, the `README.md` file must be filled up properly, with proper visualizations and conclusions.

***********************************************************************
:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include issue number along with it.
- Follow Contributing Guidelines & Code of Conduct before start Contributing.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Shristi Rawat
- GitHub Profile Link : https://github.com/shristirwt
- Email ID :shristirawat68@gmail.com
- Participant ID (if applicable):
- Approach for this Project : To modify the column names in the code to match with column names in the dataset
- What is your participant role? (Mention the Open Source program) : GSSoC 2024 Extd 

*************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by abhisheks008** [comment]
Hi @shristirwt thanks for showing interest here. This type of project is already present here in this repository, hence closing this issue as duplicate entry.

You can raise another issue with different problem statement.
