### ISSUE TITLE
Sign Language to Speech Conversion using Computer Vision and Keras 

### ISSUE THREAD

**Issue by rithvikreddybasani** [abhisheks008/DL-Simplified#909]
developed a sign language to speech conversion system using Keras and computer vision. The system employs a convolutional neural network (CNN) to accurately interpret sign language gestures and convert them into spoken words. For speech synthesis, I integrated pyttsx3 and gTTS, enabling seamless communication

![image](https://github.com/user-attachments/assets/40d393bb-e4f9-4b12-bed1-5c43acd3a79e)

Can you assign me this @abhisheks008?

**Comment by abhisheks008** [comment]
Can you please follow the issue template and mention all the details accordingly? It'll be helpful for me to have a better understanding and track.

Closing this issue as of now.
