### ISSUE TITLE
Enhancement: New EDA to Amazon Reviews Sentiment Analysis

### ISSUE THREAD

**Issue by SimranShaikh20** [abhisheks008/DL-Simplified#915]
### Deep Learning Simplified Repository (Proposing new issue)
issue in Amazon Reviews Sentiment Analysis 
**********************************************************************************
Feature Description
Data Analysis/Daily News and Stock Data Analysis/DailyNews.ipynb

Hi, I am Simran Shaikh. I’ve been reviewing the project as part of my contribution to GSSoC Extended 24 and noticed that the code performs by adding more charts for better understanding we can used different library of python like seaborn or matplotlib . By using this library its easy to understand Job Satisfaction Analysis . Also we can include some data cleaning concept for more accurate and efficient data. As i had find an exixting issue there is no more charts .

This would help increase in more visualization . I would like to work on this.
If you like this idea, assign the task to me and add the corresponding charts to it.
Thank you for your time and consideration!

liked my idea assign me a work @abhisheks008

**Comment by SimranShaikh20** [comment]
@abhishak3 can you assign me work !

**Comment by SimranShaikh20** [comment]
> @abhishak3 can you assign me work !

Have liked my idea ?

**Comment by SimranShaikh20** [comment]
@abhishak3  can you assign me this work ?

**Comment by SimranShaikh20** [comment]
@abhishak3  can you please review mu issue!

**Comment by abhisheks008** [comment]
> @abhishak3 can you please review mu issue!

I think you are tagging a different person instead of me!

Anyways, this work will be an enhancement work of the existing project. Do not remove any files/folders from the existing project folder, add your file(s) only in the designated folder then create a pull request for review.

I hope you have understood my point. Assigning this issue to you @SimranShaikh20 

Updated the issue title as per the required naming convention.

**Comment by SimranShaikh20** [comment]
> > @abhishak3 can you please review mu issue!
> 
> I think you are tagging a different person instead of me!
> 
> Anyways, this work will be an enhancement work of the existing project. Do not remove any files/folders from the existing project folder, add your file(s) only in the designated folder then create a pull request for review.
> 
> I hope you have understood my point. Assigning this issue to you @SimranShaikh20
> 
> Updated the issue title as per the required naming convention.

Oh sorry my bad typo error

**Comment by SimranShaikh20** [comment]
@abhisheks008  can you pls change assigned level !

**Comment by SimranShaikh20** [comment]
hey @abhisheks008  can you please upgrade the assigned level !
