### ISSUE TITLE
Real time pose estimation of a person

### ISSUE THREAD

**Issue by mahipalimkar** [abhisheks008/DL-Simplified#916]
Feature Request: Implement real-time human pose estimation for detecting key body points from live video streams or webcam feeds.

**Comment by mahipalimkar** [comment]
Can I make a pr?

**Comment by abhisheks008** [comment]
Hi @mahipalimkar thanks for creating a new issue. Can you please elaborate on the approach and the models you are implementing for this project.

**Comment by mahipalimkar** [comment]
Yes sure. I have used mediapipe's solutions.pose model for the same. It is capable of detecting 33 key landmark points in both 2d and 3d. I have implemented the 3D version, where each frame is captured and keypoints are detected across it.

**Comment by Abhiiesante** [comment]
Can you please assign this issue to me under 𝗚𝗦𝗦𝗼𝗖 '𝟮𝟰 𝗘𝘅𝘁𝗲𝗻𝗱𝗲𝗱, Hacktoberfest-accepted

**Comment by abhisheks008** [comment]
> Yes sure. I have used mediapipe's solutions.pose model for the same. It is capable of detecting 33 key landmark points in both 2d and 3d. I have implemented the 3D version, where each frame is captured and keypoints are detected across it.

Sorry for replying late @mahipalimkar 

Any dataset you are following? And apart from Mediapipe have you tried with other model implementations for this same problem statement?
