### ISSUE TITLE
Add a New Project Image Carousel

### ISSUE THREAD

**Issue by Sumanth077s** [abhisheks008/DL-Simplified#919]
We need to add a simple image carousel implemented using HTML, CSS, and JavaScript to the project repository. This carousel will allow users to navigate through multiple images with Previous and Next buttons, providing a smooth and interactive user experience.

Task Requirements:
Create an index.html file for the carousel structure.
Use CSS to style the carousel, ensuring it looks aesthetically pleasing and is responsive on different screen sizes.
Implement JavaScript to enable carousel functionality:
Transition between images when clicking Previous and Next buttons.
Loop back to the first image when the user reaches the end.

Optionally, include autoplay functionality with a pause on hover.

Acceptance Criteria:
The carousel should function smoothly with transitions.
It should be responsive on both desktop and mobile devices.
Code should be clean, modular, and easy to maintain.

Benefits:
Adds a visually engaging component to the project.
Demonstrates practical use of HTML, CSS, and JavaScript.

Additional Notes:
Ensure all files are well-documented with comments.
Test the carousel thoroughly to avoid any navigation issues.

**Comment by abhisheks008** [comment]
This project repository mainly focuses on deep learning projects. Closing this issue as not planned.
