### ISSUE TITLE
Implement PR Issue Checker Workflow

### ISSUE THREAD

**Issue by smog-root** [abhisheks008/DL-Simplified#923]
**Description:** We need to create a GitHub Actions workflow that automates the validation of pull requests (PRs). This workflow will ensure that all PRs meet the following criteria before being merged:

**PR Description Check:** Every PR must have a description. If the description is missing, the PR should fail the check.
    
**Issue Reference Check:** The PR description must include an issue reference in the format Fixes #<issue-number>. If the PR is not addressing an existing issue, it should mention Fixes #NEW as a placeholder.

**Acceptance Criteria:**

- A GitHub Action workflow is triggered on PR events (opened, edited).

**The workflow checks the PR body for:**
- A non-empty description.
- The presence of Fixes #<issue-number> or Fixes #NEW.

**If the criteria are not met:**

- The workflow should fail and return clear error messages.

**If the checks pass:**
- A confirmation message is outputted.

**Expected Output:**

- Error message if the PR description is missing.
- Error message if the issue reference is missing or incorrectly formatted.
- Success message when all checks are satisfied.

**Additional Notes:**

- This issue may serve as a foundation for more advanced PR validation (e.g., commit message format, label enforcement).
- We can later extend this to check for specific branch naming conventions or enforce the addition of specific labels.

_**Note**_: i'm expecting a gssoc-ext with level3 and a hacktoberfest-accepted label!

@abhisheks008

**Comment by abhisheks008** [comment]
Not required @smog-root 

Closing this issue.

**Comment by smog-root** [comment]
@abhisheks008 anything I can contribute to??

**Comment by abhisheks008** [comment]
You can try out the existing deep learning projects (issues) for contributions if you are comfortable with this topic.

Workflows are okay to ccontribute but as this repository is mainly focuses on deep learning projects hence workflows contributions are not validated that much by the GSSOC Extd team as per their code of conduct and regulations.
