### ISSUE TITLE
Gender Classification using DL(new issue)

### ISSUE THREAD

**Issue by Pratzybha** [abhisheks008/DL-Simplified#928]
### Deep Learning Simplified Repository (Proposing new issue)
:red_circle: **Project Title** : Gender Classification using DL</br>
:red_circle: **Aim** : To build ensemble model + improve read me section and add more visualizations</br>
:red_circle: **Dataset** : https://www.kaggle.com/datasets/cashutosh/gender-classification-dataset</br>
:red_circle: **Approach** :  Combine predictions from Custom CNN + VGGNet + ResNet models to build a final ensemble model.

**********************************************************************************
### 📍 **Follow the Guidelines to Contribute in the Project :**
* You need to create a separate folder named as the Project Title.
* Inside that folder, there will be four main components.
   * Images - To store the required images.
   * Dataset - To store the dataset or, information/source about the dataset.
   * Model - To store the machine learning model you've created using the dataset.
   * `requirements.txt` - This file will contain the required packages/libraries to run the project in other machines.
* Inside the `Model` folder, the `README.md` file must be filled up properly, with proper visualizations and conclusions.

***********************************************************************
:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include issue number along with it.
- Follow Contributing Guidelines & Code of Conduct before start Contributing.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Pratibha Balgi
- GitHub Profile Link : https://github.com/Pratzybha
- Email ID : pratibhabalgi02@gmail.com
- Participant ID (if applicable):
- Approach for this Project : Mentioned above
- What is your participant role? GSSOC-EXT 2024

*************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by AgrawalTitiksha** [comment]
Full name : Titiksha Agrawal
GitHub Profile Link : https://github.com/AgrawalTitiksha/
Email ID : [agrawaltn2311@gmail.com](mailto:agrawaltn2311@gmail.com)
Participant ID (if applicable):
Approach for this Project : Load the dataset from Kaggle, preprocess the images, and split the data into training, validation, and testing sets. Develop and train three separate models: Custom CNN, VGGNet, and ResNet, and then combine their predictions using techniques like voting, averaging, or stacking to create the final ensemble model. Evaluate the performance of the ensemble model using metrics like accuracy, precision, and recall.
What is your participant role? Hacktoberfest-2024 Contributor

**Comment by abhisheks008** [comment]
Hi @Pratzybha  this project is already present in this repository.
![image](https://github.com/user-attachments/assets/118ad7d3-84cc-4381-8a06-f3afa14b505f)

Hence closing this issue as duplicate.
