### ISSUE TITLE
Image Caption Generator

### ISSUE THREAD

**Issue by Amanjayswal500** [abhisheks008/DL-Simplified#942]
### Deep Learning Simplified Repository (Proposing new issue)
:red_circle: **Project Title** : Image Caption Generator</br>
:red_circle: **Aim** :To develop an image caption generator using deep learning that automatically generates descriptive and contextually accurate captions for images, combining computer vision and natural language processing techniques for improved human-computer interaction. </br>
:red_circle: **Dataset** :Flicker8K dataset </br>
:red_circle: **Approach** :  image caption generator by using CNN (Convolutional Neural Networks) and LSTM (Long short term memory) units.
For training our model I’m using Flickr8K dataset. It consists of 8000 unique images and each image will be mapped to five different sentences which will describe the image.

**********************************************************************************
### 📍 **Follow the Guidelines to Contribute in the Project :**
* You need to create a separate folder named as the Project Title.
* Inside that folder, there will be four main components.
   * Images - To store the required images.
   * Dataset - To store the dataset or, information/source about the dataset.
   * Model - To store the machine learning model you've created using the dataset.
   * `requirements.txt` - This file will contain the required packages/libraries to run the project in other machines.
* Inside the `Model` folder, the `README.md` file must be filled up properly, with proper visualizations and conclusions.

***********************************************************************
:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include issue number along with it.
- Follow Contributing Guidelines & Code of Conduct before start Contributing.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Aman Jayswal
- GitHub Profile Link : https://github.com/Amanjayswal500
- Email ID :amanjayswal500@gmail.com
- What is your participant role? GSSoC'24-Extd Contributor, hacktobefest

*************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by abhisheks008** [comment]
The same problem statement is already present in this repository. Hence closing this issue as duplicate.
