### ISSUE TITLE
Documentation: Enhancement Of Contributing.md

### ISSUE THREAD

**Issue by milansamuel609** [abhisheks008/DL-Simplified#944]
The contributing.md file is not in a structured manner. Also some sections are missing. I can enhance it in a well structured manner with proper details and some additional sections also that will make the contributors easier to contribute. Please can you assign me this task?

Wanted to do the following changes :-

1) Enhance the project structure
2) Add need help with the basics section
3) Add project structure section
4) Add additional method of contributing through GitHub desktop section
5) Add good coding practices section
6) Add the help and support section
7) Add the pull request section
8) Add issue report process section

**Comment by abhisheks008** [comment]
Can you please mention the URL of the file in which you want to update these changes?
@milansamuel609

**Comment by milansamuel609** [comment]
This one 
https://github.com/abhisheks008/DL-Simplified/blob/main/CONTRIBUTING.md

**Comment by abhisheks008** [comment]
Cool go ahead. Quick reminder: this type of issue will only be labelled as Level 1.

**Comment by milansamuel609** [comment]
> Cool go ahead. Quick reminder: this type of issue will only be labelled as Level 1.

Sure
