### ISSUE TITLE
Skin Disease Classification using Deep Learning Models

### ISSUE THREAD

**Issue by pacificrm** [abhisheks008/DL-Simplified#945]
### Deep Learning Simplified Repository (Proposing new issue)
:red_circle: **Project Title** : Skin Disease Classification using Deep Learning Models </br>
:red_circle: **Aim** :  To build a model to classify various Skin diseases</br>
:red_circle: **Dataset** : https://www.kaggle.com/datasets/pacificrm/skindiseasedataset/data </br>
:red_circle: **Approach** : First  Analyze the dataset by checking image quality, class distributions, and visualization of sample images. Then I train various models to enhance the classification accuracy, I propose building and comparing various models to select the best one. The models to be used include:
VGG /(Custom model)
ResNet
SEResNet
EfficientNet
Vision Transformer (ViT)

**********************************************************************************
### 📍 **Follow the Guidelines to Contribute in the Project :**
* You need to create a separate folder named as the Project Title.
* Inside that folder, there will be four main components.
   * Images - To store the required images.
   * Dataset - To store the dataset or, information/source about the dataset.
   * Model - To store the machine learning model you've created using the dataset.
   * `requirements.txt` - This file will contain the required packages/libraries to run the project in other machines.
* Inside the `Model` folder, the `README.md` file must be filled up properly, with proper visualizations and conclusions.

***********************************************************************
:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include issue number along with it.
- Follow Contributing Guidelines & Code of Conduct before start Contributing.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name :  Prashant Kumar Mishra
- GitHub Profile Link : https://github.com/pacificrm
- Email ID : ur.pm.ru@gmail.com
- Participant ID (if applicable):
- Approach for this Project :  Mentioned above.
- What is your participant role? GSSOC-EXT  and Hacktoberfest

*************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by abhisheks008** [comment]
Assigning this issue to you @pacificrm. You can start working on it.
