### ISSUE TITLE
GAN-based Art Generator using Deep learning

### ISSUE THREAD

**Issue by alo7lika** [abhisheks008/DL-Simplified#954]
### Deep Learning Simplified Repository (Proposing new issue)

:red_circle: **Project Title** : GAN-based Art Generator using Deep Learning  
:red_circle: **Aim** : Create an art generator that utilizes Generative Adversarial Networks (GANs) to generate artistic images.  
:red_circle: **Dataset** : A synthetic dataset of artistic images will be generated or sourced from open datasets.  
:red_circle: **Approach** : Implement 3-4 different GAN algorithms, conduct exploratory data analysis, and compare their performance based on accuracy scores to determine the best fitting model.  

**********************************************************************************

### 📍 **Follow the Guidelines to Contribute in the Project :**
* You need to create a separate folder named as the Project Title.
* Inside that folder, there will be four main components.
   * Images - To store the required images.
   * Dataset - To store the dataset or, information/source about the dataset.
   * Model - To store the machine learning model you've created using the dataset.
   * `requirements.txt` - This file will contain the required packages/libraries to run the project in other machines.
* Inside the `Model` folder, the `README.md` file must be filled up properly, with proper visualizations and conclusions.

***********************************************************************

:red_circle::yellow_circle: **Points to Note :**
- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include issue number along with it.
- Follow Contributing Guidelines & Code of Conduct before start Contributing.

***********************************************************************

:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Alolika Bhowmik
- GitHub Profile Link : https://github.com/alo7lika
- Email ID : alolikabhowmik72@gmail.com
- Participant ID (if applicable): GSSOC Contributor
- Approach for this Project : Implement GANs to generate art and evaluate their performance.
- What is your participant role? (Mention the Open Source program): GSSOC Contributor.

*************************************************************
Happy Contributing 🚀 
All the best. Enjoy your open source journey ahead. 😎

**Comment by alo7lika** [comment]
Assign me the task under GSSOC EXT 24 and HACKTOBERFEST @abhisheks008

**Comment by abhisheks008** [comment]
Assigned @alo7lika
