### ISSUE TITLE
3D Human Pose Estimation Using Deep learning

### ISSUE THREAD

**Issue by alo7lika** [abhisheks008/DL-Simplified#955]
### Deep Learning Simplified Repository (Proposing new issue)
:red_circle: **Project Title**: 3D Human Pose Estimation  using Deep Learning
:red_circle: **Aim**: To predict 3D coordinates of human body joints from 2D images.  
:red_circle: **Dataset**: Synthetic dataset generated using 2D pose data and corresponding 3D coordinates.  
:red_circle: **Approach**: Utilize 3-4 algorithms such as CNNs for image processing and regression networks for 3D coordinate prediction. Compare accuracy scores to determine the best-performing model. Perform exploratory data analysis (EDA) prior to model creation.

**********************************************************************************
### 📍 **Follow the Guidelines to Contribute in the Project**:
* You need to create a separate folder named as the Project Title.
* Inside that folder, there will be four main components:
   * Images - To store the required images.
   * Dataset - To store the dataset or information/source about the dataset.
   * Model - To store the machine learning model you've created using the dataset.
   * `requirements.txt` - This file will contain the required packages/libraries to run the project on other machines.
* Inside the `Model` folder, the `README.md` file must be filled up properly, with proper visualizations and conclusions.

***********************************************************************
:red_circle::yellow_circle: **Points to Note**:
- The issues will be assigned on a first-come, first-serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include the issue number along with it.
- Follow Contributing Guidelines & Code of Conduct before you start contributing.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue**:
- Full name: Alolika Bhowmik  
- GitHub Profile Link: https://github.com/alo7lika
- Email ID: alolikabhowmik72@gmail.com  
- Participant ID (if applicable): GSSOC Contributor  
- Approach for this Project: Use CNNs and regression networks for 3D human pose estimation.  
- What is your participant role? (Mention the Open Source program): GSSOC Contributor  

*************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by alo7lika** [comment]
Assign me the task under GSSOC EXT 24  and HACKTOBERFEST @abhisheks008

**Comment by abhisheks008** [comment]
Similar problem statement is already present in this repository hence closing this issue as duplicate.
