### ISSUE TITLE
Addition of Groundwater arsenic content detection

### ISSUE THREAD

**Issue by Stuti333** [abhisheks008/DL-Simplified#960]
### Deep Learning Simplified Repository (Proposing new issue)
:red_circle: **Groundwater arsenic content detection**  </br>
:red_circle: **Develop and implement reliable, cost-effective methods to detect and monitor arsenic contamination in groundwater sources to ensure water safety** </br>
:red_circle: **Government released groundwater data (for different states)** </br>
:red_circle: **Approach** : Try to use 1-2 algorithms to implement the groundwater contaminants detection and compare all the algorithms to find out the best fitted algorithm for the model by checking the accuracy scores. Also do not forget to do a exploratory data analysis before creating any model.

**********************************************************************************
### 📍 **Follow the Guidelines to Contribute in the Project :**
* You need to create a separate folder named as the Project Title.
* Inside that folder, there will be four main components.
   * Images - To store the required images.
   * Dataset - To store the dataset or, information/source about the dataset.
   * Model - To store the machine learning model you've created using the dataset.
   * `requirements.txt` - This file will contain the required packages/libraries to run the project in other machines.
* Inside the `Model` folder, the `README.md` file must be filled up properly, with proper visualizations and conclusions.

***********************************************************************
:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include issue number along with it.
- Follow Contributing Guidelines & Code of Conduct before start Contributing.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Stuti Sharma
- GitHub Profile Link : https://github.com/Stuti333
- Email ID : stuti2718@gmail.com
- Participant ID (if applicable):
- Approach for this Project : To use ANN as well as WOA to predict whether the groundwater is favourable or poisonous
- What is your participant role? Contributor GSSOC EXT

*************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by abhisheks008** [comment]
It'd be good if you go with 3 models at least. Can you update your approach and revert back.
@Stuti333

**Comment by Stuti333** [comment]
sure

**Comment by Stuti333** [comment]
Deep Learning Simplified Repository (Proposing new issue)
🔴 Groundwater arsenic content detection

🔴 Develop and implement reliable, cost-effective methods to detect and monitor arsenic contamination in groundwater sources to ensure water safety

🔴 Government released groundwater data (for different states)

🔴 Approach : Try to use 3 algorithms to implement the groundwater contaminants detection and compare all the algorithms to find out the best fitted algorithm for the model by checking the accuracy scores. Also do not forget to do a exploratory data analysis before creating any model.

📍 Follow the Guidelines to Contribute in the Project :
You need to create a separate folder named as the Project Title.
Inside that folder, there will be four main components.
Images - To store the required images.
Dataset - To store the dataset or, information/source about the dataset.
Model - To store the machine learning model you've created using the dataset.
requirements.txt - This file will contain the required packages/libraries to run the project in other machines.
Inside the Model folder, the README.md file must be filled up properly, with proper visualizations and conclusions.
🔴🟡 Points to Note :

The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
"Issue Title" and "PR Title should be the same. Include issue number along with it.
Follow Contributing Guidelines & Code of Conduct before start Contributing.
✅ To be Mentioned while taking the issue :

Full name : Stuti Sharma
GitHub Profile Link : https://github.com/Stuti333
Email ID : [stuti2718@gmail.com](mailto:stuti2718@gmail.com)
Participant ID (if applicable):
Approach for this Project : To use ANN , WOA and Random Forest Regression to predict whether the groundwater is favourable or poisonous
What is your participant role? Contributor GSSOC EXT
Happy Contributing 🚀

All the best. Enjoy your open source journey ahead. 😎

**Comment by Stuti333** [comment]
@abhisheks008 kindly assign me this task

**Comment by abhisheks008** [comment]
Go ahead @Stuti333
