### ISSUE TITLE
FEATURE REQUESTED : Urban Sound Analysis - Sound Classification

### ISSUE THREAD

**Issue by SimranShaikh20** [abhisheks008/DL-Simplified#963]
This project classifies audio samples from urban environments into one of 10 classes. The dataset, known as UrbanSound8K, contains 8732 sound excerpts, each 4 seconds or shorter, representing urban sounds like air conditioners, car horns, children playing, and more. Using a Neural Network model, the project aims to achieve high classification accuracy (reported at 93%).

Key Objectives : Classify Urban Sound Events ,  Feature Extraction from Audio Data , Use Deep Learning for Accuracy

Overall Goal:
To build a robust and accurate audio classification model that can recognize urban sound types, offering potential for real-world applications in smart cities and environmental monitoring systems.

@abhisheks008  liked my idea / new feature !
then assign me this issue to work on it .

**Comment by abhisheks008** [comment]
Hi @SimranShaikh20 what are the models you are planning to implement here?
Can you please share the dataset URL?

**Comment by SimranShaikh20** [comment]
here is dataset link - https://drive.google.com/file/d/1EpRQYWDIiZgmgnQunOFCzGIrfissXOxX/view?usp=sharing
i am thinking to implement it by using 3 ways 
and model i will implemet is - Training a ResNet model on spectorgram images / Training a Convolutional neural network on spectrogram images / Training an Artificial Neural Network on time-series audio data

but i will select more prefereable which is ann 
you can suggest me which i can used from above 3 option 

@abhisheks008

**Comment by SimranShaikh20** [comment]
hey @abhisheks008  can you assign me this project as i ha shared all mandatory details !

**Comment by SimranShaikh20** [comment]
@abhisheks008 let me know have you liked my idea !

**Comment by abhisheks008** [comment]
Hi @SimranShaikh20 try to implement in all the three possible ways mentioned by you, then based on the accuracy scores you can figure out the best fitted approach.

Assigned to you.
