### ISSUE TITLE
Enhancements in code of conduct file 

### ISSUE THREAD

**Issue by Nikhil0-3** [abhisheks008/DL-Simplified#964]
I want to add following points- 
Our Pledge
Our Standards
Enforcement Responsibilities
Scope
Pull Request Guidelines
Enforcement
Enforcement Guidelines
Attribution
Conclusion

here I added the screenshots of the file on which I worked earlier

![Screenshot 2024-10-22 104423](https://github.com/user-attachments/assets/c0bf4699-9d36-40f8-bade-82f80e29c291)
![Screenshot 2024-10-22 104433](https://github.com/user-attachments/assets/0e87d657-973a-465f-8245-91e37358f483)
![Screenshot 2024-10-22 104442](https://github.com/user-attachments/assets/a0737644-fa41-43d5-8f83-9df72271a176)

**Comment by abhisheks008** [comment]
Go ahead with it. Replace the old version with the new one.
Assigned @Nikhil0-3
