### ISSUE TITLE
 Anomaly Detection in Time Series

### ISSUE THREAD

**Issue by alo7lika** [abhisheks008/DL-Simplified#967]
### Deep Learning Simplified Repository 

:red_circle: **Project Title**: Anomaly Detection in Time Series Using LSTM Networks 

:red_circle: **Aim**: To develop an effective model for detecting anomalies in time series data, leveraging LSTM networks for improved accuracy and reliability.

:red_circle: **Dataset**: Synthetic Dataset

:red_circle: **Approach**: Implement 3-4 algorithms for anomaly detection, such as LSTM, Facebook Prophet Classification, and Isolation Forest. Conduct exploratory data analysis (EDA) to understand the data distribution and characteristics, and compare model performances using accuracy scores to identify the best-fitting model.

**********************************************************************************

### 📍 **Follow the Guidelines to Contribute in the Project:**
* Create a separate folder named as the Project Title.
* Inside that folder, include:
   * **Images** - For required visualizations.
   * **Dataset** - For dataset storage or source information.
   * **Model** - For the developed machine learning models.
   * **`requirements.txt`** - List of required packages/libraries.

* In the `Model` folder, provide a comprehensive `README.md` with visualizations and conclusions.

***********************************************************************

:red_circle::yellow_circle: **Points to Note:**

- Issues will be assigned on a first-come, first-served basis. 1 Issue == 1 PR.
- Ensure the "Issue Title" and "PR Title" match, including the issue number.
- Follow Contributing Guidelines & Code of Conduct.

***********************************************************************

:white_check_mark: **To be Mentioned while taking the issue:**
- Full name: Alolika Bhowmik
- GitHub Profile Link: https://github.com/alo7lika
- Email ID: alolikabhowmik72@gmail.com
- Participant ID (if applicable): [Your Participant ID]
- Approach for this Project: Implementing LSTM networks for time series anomaly detection and comparing multiple algorithms.
- What is your participant role? GSSOC Contributor

*************************************************************

Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by alo7lika** [comment]
Assign me the task under GSSOC and HACKTOBERFEST @abhisheks008

**Comment by alo7lika** [comment]
> Assign me the task under GSSOC and HACKTOBERFEST @abhisheks008

@abhisheks008

**Comment by alo7lika** [comment]
> Assign me the task under GSSOC and HACKTOBERFEST @abhisheks008

Assign the task @abhisheks008

**Comment by alo7lika** [comment]
Assign me the task under GSSOC and HACKTOBERFEST @abhisheks008

**Comment by alo7lika** [comment]
> Assign me the task under GSSOC and HACKTOBERFEST @abhisheks008

???

**Comment by abhisheks008** [comment]
Is the project ready with you? Can you make the PR as early as possible? If yes then make the pull request I will review and add the labels.
@alo7lika

**Comment by alo7lika** [comment]
> Is the project ready with you? Can you make the PR as early as possible? If yes then make the pull request I will review and add the labels. @alo7lika

yes its ready

**Comment by abhisheks008** [comment]
Make a pull request, I'll do the needful.

**Comment by alo7lika** [comment]
REVIEW THE PR ASAP @abhisheks008
