### ISSUE TITLE
Feature: Leaf Disease Detection

### ISSUE THREAD

**Issue by AE-Hertz** [abhisheks008/DL-Simplified#970]
Leaf disease detection using CNN .
importance- the leaf disease detection is a model to detect disease this will promptly help farmers to recognize the disease and find prevention of it accordingly. its a helpful model.

Assign me this under gssoc-ext and hacktoberfest.

**Comment by AE-Hertz** [comment]
@abhisheks008 assign me this issue .

**Comment by abhisheks008** [comment]
Similar kind of problem statement is already present here in this repository. Hence closing this issue as duplicate entry.
