### ISSUE TITLE
Add Hate Speech Detection

### ISSUE THREAD

**Issue by adwityac** [abhisheks008/DL-Simplified#972]
### Deep Learning Simplified Repository (Proposing new issue)
:red_circle: **Project Name** : Hate Speech Detection  </br>
:red_circle: **Aim** : The aim of the project is to develop a Natural Language Processing (NLP) system that can automatically identify and classify hate speech and abusive language in social media posts. By leveraging sentence classification techniques, the project seeks to filter out harmful content, promote a safer online environment, and reduce the spread of hate and controversy on social media platforms. Ultimately, the goal is to enhance user experience and foster positive interactions by mitigating the impact of negative and toxic communication. </br>
:red_circle: **Dataset** : 
[Dataset---Hate-Speech-Detection-using-Deep-Learning.csv](https://github.com/user-attachments/files/17582108/Dataset---Hate-Speech-Detection-using-Deep-Learning.csv)
</br>
:red_circle: **Approach** : This project focuses on hate speech detection using a deep learning approach, specifically employing an LSTM (Long Short-Term Memory) model to analyze text data. The LSTM model is designed to capture sequential patterns in text, making it effective for understanding context in hate speech detection tasks.

**********************************************************************************
### 📍 **Follow the Guidelines to Contribute in the Project :**
* You need to create a separate folder named as the Project Title.
* Inside that folder, there will be four main components.
   * Images - To store the required images.
   * Dataset - To store the dataset or, information/source about the dataset.
   * Model - To store the machine learning model you've created using the dataset.
   * `requirements.txt` - This file will contain the required packages/libraries to run the project in other machines.
* Inside the `Model` folder, the `README.md` file must be filled up properly, with proper visualizations and conclusions.

***********************************************************************
:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include issue number along with it.
- Follow Contributing Guidelines & Code of Conduct before start Contributing.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Adwitya Chakraborty
- GitHub Profile Link : [profile link](https://github.com/adwityac)
- Email ID : adwityachakraborty@hotmail.com
- Participant ID (if applicable):
- Approach for this Project : This project uses an LSTM-based deep learning approach for hate speech detection. Text data is preprocessed, tokenized, and transformed into word embeddings to capture meaning. The LSTM model then analyzes the sequential text patterns, learning contextual cues that help identify hate speech. The model's performance is evaluated using accuracy and other relevant metrics.
- What is your participant role? (Mention the Open Source program) Contributor (GSSoC)

*************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by abhisheks008** [comment]
Apart from LSTM any other models you know for this project?

**Comment by adwityac** [comment]
Nope, only LSTM

**Comment by abhisheks008** [comment]
Cool then go ahead. But this will be labelled as Level 1 only.
@adwityac

**Comment by abhisheks008** [comment]
Ongoing!!!
