### ISSUE TITLE
Breast Cancer Diagnosis Prediction Using Explainable AI Algorithms

### ISSUE THREAD

**Issue by inkerton** [abhisheks008/DL-Simplified#974]
### Deep Learning Simplified Repository (Proposing new issue)
:red_circle: **Project Title** : Breast Cancer Type Detection using Explainable AI </br>
:red_circle: **Aim** : The main objective of this project is to predict whether a tumor is benign or malignant using machine learning models and explain the model’s decisions using LIME (Local Interpretable Model-Agnostic Explanations). The dataset used in this project is the Breast Cancer Dataset available from Kaggle.</br>
:red_circle: **Dataset** : [https://www.kaggle.com/datasets/yasserh/breast-cancer-dataset](https://www.kaggle.com/datasets/yasserh/breast-cancer-dataset)</br>
:red_circle: **Approach** : Try to use 3-4 algorithms to implement the models and compare all the algorithms to find out the best fitted algorithm for the model by checking the accuracy scores. Also do not forget to do a exploratory data analysis before creating any model.

**********************************************************************************
### 📍 **Follow the Guidelines to Contribute in the Project :**
* You need to create a separate folder named as the Project Title.
* Inside that folder, there will be four main components.
   * Images - To store the required images.
   * Dataset - To store the dataset or, information/source about the dataset.
   * Model - To store the machine learning model you've created using the dataset.
   * `requirements.txt` - This file will contain the required packages/libraries to run the project in other machines.
* Inside the `Model` folder, the `README.md` file must be filled up properly, with proper visualizations and conclusions.

***********************************************************************
:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include issue number along with it.
- Follow Contributing Guidelines & Code of Conduct before start Contributing.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : inkerton
- GitHub Profile Link :  [inkerton](https://github.com/inkerton)
- Email ID : janvichoudhary116@gmail.com
- Participant ID (if applicable): 
- Approach for this Project : To add explainable AI models in the repo since this is a newly emerging field.
- What is your participant role? (Mention the Open Source program) **GSSOC**

*************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by abhisheks008** [comment]
Can you elaborate more on the approach? Didn't get the explainable AI approach!!

**Comment by inkerton** [comment]
Explainable Ai is the set of a;gorithms that explains the working behind a prediction like how did the Ai came to the conclusion that its a tumor and not just a ump or a ball of mass. The explaination of behind the process is termed as Explainable AI.

**Comment by abhisheks008** [comment]
Already present in this repository, hence closing this issue as a duplicate entry.
