### ISSUE TITLE
AI Resume Analyzer 

### ISSUE THREAD

**Issue by Niraj1608** [abhisheks008/DL-Simplified#975]
### Deep Learning Simplified Repository (Proposing new issue)
:red_circle: **Project Title** : **Resume AI Analyzer** </br>
:red_circle: **Aim** : This project aims to leverage machine learning techniques to help job seekers optimize their resumes for specific job applications. We are excited to have contributors who are interested in improving the job application process through AI.

:red_circle: **Features**

AI-Powered Resume Analysis: Gemini AI to analyze the content of resumes.
Keyword Extraction: Extracts key information such as skills, experiences, and educational background.
Strengths and Weaknesses Identification: Provides a detailed analysis of the candidate's strengths and areas of improvement.
Job Role Suggestions: Suggests relevant job roles based on resume content to enhance the candidate's job search.
Resume Summarization: Condenses the resume into a concise summary for quick evaluation

**********************************************************************************
### 📍 **Follow the Guidelines to Contribute in the Project :**
* You need to create a separate folder named as the Project Title.
* Inside that folder, there will be four main components.
   * Images - To store the required images.
   * Dataset - To store the dataset or, information/source about the dataset.
   * Model - To store the machine learning model you've created using the dataset.
   * `requirements.txt` - This file will contain the required packages/libraries to run the project in other machines.
* Inside the `Model` folder, the `README.md` file must be filled up properly, with proper visualizations and conclusions.

***********************************************************************
:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include issue number along with it.
- Follow Contributing Guidelines & Code of Conduct before start Contributing.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Niraj Parmar
- GitHub Profile Link : https://github.com/Niraj1608
- Email ID : nirajprmr1608@gmail.com
- Participant ID (if applicable):GSSOC Contributor
- Approach for this Project : using gpt and gemini ai 
- What is your participant role? GSSOC Contributor
*************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Niraj1608** [comment]
@abhisheks008 assign me this issue

**Comment by abhisheks008** [comment]
Are you going to use ChatGPT and Gemini AI's API keys for this project?
@Niraj1608

**Comment by Niraj1608** [comment]
@abhisheks008 yeah plus i also think to uses hugging face or opensource llm models for that

**Comment by Niraj1608** [comment]
Yeah sure :)
Hey im thinking to deploy with flask and strwmlit
Could you please increase the level 3 ?

**Comment by Niraj1608** [comment]
@abhisheks008
hey can i raise 2 prs like one with gemini ai and second one with nlp model

**Comment by abhisheks008** [comment]
Ongoing!!
