### ISSUE TITLE
Advance Anime Recommendation System 

### ISSUE THREAD

**Issue by Niraj1608** [abhisheks008/DL-Simplified#981]
### Deep Learning Simplified Repository (Proposing new issue)
:red_circle: **Project Title** :Advance Anime Recommendation System </br>
:red_circle: **Aim** :This project implements an Anime Recommendation System using both content-based and collaborative filtering techniques. It provides recommendations based on user preferences and anime content, leveraging deep learning for enhanced collaborative filtering. </br>
:red_circle: **Dataset** : The dataset is available on Kaggle:
- [Anime.csv and Rating.csv - Kaggle Dataset](https://www.kaggle.com/datasets/CooperUnion/anime-recommendations-database) </br>

:red_circle: **Approach** : using Nlp and DL techniques 

## Features

- **Data Preprocessing**: Cleans and preprocesses `anime.csv` and `rating.csv` datasets.
- **Exploratory Data Analysis (EDA)**: Provides an overview of anime types, genres, ratings, and other insights.
- **Content-Based Filtering**: Generates recommendations based on anime genres, type, and average ratings.
- **Collaborative Filtering**: A deep learning-based recommendation model that learns user preferences.
- **Genre-Based Recommendations**: Ensures diverse recommendations by including various genres in top recommendations.
- **New User and New Anime Recommendations**: Customized recommendations for new users and newly added anime.
- 
**********************************************************************************
### 📍 **Follow the Guidelines to Contribute in the Project :**
* You need to create a separate folder named as the Project Title.
* Inside that folder, there will be four main components.
   * Images - To store the required images.
   * Dataset - To store the dataset or, information/source about the dataset.
   * Model - To store the machine learning model you've created using the dataset.
   * `requirements.txt` - This file will contain the required packages/libraries to run the project in other machines.
* Inside the `Model` folder, the `README.md` file must be filled up properly, with proper visualizations and conclusions.

***********************************************************************
:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include issue number along with it.
- Follow Contributing Guidelines & Code of Conduct before start Contributing.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Parmar Niraj
- GitHub Profile Link : @Niraj1608
- Email ID : nirajprmr1608@gmail.com
- Participant ID (if applicable):GSSOC

- What is your participant role? (Mention the Open Source program)GSSOC

*************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Niraj1608** [comment]
@abhisheks008 assign me this issue ready to raise a pr

**Comment by abhisheks008** [comment]
Assigning this issue to you, @Niraj1608. Make sure you complete the previous PR first before pushing this PR.
