### ISSUE TITLE
Add back-to-top scroll up button in readme

### ISSUE THREAD

**Issue by T-Fathima** [abhisheks008/DL-Simplified#982]
### Deep Learning Simplified Repository (Proposing new issue)
:red_circle: **Project Title** :  Add back-to-top scroll up button in readme
:red_circle: **Aim** : The aim is to enhance the README file by implementing a button at the button for easier navigation in lengthy readme file.

***********************************************************************
:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include issue number along with it.
- Follow Contributing Guidelines & Code of Conduct before start Contributing.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name :  Tatheer Fathima
- GitHub Profile Link :  T-Fathima
- Email ID : tatheerfathima2004@gmail.com
- Participant ID (if applicable): T-Fathima
- What is your participant role? (Mention the Open Source program) gssoc-ext contributor.

@abhisheks008 I would like to work on it.
Please assign it to me.
*************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by abhisheks008** [comment]
No required!
