### ISSUE TITLE
Adding project contribution format 

### ISSUE THREAD

**Issue by SimranShaikh20** [abhisheks008/DL-Simplified#985]
### Deep Learning Simplified Repository (Proposing new issue)
:red_circle: **Project Title** : </br>Adding project contribution format to readme.md file
:red_circle: **Aim** : The aim is to enhance the README file and make it eye pleasing, well documented using the given README template.</br> To add format for contribution in project 

:red_circle: **README Template** : https://github.com/abhisheks008/DL-Simplified/blob/main/.github/readme_template.md

***********************************************************************
:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include issue number along with it.
- Follow Contributing Guidelines & Code of Conduct before start Contributing.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Simran Shaikh
- Approach for this Project : Adding important content to readme.md file
- What is your participant role? (Mention the Open Source program)
GSSOC 24 extd
*************************************************************
Happy Contributing 🚀 
@abhisheks008  assign me this issue!

All the best. Enjoy your open source journey ahead. 😎

**Comment by abhisheks008** [comment]
Hi @SimranShaikh20 please push your code.

**Comment by abhisheks008** [comment]
No need to create a PR for this issue, I'll fix it.
