### ISSUE TITLE
Research Topic Prediction using DL

### ISSUE THREAD

**Issue by SimranShaikh20** [abhisheks008/DL-Simplified#986]
Key points - A research-topic prediction model transforms how researchers access and discover knowledge, enabling rapid, relevant insights and fostering interdisciplinary innovation.

Problem Statement
Researchers have access to large online archives of scientific articles. As a consequence, finding relevant articles has become more difficult. Tagging or topic modelling provides a way to give token of identification to research articles which facilitates recommendation and search process.

Given the abstract and title for a set of research articles, predict the topics for each article included in the test set.
The research article abstracts and titles will  sourced from the following 6 topics:

The goal is to build a model that can predict topics for each article. Each article is represented by its title and abstract, and the model should classify it into one or more relevant topics from a predefined set of six fields.

Computer Science
Physics
Mathematics
Statistics
Quantitative Biology
Quantitative Finance

@abhisheks008 assign me this issue !

**Comment by abhisheks008** [comment]
What are the deep learning models you are planning to perform here?
@SimranShaikh20

**Comment by SimranShaikh20** [comment]
@abhisheks008 
model name - MultiOutputClassifier with a LinearSVC

**Comment by abhisheks008** [comment]
Push the code ASAP for review.
@SimranShaikh20

**Comment by SimranShaikh20** [comment]
yeah sure

**Comment by abhisheks008** [comment]
> yeah sure

Updated the issue/project folder name. Please follow the same

**Comment by SimranShaikh20** [comment]
> > yeah sure
> 
> Updated the issue/project folder name. Please follow the same

yeah i will make sure about it

can you pls share you email id for further communication ?

**Comment by abhisheks008** [comment]
> > > yeah sure
> > 
> > 
> > Updated the issue/project folder name. Please follow the same
> 
> yeah i will make sure about it
> 
> can you pls share you email id for further communication ?

It's there in my GitHub profile.
