### ISSUE TITLE
Fashion classifier model

### ISSUE THREAD

**Issue by shreyanshjain05** [abhisheks008/DL-Simplified#990]
end-to-end fashion classifier system

**Comment by abhisheks008** [comment]
Hi @shreyanshjain05 thanks for showing interest here. Can you please use the Issue Template for creating the new issue? It'll be better for me to understand what's the problem statement for this issue.

Closing this issue, requesting you to create a new issue using the given Issue Template.

![image](https://github.com/user-attachments/assets/f7edc8b8-5c46-4339-9977-d28c638fab5a)

**Comment by shreyanshjain05** [comment]
sure @abhisheks008
