### ISSUE TITLE
Understanding build of simple End to End ML model

### ISSUE THREAD

**Issue by shreyanshjain05** [abhisheks008/DL-Simplified#991]
### Deep Learning Simplified Repository (Proposing new issue)
:red_circle: **Project Title** : Understanding how to make an end to end ml model </br>
:red_circle: **Aim** : The aim is to understand how to make an end to endl ml model so it can. be deployed using python.</br>
:red_circle: **Dataset** : https://www.tensorflow.org/datasets/catalog/fashion_mnist </br>
:red_circle: **Approach** : In order to make the ml model i have used a CNN model which uses early stoping. For making an end to end system i have used streamlit and also created a docker image

***********************************************************************
:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include issue number along with it.
- Follow Contributing Guidelines & Code of Conduct before start Contributing.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Shreyansh Jain
- GitHub Profile Link : https://github.com/shreyanshjain05
- Email ID : shreyansh_jain2005@yahoo.com
- Participant ID (if applicable):
- Approach for this Project : CNN , Streamlit , Docker
- What is your participant role? Social Winter Of Code Season 5

*************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by abhisheks008** [comment]
Hi @shreyanshjain05 can you please elaborate on the problem statement you have proposed here? Also, implementing machine learning models will not work here, as the repository mainly focuses on deep learning models, hence it's expected that deep learning models will be implemented here.

Similar project is already present here in this repository, https://github.com/abhisheks008/DL-Simplified/tree/main/MNIST%20Digit%20Classification%20using%20Neural%20Networks
